### ISSUE TITLE
Api return 500 when moving document to a private collection  

### ISSUE THREAD

**Issue by zwwhdls** [outline/outline#1070]
Hi,

When I moved a document to a document of private collection, the status code of api "/api/documents.move" response turned to 500. The screenshot is as follows:
 
![image](https://user-images.githubusercontent.com/33822635/67362093-e6f48a80-f59c-11e9-8463-375319f9859b.png)

The request body:

```
{
  collectionId: "ed617e9d-a781-4581-b71f-abc97198fa30"
  id: "16c6a072-8fd2-4c68-8946-ce7aa154fbe4"
  parentDocumentId: "5cae0985-eea1-421c-adab-0a44587a4265"
}
```

The error logs:

```
Invariant Violation: membership should be preloaded, did you forget withMembership scope?
      at invariant (/opt/outline/node_modules/invariant/invariant.js:40:15)
      at Object.condition (/opt/outline/server/policies/collection.js:28:5)
      at /opt/outline/node_modules/cancan/index.js:61:21
      at Array.filter (<anonymous>)
      at CanCan.can (/opt/outline/node_modules/cancan/index.js:59:5)
      at CanCan.cannot (/opt/outline/node_modules/cancan/index.js:70:20)
      at Object.condition (/opt/outline/server/policies/document.js:48:7)
      at /opt/outline/node_modules/cancan/index.js:61:21
      at Array.filter (<anonymous>)
      at CanCan.can (/opt/outline/node_modules/cancan/index.js:59:5)
      at CanCan.cannot (/opt/outline/node_modules/cancan/index.js:70:20)
      at CanCan.authorize (/opt/outline/node_modules/cancan/index.js:74:19)
      at _callee19$ (/opt/outline/server/api/documents.js:818:5)
      at tryCatch (/opt/outline/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (/opt/outline/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.<computed> [as next] (/opt/outline/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (/opt/outline/server/api/documents.js:45:191)
      at /opt/outline/server/api/documents.js:45:361
```

**Comment by tommoor** [comment]
Hey, this was fixed here 2d2ad83469f1107126df7b86266e13c37bd74d45 a week or so ago, I'd recommend running from master to get the fix.
