### ISSUE TITLE
Slack login problem on docker, aws ec2, nginx

### ISSUE THREAD

**Issue by vitorgga** [outline/outline#1239]
I have a  problem on run Outline in AWS Ec2 Ubuntu, over Docker, and Nginx. All problems i have is on slack configure, i create slack app, but never function (i try in heroku too, no success).

`BadRequestError: code_already_used
    at new InvalidRequestError (/opt/outline/server/errors.js:32:10)
    at _callee2$ (/opt/outline/server/slack.js:40:23)
    at tryCatch (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (/opt/outline/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/opt/outline/server/slack.js:157:191)
    at /opt/outline/server/slack.js:157:361
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

In heroku i have always this error:
Authentication failed - we were unable to sign you in at this time. Please try again.

**Comment by tommoor** [comment]
Hi, this issue tracker is for bugs in the software – we cannot provide personal support for running your own instance.

That said, `code_already_used` is coming from Slack – it means that the last part of the OAuth request where you exchange a code for a token was made twice. We see this internally usually when folks refresh the page during the authorization process. Hope that helps
