### ISSUE TITLE
Installing self hosted Outline with only one gmail account for personal use

### ISSUE THREAD

**Issue by flaviuse** [outline/outline#1257]
Hi,
I installed Outline previously for the documentation of a startup, I wanted to run my own self hosted version for taking notes but the trick showed of hardcoding profile.data.hd does not work for me, I run into a timeout when trying a loging with my gmail account, it seems to be a problem with the oauth tokens but I could not find the issue. Any idea ? 
<details> 

```
2020-05-03T20:13:57.283623+00:00 heroku[router]: at=info method=GET path="/auth/google.callback?code=4%2FzQEWd7dCOXkNtIvqCze6W0HBUiEafPOdYgAH6Yh-Z4TQO3WzlHG37tS4_mqnLrePX9s_DkyNgA-UwE0YnD-B8-A&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=consent" host=mydocumentation.herokuapp.com request_id=7f338704-547c-4e02-b3ce-befa3b99f6dc fwd="81.185.174.203" dyno=web.1 connect=8ms service=119ms status=500 bytes=737 protocol=https

2020-05-03T20:14:40+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.285 sample#load-avg-5m=0.225 sample#load-avg-15m=0.175 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11709784kB sample#memory-cached=818268kB sample#memory-redis=447136bytes sample#hit-rate=0.0099302 sample#evicted-keys=0

2020-05-03T20:14:40+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.11 sample#load-avg-5m=0.19 sample#load-avg-15m=0.17 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705396kB sample#memory-cached=818272kB sample#memory-redis=488088bytes sample#hit-rate=0.0097529 sample#evicted-keys=0

2020-05-03T20:18:05+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.065 sample#load-avg-5m=0.12 sample#load-avg-15m=0.145 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705128kB sample#memory-cached=818288kB sample#memory-redis=447136bytes sample#hit-rate=0.010077 sample#evicted-keys=0

2020-05-03T20:21:18+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.13 sample#load-avg-5m=0.14 sample#load-avg-15m=0.15 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705600kB sample#memory-cached=818288kB sample#memory-redis=446936bytes sample#hit-rate=0.010031 sample#evicted-keys=0

2020-05-03T20:24:43+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.115 sample#load-avg-5m=0.14 sample#load-avg-15m=0.145 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705028kB sample#memory-cached=818296kB sample#memory-redis=447136bytes sample#hit-rate=0.010086 sample#evicted-keys=0

2020-05-03T20:27:21.948842+00:00 heroku[router]: at=info method=GET path="/" host=mydocumentation.herokuapp.com request_id=0284563f-b459-47bf-9832-331a150de232 fwd="81.185.174.203" dyno=web.1 connect=6ms service=46ms status=200 bytes=4679 protocol=https

2020-05-03T20:27:23.483545+00:00 heroku[router]: at=info method=GET path="/auth/google" host=mydocumentation.herokuapp.com request_id=321bb799-a52a-478b-8f02-14ad85f62d3b fwd="81.185.174.203" dyno=web.1 connect=1ms service=4ms status=302 bytes=1403 protocol=https

2020-05-03T20:24:43+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.13 sample#load-avg-5m=0.135 sample#load-avg-15m=0.14 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11704432kB sample#memory-cached=818300kB sample#memory-redis=488088bytes sample#hit-rate=0.0099278 sample#evicted-keys=0

2020-05-03T20:27:56.474645+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/auth/google.callback?code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=consent" host=mydocumentation.herokuapp.com request_id=3a23f0a1-fe57-4fb0-9231-d3bebd3bf92e fwd="81.185.174.203" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https

2020-05-03T20:27:56.810447+00:00 heroku[router]: at=info method=GET path="/auth/google.callback?code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=consent" host=mydocumentation.herokuapp.com request_id=eabb92d7-479f-4c6b-9141-c761b3f3f709 fwd="81.185.174.203" dyno=web.1 connect=1ms service=80ms status=500 bytes=737 protocol=https

2020-05-03T20:27:56.811296+00:00 app[web.1]: GaxiosError: invalid_grant

2020-05-03T20:27:56.811337+00:00 app[web.1]:     at Gaxios._request (/app/node_modules/gaxios/src/gaxios.ts:109:15)

2020-05-03T20:27:56.811339+00:00 app[web.1]:     at runMicrotasks (<anonymous>)

2020-05-03T20:27:56.811339+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

2020-05-03T20:27:56.811340+00:00 app[web.1]:     at OAuth2Client.getTokenAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:122:21) {

2020-05-03T20:27:56.811341+00:00 app[web.1]:   response: {

2020-05-03T20:27:56.811342+00:00 app[web.1]:     config: {

2020-05-03T20:27:56.811342+00:00 app[web.1]:       method: 'POST',

2020-05-03T20:27:56.811343+00:00 app[web.1]:       url: 'https://oauth2.googleapis.com/token',

2020-05-03T20:27:56.811344+00:00 app[web.1]:       data: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-fldah0htukrb4nrkoge0rqmh71m5lkadg.fzfzfezapps.gozfefzzogleusercontent.com&client_secret=t5zmCfx6Dfezfzfezfzfzm6CFh2gNw-i3FfD&redirect_uri=http%3A%2F%2Fmydocumentation.herokuapp.com%2Fauth%2Fgoogle.callback&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811345+00:00 app[web.1]:       headers: [Object],

2020-05-03T20:27:56.811345+00:00 app[web.1]:       params: [Object: null prototype] {},

2020-05-03T20:27:56.811345+00:00 app[web.1]:       paramsSerializer: [Function: paramsSerializer],

2020-05-03T20:27:56.811346+00:00 app[web.1]:       body: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-ldah0htukrb4nrkoge0zerzrerqmh71m5lkadg.appsrezrez.googleusercorezrzerzeezrrezntent.com&client_secret=t5zmCfxzrezre6Dm6CFrzerzrezh2gNw-i3FfD&redirect_uri=http%3A%2F%2Fmydocumentation.herokuapp.com%2Fauth%2Fgoogle.callback&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811346+00:00 app[web.1]:       validateStatus: [Function: validateStatus],

2020-05-03T20:27:56.811347+00:00 app[web.1]:       responseType: 'json'

2020-05-03T20:27:56.811347+00:00 app[web.1]:     },

2020-05-03T20:27:56.811347+00:00 app[web.1]:     data: { error: 'invalid_grant', error_description: 'Bad Request' },

2020-05-03T20:27:56.811348+00:00 app[web.1]:     headers: {

2020-05-03T20:27:56.811348+00:00 app[web.1]:       'alt-svc': 'h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',

2020-05-03T20:27:56.811349+00:00 app[web.1]:       'cache-control': 'private',

2020-05-03T20:27:56.811349+00:00 app[web.1]:       connection: 'close',

2020-05-03T20:27:56.811349+00:00 app[web.1]:       'content-encoding': 'gzip',

2020-05-03T20:27:56.811350+00:00 app[web.1]:       'content-type': 'application/json; charset=utf-8',

2020-05-03T20:27:56.811350+00:00 app[web.1]:       date: 'Sun, 03 May 2020 20:27:56 GMT',

2020-05-03T20:27:56.811350+00:00 app[web.1]:       server: 'scaffolding on HTTPServer2',

2020-05-03T20:27:56.811351+00:00 app[web.1]:       'transfer-encoding': 'chunked',

2020-05-03T20:27:56.811351+00:00 app[web.1]:       vary: 'Origin, X-Origin, Referer',

2020-05-03T20:27:56.811351+00:00 app[web.1]:       'x-content-type-options': 'nosniff',

2020-05-03T20:27:56.811352+00:00 app[web.1]:       'x-frame-options': 'SAMEORIGIN',

2020-05-03T20:27:56.811352+00:00 app[web.1]:       'x-xss-protection': '0'

2020-05-03T20:27:56.811352+00:00 app[web.1]:     },

2020-05-03T20:27:56.811352+00:00 app[web.1]:     status: 400,

2020-05-03T20:27:56.811353+00:00 app[web.1]:     statusText: 'Bad Request',

2020-05-03T20:27:56.811353+00:00 app[web.1]:     request: { responseURL: 'https://oauth2.googleapis.com/token' }

2020-05-03T20:27:56.811354+00:00 app[web.1]:   },

2020-05-03T20:27:56.811354+00:00 app[web.1]:   config: {

2020-05-03T20:27:56.811354+00:00 app[web.1]:     method: 'POST',

2020-05-03T20:27:56.811354+00:00 app[web.1]:     url: 'https://oauth2.googleapis.com/token',

2020-05-03T20:27:56.811355+00:00 app[web.1]:     data: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-ldah0htukrb4kruknrkoge0rqmh71m5lkadg.apps.googleusercomioumjytjrntent.com&client_secret=t5zmCfx6Dm6uyjrjryjruryjCFh2gNw-i3FfD&redirect_uri=http%3A%2F%2Fmydocumentation.herokrjyuapp.com%2Fauth%2Fgoogle.callback&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811355+00:00 app[web.1]:     headers: {

2020-05-03T20:27:56.811355+00:00 app[web.1]:       'Content-Type': 'application/x-www-form-urlencoded',

2020-05-03T20:27:56.811356+00:00 app[web.1]:       'User-Agent': 'google-api-nodejs-client/5.10.1',

2020-05-03T20:27:56.811356+00:00 app[web.1]:       'x-goog-api-client': 'gl-node/14.1.0 auth/5.10.1',

2020-05-03T20:27:56.811356+00:00 app[web.1]:       Accept: 'application/json'

2020-05-03T20:27:56.811356+00:00 app[web.1]:     },

2020-05-03T20:27:56.811357+00:00 app[web.1]:     params: [Object: null prototype] {},

2020-05-03T20:27:56.811357+00:00 app[web.1]:     paramsSerializer: [Function: paramsSerializer],

2020-05-03T20:27:56.811357+00:00 app[web.1]:     body: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-ldah0htukrb4nrkoge0rqmh71m5lkadg.apps.googfezfzfzeleusercontent.com&client_secret=fezzefzfe
t5zmCfx6Dm6CfezfezFh2gNw-i3FfD&fezedirect_uri=hfezfzefezttp%3A%2F%2Fmydocumentation.herokuapp.com%2Fauth%2Fgoogle.callbzefack&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811358+00:00 app[web.1]:     validateStatus: [Function: validateStatus],

2020-05-03T20:27:56.811358+00:00 app[web.1]:     responseType: 'json'

2020-05-03T20:27:56.811358+00:00 app[web.1]:   },

2020-05-03T20:27:56.811358+00:00 app[web.1]:   code: '400'

2020-05-03T20:27:56.811359+00:00 app[web.1]: }

```

</details>

_Originally posted by @flaviuse in https://github.com/outline/outline/issues/883#issuecomment-623176613_

**Comment by tommoor** [comment]
Invalid grant can mean lots of different things unfortunately, this blog post provides some examples:

https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35
