### ISSUE TITLE
TypeError: Cannot read property 'waitUntilValid' of undefined

### ISSUE THREAD

**Issue by TiemcoM** [outline/outline#1548]
I am new, so sorry if this is a stupid question

I am trying to use outline in docker, after following all the steps in the Installation, when i try to open outline in gives me a error

TypeError: Cannot read property 'waitUntilValid' of undefined
    at /Users/tiemcomeernik/Documents/GitHub/outline/build/server/routes.js:70:33
    at new Promise (<anonymous>)
    at _callee$ (/Users/tiemcomeernik/Documents/GitHub/outline/build/server/routes.js:69:20)
    at tryCatch (/Users/tiemcomeernik/Documents/GitHub/outline/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/tiemcomeernik/Documents/GitHub/outline/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/Users/tiemcomeernik/Documents/GitHub/outline/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/tiemcomeernik/Documents/GitHub/outline/build/server/routes.js:42:103)
    at _next (/Users/tiemcomeernik/Documents/GitHub/outline/build/server/routes.js:44:194)
    at /Users/tiemcomeernik/Documents/GitHub/outline/build/server/routes.js:44:364
    at new Promise (<anonymous>)
        

I followed all the steps and the previous time doing this is worked just fine after following the same steps

I am hosting this on a iMac, the browser i use is google chrome

Can someone help me with this?

**Comment by tommoor** [comment]
Are you attempting to build from master? The documentation needs updating. You should run from the tag, not from master:
https://github.com/outline/outline/tree/v0.47.1

OR even better, the docker image:
outlinewiki/outline:latest

**Comment by renanfilipe** [comment]
I'm having the same issue in the branch `develop`.

**Comment by guilherme-diniz** [comment]
@tommoor , @renanfilipe and I are developing for Rock on this. Should we base our taks from this tag as well? Or we wait until the develop is fixed?

**Comment by tommoor** [comment]
Generally dev work should happen from head, I've been working against it without an issue – I'm not sure what this problem is to be honest. Perhaps NODE_ENV isn't set to `development`?

**Comment by renanfilipe** [comment]
adding NODE_ENV=development to the .env file made it work, thanks

**Comment by tommoor** [comment]
@TiemcoM in your case you'll need to add `NODE_ENV=production`, I'll fix up the mismatch that makes this bug happen.

**Comment by TiemcoM** [comment]
@tommoor NODE_ENV=production gave the following error 
ERROR: The server does not support SSL connections

Switched NODE_ENV to development and it worked fine, thank you for the help!

**Comment by tommoor** [comment]
You probably need `NODE_ENV=production` and `FORCE_HTTPS=false`
