### ISSUE TITLE
yarn db:migrate not found

### ISSUE THREAD

**Issue by alvxi** [outline/outline#1982]
When trying to run `docker run --rm outlinewiki/outline yarn db:migrate` it triggers the following error:

```
ubuntu@host:~$ docker run --rm outlinewiki/outline yarn db:migrate
yarn run v1.22.5
error Command "db:migrate" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tommoor** [comment]
Instructions were recently updated and will apply to the next release, see README for the version you're running here – command is slightly different 😄 

https://github.com/outline/outline/tree/v0.54.0

**Comment by alvxi** [comment]
Thanks for the quick answer. I ran docker with yarn sequelize:migrate and it triggers this error:
```
ubuntu@host:~$ sudo docker run --rm outlinewiki/outline yarn sequelize:migrate
yarn run v1.22.5
$ sequelize db:migrate

Sequelize CLI [Node: 14.16.0, CLI: 6.2.0, ORM: 6.3.5]

Loaded configuration file "server/config/database.json".
Using environment "production".

ERROR: Error parsing url: undefined

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tommoor** [comment]
I'm guessing you didn't configure your DATABASE_URL? 🤷

**Comment by alvxi** [comment]
This is my .env file part for DBs:

```
DATABASE_URL=postgres://postgres:pgs_pwd@host.compute.amazonaws.com:5432/db-name
DATABASE_URL_TEST=postgres://postgres:password@localhost:5432/outline
REDIS_URL=redis://default:default_pwd@redis-host.redislabs.com:19686
```
I checked connection via localhost and remote and both work fine on pgAdmin

**Comment by alvxi** [comment]
For some kind of reason, when I was running `sudo docker run --env-file=.env outlinewiki/outline` it was triggering the following error (among other consequent errors):

`UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED`

So I managed to solve this issue by replacing localhost on .env file (at DB URL) with the actual public IP of the server.
But, when I run `sudo docker run --env-file=.env outlinewiki/outline` again, it triggers the following error:

```
ubuntu@host:~$ sudo docker run --env-file=.env outlinewiki/outline
yarn run v1.22.5
$ node ./build/server/index.js

Running Outline in production mode.
2021-03-24T21:31:21.401Z services loaded backlinks service
2021-03-24T21:31:21.402Z services loaded debouncer service
2021-03-24T21:31:21.403Z services loaded importer service
2021-03-24T21:31:21.403Z services loaded notifications service
2021-03-24T21:31:21.403Z services loaded revisions service
2021-03-24T21:31:21.404Z services loaded slack service
2021-03-24T21:31:21.404Z services loaded websockets service
2021-03-24T21:31:21.706Z server loaded Email auth provider
2021-03-24T21:31:21.706Z server loaded Google auth provider
2021-03-24T21:31:21.706Z server loaded Slack auth provider
(node:28) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: relation "users" does not exist
    at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.rawSelect (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:980:18)
    at async Function.aggregate (/opt/outline/node_modules/sequelize/lib/model.js:1986:19)
    at async Function.count (/opt/outline/node_modules/sequelize/lib/model.js:2037:12)
    at async Promise.all (index 0)
    at async _default (/opt/outline/build/server/utils/updates.js:31:66)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: relation "teams" does not exist
    at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.rawSelect (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:980:18)
    at async Function.aggregate (/opt/outline/node_modules/sequelize/lib/model.js:1986:19)
    at async Function.count (/opt/outline/node_modules/sequelize/lib/model.js:2037:12)
    at async checkMigrations (/opt/outline/build/server/utils/startup.js:15:17)
    at async /opt/outline/build/server/main.js:191:3
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
It seems like this error is due to DBs aren't with the supposed structure yet, so I ran `sudo docker run --rm outlinewiki/outline yarn sequelize:migrate` and this was the output, again:

```
ubuntu@host:~$ sudo docker run --rm outlinewiki/outline yarn sequelize:migrate
yarn run v1.22.5
$ sequelize db:migrate

Sequelize CLI [Node: 14.16.0, CLI: 6.2.0, ORM: 6.3.5]

Loaded configuration file "server/config/database.json".
Using environment "production".

ERROR: Error parsing url: undefined

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tommoor** [comment]
Looks like you need to pass `--env-file=.env` to the migrate command too?

**Comment by alvxi** [comment]
It worked, sorry for the inconvenience.

**Comment by rromanchuk** [comment]
this is really dumb, and not really an outline problem, but if you're moving from non-containerized to containerized and doing a quick sanity check using README, eg: 

`docker run --env-file=.env outlinewiki/outline` 

Don't forget that even if you're passing .env, maybe with custom proxy ports etc,  you still have to tell docker to bind/publish to the host.  `docker run -p 3000:3000 --env-file=.env outlinewiki/outline`

Not going to admit how long it took me to debug that 🤦 

Also, if you're coming from building from source, be aware `docker-compose.yml` in the directory, so slowwwwwwwwww down.
