### ISSUE TITLE
[BadRequestError]: State not return in OAuth flow after upgrade v54.0.0. 

### ISSUE THREAD

**Issue by tiagocamargo** [outline/outline#1985]
After upgrading to version 0.54.0 I can no longer authenticate. It is a Self hosted installation.

I followed the guidelines, running `sequelize:migrate` afterwards`node build/server/scripts/20210226232041-migrate-authentication.js`.

The `user_authentications` table is populated.

When trying to login via Google I have this log with debug:

```
0|outline  | ClientError [BadRequestError]: State not return in OAuth flow
0|outline  |     at new OAuthStateMismatchError (/home/portabilis/outline/build/server/errors.js:96:34)
0|outline  |     at StateStore.verify (/home/portabilis/outline/build/server/utils/passport.js:38:25)
0|outline  |     at Strategy.OAuth2Strategy.authenticate (/home/portabilis/outline/node_modules/passport-oauth2/lib/strategy.js:219:26)
0|outline  |     at Strategy.authenticate (/home/portabilis/outline/node_modules/passport-google-oauth2/lib/oauth2.js:62:41)
0|outline  |     at attempt (/home/portabilis/outline/node_modules/passport/lib/middleware/authenticate.js:366:16)
0|outline  |     at authenticate (/home/portabilis/outline/node_modules/passport/lib/middleware/authenticate.js:367:7)
0|outline  |     at /home/portabilis/outline/node_modules/@outlinewiki/koa-passport/lib/framework/koa.js:194:7
0|outline  |     at new Promise (<anonymous>)
0|outline  |     at /home/portabilis/outline/node_modules/@outlinewiki/koa-passport/lib/framework/koa.js:193:12
0|outline  |     at /home/portabilis/outline/node_modules/@outlinewiki/koa-passport/lib/framework/koa.js:143:7
0|outline  |     at new Promise (<anonymous>)
0|outline  |     at passportAuthenticate (/home/portabilis/outline/node_modules/@outlinewiki/koa-passport/lib/framework/koa.js:107:15)
0|outline  |     at passportMiddleware (/home/portabilis/outline/build/server/middlewares/passport.js:36:7)
0|outline  |     at dispatch (/home/portabilis/outline/node_modules/koa-compose/index.js:44:32)
0|outline  |     at next (/home/portabilis/outline/node_modules/koa-compose/index.js:45:18)
0|outline  |     at authMiddleware (/home/portabilis/outline/build/server/middlewares/authentication.js:164:12) {
0|outline  |   id: 'state_mismatch'
0|outline  | }
0|outline  | 2021-03-24T21:34:27.404Z sql Executing (default): SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."guestSignin", "team"."documentEmbeds", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL); {
0|outline  |   plain: false,
0|outline  |   raw: false,
0|outline  |   logging: [Function: debug] {
0|outline  |     namespace: 'sql',
0|outline  |     enabled: true,
0|outline  |     useColors: false,
0|outline  |     color: 6,
0|outline  |     destroy: [Function: destroy],
0|outline  |     extend: [Function: extend],
0|outline  |     inspectOpts: {},
0|outline  |     diff: 438997,
0|outline  |     prev: 1616621228407,
0|outline  |     curr: 1616621667404
0|outline  |   },
0|outline  |   hooks: true,
0|outline  |   rejectOnEmpty: false,
0|outline  |   include: [
0|outline  |     {
0|outline  |       model: authentication_providers,
0|outline  |       as: 'authenticationProviders',
0|outline  |       parent: [Object],
0|outline  |       topLimit: undefined,
0|outline  |       association: authenticationProviders,
0|outline  |       attributes: [Array],
0|outline  |       required: false,
0|outline  |       duplicating: true,
0|outline  |       hasDuplicating: true,
0|outline  |       hasRequired: false,
0|outline  |       hasParentWhere: false,
0|outline  |       hasParentRequired: false,
0|outline  |       subQuery: false,
0|outline  |       subQueryFilter: false
0|outline  |     }
0|outline  |   ],
0|outline  |   originalAttributes: [
0|outline  |     'id',          'name',
0|outline  |     'subdomain',   'domain',
0|outline  |     'slackId',     'googleId',
0|outline  |     'avatarUrl',   'sharing',
0|outline  |     'guestSignin', 'documentEmbeds',
0|outline  |     'createdAt',   'updatedAt',
0|outline  |     'deletedAt'
0|outline  |   ],
0|outline  |   hasJoin: true,
0|outline  |   model: team,
0|outline  |   includeNames: [ 'authenticationProviders' ],
0|outline  |   includeMap: {
0|outline  |     authenticationProviders: {
0|outline  |       model: authentication_providers,
0|outline  |       as: 'authenticationProviders',
0|outline  |       parent: [Object],
0|outline  |       topLimit: undefined,
0|outline  |       association: authenticationProviders,
0|outline  |       attributes: [Array],
0|outline  |       required: false,
0|outline  |       duplicating: true,
0|outline  |       hasDuplicating: true,
0|outline  |       hasRequired: false,
0|outline  |       hasParentWhere: false,
0|outline  |       hasParentRequired: false,
0|outline  |       subQuery: false,
0|outline  |       subQueryFilter: false
0|outline  |     }
0|outline  |   },
0|outline  |   hasSingleAssociation: false,
0|outline  |   hasMultiAssociation: true,
0|outline  |   topModel: team,
0|outline  |   topLimit: undefined,
0|outline  |   hasDuplicating: true,
0|outline  |   hasRequired: false,
0|outline  |   hasWhere: false,
0|outline  |   hasIncludeWhere: false,
0|outline  |   hasIncludeRequired: false,
0|outline  |   subQuery: false,
0|outline  |   attributes: [
0|outline  |     'id',          'name',
0|outline  |     'subdomain',   'domain',
0|outline  |     'slackId',     'googleId',
0|outline  |     'avatarUrl',   'sharing',
0|outline  |     'guestSignin', 'documentEmbeds',
0|outline  |     'createdAt',   'updatedAt',
0|outline  |     'deletedAt'
0|outline  |   ],
0|outline  |   where: '("team"."deletedAt" IS NULL)',
0|outline  |   tableNames: [ 'teams', 'authentication_providers' ],
0|outline  |   type: 'SELECT',
0|outline  |   keysEscaped: true
0|outline  | }
0|outline  | 2021-03-24T21:34:27.411Z sql Executing (default): SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."guestSignin", "team"."documentEmbeds", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL AND "team"."domain" = 'bussola'); {
0|outline  |   plain: true,
0|outline  |   raw: false,
0|outline  |   logging: [Function: debug] {
0|outline  |     namespace: 'sql',
0|outline  |     enabled: true,
0|outline  |     useColors: false,
0|outline  |     color: 6,
0|outline  |     destroy: [Function: destroy],
0|outline  |     extend: [Function: extend],
0|outline  |     inspectOpts: {},
0|outline  |     diff: 7,
0|outline  |     prev: 1616621667404,
0|outline  |     curr: 1616621667411
0|outline  |   },
0|outline  |   where: `("team"."deletedAt" IS NULL AND "team"."domain" = 'bussola')`,
0|outline  |   hooks: true,
0|outline  |   rejectOnEmpty: false,
0|outline  |   include: [
0|outline  |     {
0|outline  |       model: authentication_providers,
0|outline  |       as: 'authenticationProviders',
0|outline  |       parent: [Object],
0|outline  |       topLimit: undefined,
0|outline  |       association: authenticationProviders,
0|outline  |       attributes: [Array],
0|outline  |       required: false,
0|outline  |       duplicating: true,
0|outline  |       hasDuplicating: true,
0|outline  |       hasRequired: false,
0|outline  |       hasParentWhere: true,
0|outline  |       hasParentRequired: false,
0|outline  |       subQuery: false,
0|outline  |       subQueryFilter: false
0|outline  |     }
0|outline  |   ],
0|outline  |   originalAttributes: [
0|outline  |     'id',          'name',
0|outline  |     'subdomain',   'domain',
0|outline  |     'slackId',     'googleId',
0|outline  |     'avatarUrl',   'sharing',
0|outline  |     'guestSignin', 'documentEmbeds',
0|outline  |     'createdAt',   'updatedAt',
0|outline  |     'deletedAt'
0|outline  |   ],
0|outline  |   hasJoin: true,
0|outline  |   model: team,
0|outline  |   includeNames: [ 'authenticationProviders' ],
0|outline  |   includeMap: {
0|outline  |     authenticationProviders: {
0|outline  |       model: authentication_providers,
0|outline  |       as: 'authenticationProviders',
0|outline  |       parent: [Object],
0|outline  |       topLimit: undefined,
0|outline  |       association: authenticationProviders,
0|outline  |       attributes: [Array],
0|outline  |       required: false,
0|outline  |       duplicating: true,
0|outline  |       hasDuplicating: true,
0|outline  |       hasRequired: false,
0|outline  |       hasParentWhere: true,
0|outline  |       hasParentRequired: false,
0|outline  |       subQuery: false,
0|outline  |       subQueryFilter: false
0|outline  |     }
0|outline  |   },
0|outline  |   hasSingleAssociation: false,
0|outline  |   hasMultiAssociation: true,
0|outline  |   topModel: team,
0|outline  |   topLimit: undefined,
0|outline  |   hasDuplicating: true,
0|outline  |   hasRequired: false,
0|outline  |   hasWhere: false,
0|outline  |   hasIncludeWhere: false,
0|outline  |   hasIncludeRequired: false,
0|outline  |   subQuery: false,
0|outline  |   attributes: [
0|outline  |     'id',          'name',
0|outline  |     'subdomain',   'domain',
0|outline  |     'slackId',     'googleId',
0|outline  |     'avatarUrl',   'sharing',
0|outline  |     'guestSignin', 'documentEmbeds',
0|outline  |     'createdAt',   'updatedAt',
0|outline  |     'deletedAt'
0|outline  |   ],
0|outline  |   tableNames: [ 'teams', 'authentication_providers' ],
0|outline  |   type: 'SELECT',
0|outline  |   keysEscaped: true
0|outline  | }
```

- Install: self hosted
- Version: 0.54.0

Ubuntu 20.04 LTS, yarn 1.22.5, Postgresql 12, node 14.16.0.

**Comment by tommoor** [comment]
It seems like the state cookie could not be found, it lasts 10minutes – I'm guessing you didn't take more than 10minutes to authenticate? It would be useful to know:

- is there a `state` parameter in the url from Google?
- is there a `state` cookie stored
- are you using https?
- what is the format of the domain name?

**Comment by tiagocamargo** [comment]
The problem seems to be linked with Google oauth update of my account. I made the necessary adjustments and sent them for approval.

- is there a state parameter in the url from Google?
How do I see this?

- is there a state cookie stored
I don't have any related cookies linked to my domain after oauth.

-  are you using https?
I use nginx as a proxy. The outline is with `FORCE_HTTPS = false`, and` URL = https: // ... `

-  what is the format of the domain name?
https://bussola.portabilis.com.br

**Comment by tommoor** [comment]
- is there a state parameter in the url from Google?
  You would see `state=something` in the url that Google redirects to. You might have to use developer tools to log all of the redirects that happen
  
- I don't have any related cookies linked to my domain after oauth.
   This is the problem, the app sets a cookie before sending to Google - we need to figure out why it isn't persisting. My guess would be that the domain it's trying to set to is incorrect here: https://github.com/outline/outline/blob/main/server/utils/passport.js#L15-L19
   
     is `SUBDOMAINS_ENABLED` set to false or unset? (It should be)

**Comment by tiagocamargo** [comment]
Hi!

I have a state:

``` 
/auth/google.callback?state=i5q4y&code=4%2F0AY0e-g55F_k9xholXnaSdzUSADawU__XmZs72RKh-wqk9g1fgzRbxdbxZymb7mc0PDpidw&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&hd=portabilis.com.br&prompt=none
```

In `SUBDOMAINS_ENABLED` already use `true` and `false`.

I'll take a look at `passport.js`.

**Comment by tommoor** [comment]
> In SUBDOMAINS_ENABLED already use true and false.

If it's set at all try unsetting it.

**Comment by tiagocamargo** [comment]
Does not work.

In version 0.53 authenticating normally.

**Comment by tommoor** [comment]
Just a note: passing the state was introduced in `v0.54` as an extra security measure to prevent MITM attacks, so it makes sense that it would work in `v0.53`. If you're able to capture the response from the `/auth/google` request that should tell us if the cookie is attempting to set.

**Comment by realvinay** [comment]
> Just a note: passing the state was introduced in `v0.54` as an extra security measure to prevent MITM attacks, so it makes sense that it would work in `v0.53`.
> 
> If you're able to capture the response from the `/auth/google` request that should tell us if the cookie is attempting to set correctly. FWIW this is working in production on getoutline.com, it looks like this:
> 
> ![image](https://user-images.githubusercontent.com/380914/112696650-79105a80-8e43-11eb-9fa2-e66db69bacc2.png)

I had the exact issue after an upgrade to self-hosted instance. The frontend proxy was sending the wrong domain (local IP), changed it and it worked.

**Comment by deletosh** [comment]
I can confirm this same issue on slack

**Comment by tiagocamargo** [comment]
> I can confirm this same issue on slack

We don't use slack. :(

> I had the exact issue after an upgrade to self-hosted instance. Our frontend proxy was sending the wrong domain (local IP), changed it and it worked.

I will check how the proxy is configured here.

**Comment by wintersrd** [comment]
We also had the same issue and had to add additional proxy settings to nginx to resolve specifically:
```
        location / {
                 proxy_pass http://127.0.0.1:3000;
                 proxy_ignore_client_abort on;
                 proxy_set_header Host $host;
                 proxy_set_header X-Forwarded-Proto $scheme;
        }
```

**Comment by tiagocamargo** [comment]
I removed the following parameters from nginx:
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
``` 

Now it looks like this:
```
proxy_pass http://outline
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Connection keep-alive;
proxy_set_header Host $host;
proxy_http_version 1.1;

proxy_ssl_session_reuse on;
proxy_ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
proxy_ssl_ciphers   HIGH:!aNULL:!MD5;
```

You are logging in normally.

Thank you all for your help!

**Comment by deletosh** [comment]
> > Just a note: passing the state was introduced in `v0.54` as an extra security measure to prevent MITM attacks, so it makes sense that it would work in `v0.53`.
> > If you're able to capture the response from the `/auth/google` request that should tell us if the cookie is attempting to set correctly. FWIW this is working in production on getoutline.com, it looks like this:
> > ![image](https://user-images.githubusercontent.com/380914/112696650-79105a80-8e43-11eb-9fa2-e66db69bacc2.png)
> 
> I had the exact issue after an upgrade to self-hosted instance. Our frontend proxy was sending the wrong domain (local IP), changed it and it worked.

Expanding on this, what is not being set properly is the domain in the cookie being set as the wrong domain is sent.

Here's how to resolve this as mentioned above: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_domain

**Comment by aCodeAlchemist** [comment]
@realvinay 

can you please let me know where did you changed cookie domain for front end proxy?

**Comment by maidh91** [comment]
FYI, this is my config for Apache Proxy

```
<VirtualHost *:443>
  ServerName outline.example.com

  SSLEngine on
  SSLCertificateFile /etc/letsencrypt/live/example.com/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
  SSLCertificateChainFile /etc/letsencrypt/live/example.com/chain.pem

  ProxyPass / http://localhost:8000/
  ProxyPassReverse / http://localhost:8000/

  ProxyPreserveHost On
  RequestHeader set X-Forwarded-Proto: "https"
</VirtualHost>
```

Adding the last 2 lines makes life working perfectly

**Comment by dkkb** [comment]
> I removed the following parameters from nginx:
> 
> ```
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> ```
> 
> Now it looks like this:
> 
> ```
> proxy_pass http://outline
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header X-Forwarded-Proto $scheme;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header Connection keep-alive;
> proxy_set_header Host $host;
> proxy_http_version 1.1;
> 
> proxy_ssl_session_reuse on;
> proxy_ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
> proxy_ssl_ciphers   HIGH:!aNULL:!MD5;
> ```
> 
> You are logging in normally.
> 
> Thank you all for your help!

It works !!! Thanks, man.

**Comment by bagheriali2001** [comment]
> I removed the following parameters from nginx:
> 
> ```
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> ```
> 
> Now it looks like this:
> 
> ```
> proxy_pass http://outline
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header X-Forwarded-Proto $scheme;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header Connection keep-alive;
> proxy_set_header Host $host;
> proxy_http_version 1.1;
> 
> proxy_ssl_session_reuse on;
> proxy_ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
> proxy_ssl_ciphers   HIGH:!aNULL:!MD5;
> ```
> 
> You are logging in normally.
> 
> Thank you all for your help!

Hi,
I used this and it worked for me, but then when we saw the need for a google workspace account we switched to slack OAuth. But it was at this time this change made a problem for us. If you remove these two lines, it will prevent from websocket connection and you can not edit any document. This little change cost me 2 days. I just wanted to add this little note about this so if someone else tried this know this will happen.

**Comment by NamUKF** [comment]
> m

Does your live collaboration feature work ? Because I have issues with the websocket, when using apache as reversee proxy. By chance it would be cool, if you show the httpd configuration of your setup :)
