### ISSUE TITLE
Impossible to move data while upgrading to 0.54 with email auth

### ISSUE THREAD

**Issue by FGuemard** [outline/outline#2031]
After the upgrade and the db migration it was impossible to move the data. The below error occured.

All the users of my instance use the email auth.

```
# Commande line
docker-compose run --rm outline /bin/sh -c "node build/server/scripts/20210226232041-migrate-authentication.js"

# Error
/opt/outline/build/server/models/index.js:123
    return _User.default;
                 ^

TypeError: Cannot read property 'default' of undefined
    at Object.get [as User] (/opt/outline/build/server/models/index.js:123:18)
    at Object.<anonymous> (/opt/outline/build/server/policies/apiKey.js:12:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/outline/build/server/policies/index.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/outline/build/server/api/apiKeys.js:14:40)
```

**Comment by tommoor** [comment]
Is this running the official image from dockerhub?

**Comment by FGuemard** [comment]
No is running the project in dev mode by building the code pulled from github.
