### ISSUE TITLE
Redis Connection Error

### ISSUE THREAD

**Issue by MetaBliss** [outline/outline#2224]
First off, a great thanks for creating the GetOutline container. This looks like a phenomenal piece of software and I can't wait to spin it up and get it working to test it out. I hear all kinds of good things about bi directional linking in applications like Roam Research and Obsidian and was hoping Get Outline may be able to do what those other applications do. 

I ran into some issues getting Redis to work properly with my setup and was wondering if you could share any intel/insights into what could be wrong. I currently use a Synology NAS 920+ which runs Linux and has Docker installed. I manage all my containers using Portainer (a container management software for containers and to deploy stacks using a GUI). 

In the screenshot picture below, I show a graphic of what my Docker Compose file looks like. 

When I run the stack, I get the following error from the GetOutline container related to Redis:
`Redis error: connect ECONNREFUSED 127.0.0.1:6377....Redis error: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.. Shutting down now., Retrying redis connection: attempt 21. at Socket.emit (events.js:315:20), at Object.onceWrapper (events.js:422:26), at Socket.EventEmitter.emit (domain.js:467:12), at TCP.<anonymous> (net.js:673:12), error Command failed with exit code 1., at Socket.<anonymous> (/opt/outline/node_modules/ioredis/built/redis/event_handler.js:173:37)`

When I check the error logs of the Redis container, I'm seeing a different mesage in the Redis log below.
Would you know what the problem could be in my setup? 

`1:C 07 Jun 2021 21:56:21.640 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo, 1:C 07 Jun 2021 21:56:21.640 # Redis version=6.2.3, bits=64, commit=00000000, modified=0, pid=1, just started, 1:C 07 Jun 2021 21:56:21.640 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf, 1:M 07 Jun 2021 21:56:21.640 * monotonic clock: POSIX clock_gettime, 1:M 07 Jun 2021 21:56:21.641 * Running mode=standalone, port=6379., 1:M 07 Jun 2021 21:56:21.641 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128., 1:M 07 Jun 2021 21:56:21.641 # Server initialized, 1:M 07 Jun 2021 21:56:21.641 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect., 1:M 07 Jun 2021 21:56:21.641 * Loading RDB produced by version 6.2.3, 1:M 07 Jun 2021 21:56:21.641 * RDB age 3 seconds, 1:M 07 Jun 2021 21:56:21.641 * RDB memory usage when created 0.77 Mb, 1:M 07 Jun 2021 21:56:21.641 * DB loaded from disk: 0.000 seconds, 1:M 07 Jun 2021 21:56:21.641 * Ready to accept connections,`

![image](https://user-images.githubusercontent.com/84720384/121810598-87466980-cc2f-11eb-967f-c27f0dd2cd9d.png)

**Comment by tommoor** [comment]
The problem appears to be the port numbers differing – Make sure to define the correct port number in the compose file?

**Comment by MetaBliss** [comment]
Thanks @tommoor Tommoor, I just edited my docker compose to reuse an existing Redis instance I had already. 

So my Redis issue is gone, but I'm getting another issue. **I've provided below my error log from the GetOutline container.**

Would be VERY grateful if you can provide me any assistance if you know about the new issue I'm getting below.

`    
yarn run v1.22.5
$ node ./build/server/index.js --env=production-ssl-disabled

╔══════════════════════════════════════════════════════════════════════════════╗║                                                                              ║║                                                                              ║║   Is your team enjoying Outline? Consider supporting future development by   ║║   sponsoring the project:                                                    ║║                                                                              ║║   https://github.com/sponsors/outline                                        ║║                                                                              ║║                                                                              ║╚══════════════════════════════════════════════════════════════════════════════╝



2021-06-13T17:13:32.325Z services loaded backlinks service
2021-06-13T17:13:32.326Z services loaded debouncer service
2021-06-13T17:13:32.326Z services loaded importer service
2021-06-13T17:13:32.326Z services loaded notifications service
2021-06-13T17:13:32.326Z services loaded revisions service
2021-06-13T17:13:32.326Z services loaded slack service
2021-06-13T17:13:32.326Z services loaded websockets service
2021-06-13T17:13:32.583Z server loaded Email auth provider
2021-06-13T17:13:32.584Z server loaded Slack auth provider


(node:27) UnhandledPromiseRejectionWarning: SequelizeConnectionError: getaddrinfo EAI_AGAIN 0utl1ne
    at Client._connectionCallback (/opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)
   at Client._handleErrorWhileConnecting (/opt/outline/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/opt/outline/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:467:12)
    at Socket.reportStreamError (/opt/outline/node_modules/pg/lib/connection.js:53:12)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)


(Use `node --trace-warnings ...` to show where the warning was created)

(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:27) UnhandledPromiseRejectionWarning: SequelizeConnectionError: getaddrinfo EAI_AGAIN 0utl1ne

    at Client._connectionCallback (/opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:184:24)


    at Client._handleErrorWhileConnecting (/opt/outline/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/opt/outline/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:467:12)
    at Socket.reportStreamError (/opt/outline/node_modules/pg/lib/connection.js:53:12)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`
