### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by matbrgz** [outline/outline#2445]
**To Reproduce**
1. Go to Template page (in the sidebar menu)
1. Scroll down

**Expected behavior**
See all templates

**Error Trace**
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
  at Ug(./node_modules/react-dom/cjs/react-dom.production.min.js:275:129)
  at p(./node_modules/react-dom/cjs/react-dom.production.min.js:142:382)
  at ca(./node_modules/react-dom/cjs/react-dom.production.min.js:145:142)
  at Yg(./node_modules/react-dom/cjs/react-dom.production.min.js:149:236)
  at R(./node_modules/react-dom/cjs/react-dom.production.min.js:173:103)
  at Rj(./node_modules/react-dom/cjs/react-dom.production.min.js:265:156)
  at Qj(./node_modules/react-dom/cjs/react-dom.production.min.js:246:265)
  at Kj(./node_modules/react-dom/cjs/react-dom.production.min.js:246:194)
  at yj(./node_modules/react-dom/cjs/react-dom.production.min.js:239:172)
  at b(./node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
  at If(./node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at cg(./node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at fg(./node_modules/react-dom/cjs/react-dom.production.min.js:123:61)
  at gg(./node_modules/react-dom/cjs/react-dom.production.min.js:122:496)
  at Ig(./node_modules/react-dom/cjs/react-dom.production.min.js:230:156)
  at zh(./node_modules/react-dom/cjs/react-dom.production.min.js:163:512)
  at apply(./app/components/Header.js:21:20)
  at invokeFunc(./node_modules/lodash/debounce.js:95:19)
  at leadingEdge(./node_modules/lodash/debounce.js:105:22)
  at debounced(./node_modules/lodash/debounce.js:172:16)
```

![image](https://user-images.githubusercontent.com/23284276/129237084-85012756-c5b4-4325-9766-7d1cc2c11517.png)

**Outline (please complete the following information):**
- Install: Self hosted 0.55.0

**Comment by tommoor** [comment]
Do you have more than 15 templates?

**Comment by matbrgz** [comment]
> Do you have more than 15 templates?

Yes. More then 100.
