### ISSUE TITLE
Cannot POST to /api/auth.config with v0.60.0

### ISSUE THREAD

**Issue by vsile** [outline/outline#2758]
![изображение](https://user-images.githubusercontent.com/9244347/141331341-c93e86ac-25cd-4953-b329-dc07e882e2de.png)
I use OIDC parameters for authentication and launch Outline via Docker.
In new version 0.60.0 Outline returns 500 Internal Server Error on POST request to /api/auth.config
In v0.59.0 OIDC authentication works fine.

**Comment by tommoor** [comment]
Please provide the error in your server logs

**Comment by vsile** [comment]
```


2021-11-12 09:54:04 | {"label":"http","level":"info","message":"  <-- POST /api/auth.config"}
-- | --
2021-11-12 09:54:04 | SequelizeDatabaseError: column team.collaborativeEditing does not exist
2021-11-12 09:54:04 | at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:392:16)
2021-11-12 09:54:04 | at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
2021-11-12 09:54:04 | at runMicrotasks (<anonymous>)
2021-11-12 09:54:04 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-11-12 09:54:04 | at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
2021-11-12 09:54:04 | at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
2021-11-12 09:54:04 | at async Function.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1752:21)
2021-11-12 09:54:04 | at async /opt/outline/build/server/routes/api/auth.js:52:19
2021-11-12 09:54:04 | at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
2021-11-12 09:54:04 | at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:17:7)
2021-11-12 09:54:04 | at async /opt/outline/node_modules/koa-mount/index.js:58:5
2021-11-12 09:54:04 | at async /opt/outline/node_modules/koa-mount/index.js:52:26
2021-11-12 09:54:04 | at async logger (/opt/outline/node_modules/koa-logger/index.js:67:7)
2021-11-12 09:54:04 | DatabaseError [SequelizeDatabaseError]: column team.collaborativeEditing does not exist
2021-11-12 09:54:04 | at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:392:16)
2021-11-12 09:54:04 | at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
2021-11-12 09:54:04 | at runMicrotasks (<anonymous>)
2021-11-12 09:54:04 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-11-12 09:54:04 | at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
2021-11-12 09:54:04 | at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
2021-11-12 09:54:04 | at async Function.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1752:21)
2021-11-12 09:54:04 | at async /opt/outline/build/server/routes/api/auth.js:52:19
2021-11-12 09:54:04 | at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
2021-11-12 09:54:04 | at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:17:7)
2021-11-12 09:54:04 | at async /opt/outline/node_modules/koa-mount/index.js:58:5
2021-11-12 09:54:04 | at async /opt/outline/node_modules/koa-mount/index.js:52:26
2021-11-12 09:54:04 | at async logger (/opt/outline/node_modules/koa-logger/index.js:67:7) {
2021-11-12 09:54:04 | parent: error: column team.collaborativeEditing does not exist
2021-11-12 09:54:04 | at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
2021-11-12 09:54:04 | at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
2021-11-12 09:54:04 | at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
2021-11-12 09:54:04 | at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
2021-11-12 09:54:04 | at Socket.emit (events.js:400:28)
2021-11-12 09:54:04 | at Socket.emit (domain.js:475:12)
2021-11-12 09:54:04 | at addChunk (internal/streams/readable.js:293:12)
2021-11-12 09:54:04 | at readableAddChunk (internal/streams/readable.js:267:9)
2021-11-12 09:54:04 | at Socket.Readable.push (internal/streams/readable.js:206:10)
2021-11-12 09:54:04 | at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
2021-11-12 09:54:04 | length: 124,
2021-11-12 09:54:04 | severity: 'ERROR',
2021-11-12 09:54:04 | code: '42703',
2021-11-12 09:54:04 | detail: undefined,
2021-11-12 09:54:04 | hint: undefined,
2021-11-12 09:54:04 | position: '223',
2021-11-12 09:54:04 | internalPosition: undefined,
2021-11-12 09:54:04 | internalQuery: undefined,
2021-11-12 09:54:04 | where: undefined,
2021-11-12 09:54:04 | schema: undefined,
2021-11-12 09:54:04 | table: undefined,
2021-11-12 09:54:04 | column: undefined,
2021-11-12 09:54:04 | dataType: undefined,
2021-11-12 09:54:04 | constraint: undefined,
2021-11-12 09:54:04 | file: 'parse_relation.c',
2021-11-12 09:54:04 | line: '3317',
2021-11-12 09:54:04 | routine: 'errorMissingColumn',
2021-11-12 09:54:04 | sql: 'SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."signupQueryParams", "team"."guestSignin", "team"."documentEmbeds", "team"."collaborativeEditing", "team"."defaultUserRole", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL);',
2021-11-12 09:54:04 | parameters: undefined
2021-11-12 09:54:04 | },
2021-11-12 09:54:04 | original: error: column team.collaborativeEditing does not exist
2021-11-12 09:54:04 | at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
2021-11-12 09:54:04 | at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
2021-11-12 09:54:04 | at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
2021-11-12 09:54:04 | at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
2021-11-12 09:54:04 | at Socket.emit (events.js:400:28)
2021-11-12 09:54:04 | at Socket.emit (domain.js:475:12)
2021-11-12 09:54:04 | at addChunk (internal/streams/readable.js:293:12)
2021-11-12 09:54:04 | at readableAddChunk (internal/streams/readable.js:267:9)
2021-11-12 09:54:04 | at Socket.Readable.push (internal/streams/readable.js:206:10)
2021-11-12 09:54:04 | at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
2021-11-12 09:54:04 | length: 124,
2021-11-12 09:54:04 | severity: 'ERROR',
2021-11-12 09:54:04 | code: '42703',
2021-11-12 09:54:04 | detail: undefined,
2021-11-12 09:54:04 | hint: undefined,
2021-11-12 09:54:04 | position: '223',
2021-11-12 09:54:04 | internalPosition: undefined,
2021-11-12 09:54:04 | internalQuery: undefined,
2021-11-12 09:54:04 | where: undefined,
2021-11-12 09:54:04 | schema: undefined,
2021-11-12 09:54:04 | table: undefined,
2021-11-12 09:54:04 | column: undefined,
2021-11-12 09:54:04 | dataType: undefined,
2021-11-12 09:54:04 | constraint: undefined,
2021-11-12 09:54:04 | file: 'parse_relation.c',
2021-11-12 09:54:04 | line: '3317',
2021-11-12 09:54:04 | routine: 'errorMissingColumn',
2021-11-12 09:54:04 | sql: 'SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."signupQueryParams", "team"."guestSignin", "team"."documentEmbeds", "team"."collaborativeEditing", "team"."defaultUserRole", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL);',
2021-11-12 09:54:04 | parameters: undefined
2021-11-12 09:54:04 | },
2021-11-12 09:54:04 | sql: 'SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."signupQueryParams", "team"."guestSignin", "team"."documentEmbeds", "team"."collaborativeEditing", "team"."defaultUserRole", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL);',
2021-11-12 09:54:04 | parameters: undefined
2021-11-12 09:54:04 | }
2021-11-12 09:54:04 | {"label":"http","level":"info","message":"  --> POST /api/auth.config 500 26ms 78b"}


```

**Comment by tommoor** [comment]
You must run the database migrations as described in [release notes](https://github.com/outline/outline/releases/tag/v0.60.0).

Hopefully this will be automatic soon.
