### ISSUE TITLE
OIDC: 'No email field in profile parameter' error not surfaced to the user

### ISSUE THREAD

**Issue by almereyda** [outline/outline#2781]
**To Reproduce**
1. Create an Outline Team through logging in as first user via SSO
2. Ask a second user to login to the team via SSO
3. See it being rejected with an error message, and being redirected to the login screen:

```
{"label":"http","level":"info","message":"  <-- GET /auth/oidc"}
{"label":"http","level":"info","message":"  --> POST /auth/oidc 302 5ms 2b"}
{"label":"http","level":"info","message":"  <-- GET /auth/oidc.callback?code=15499b8eccd705c5e4ac50164526fb39c35d41c1fc222cf072683b549664d2de&state=cw8tblne"}
{"error":"An email field was not returned in the profile parameter, but is required.","stack":"UnauthorizedError: An email field was not returned in the profile parameter, but is required.\n    at new Aut
henticationError (/opt/outline/build/server/errors.js:32:34)\n    at OAuth2Strategy._verify (/opt/outline/build/server/routes/auth/providers/oidc.js:79:15)\n    at /opt/outline/node_modules/passport-oauth
2/lib/strategy.js:198:24\n    at OAuth2Strategy._passportOauth.Strategy.userProfile (/opt/outline/build/server/routes/auth/providers/oidc.js:52:12)\n    at runMicrotasks (<anonymous>)\n    at processTicks
AndRejections (internal/process/task_queues.js:95:5)","level":"error","message":"Error during authentication"}
{"label":"http","level":"info","message":"  --> POST /auth/oidc.callback?code=15499b8eccd705c5e4ac50164526fb39c35d41c1fc222cf072683b549664d2de&state=cw8tblne 302 147ms 149b"}
{"label":"http","level":"info","message":"  <-- GET /?notice=authentication-required"}
{"label":"http","level":"info","message":"  --> GET /?notice=authentication-required 200 5ms 1kb"}
```

**Expected behavior**

The error message in the frontend is more verbose and forwards the reason already known to the backend, for why this login cycle did not finish successfully.

---

This seems to be a special case of #2678, when no domain can be inferred.

**Outline (please complete the following information):**
- Install: self hosted
- Version: #2568 merged with 0.60.1

**Comment by almereyda** [comment]
This error was also reported in https://github.com/outline/outline/discussions/3299#discussioncomment-2461818
