### ISSUE TITLE
Validation error: Validation isIP on lastActiveIp failed

### ISSUE THREAD

**Issue by dkkb** [outline/outline#2989]
**To Reproduce**

**Expected behavior**

```
/home/ubuntu/outline/node_modules/sequelize/lib/instance-validator.js:78
      throw new sequelizeError.ValidationError(null, this.errors);
            ^

ValidationError [SequelizeValidationError]: Validation error: Validation isIP on lastActiveIp failed
    at InstanceValidator._validate (/home/ubuntu/outline/node_modules/sequelize/lib/instance-validator.js:78:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InstanceValidator.validate (/home/ubuntu/outline/node_modules/sequelize/lib/instance-validator.js:93:12)
    at async Object.save (/home/ubuntu/outline/node_modules/sequelize/lib/model.js:3910:7) {
  errors: [
    ValidationErrorItem {
      message: 'Validation isIP on lastActiveIp failed',
      type: 'Validation error',
      path: 'lastActiveIp',
      value: 'x.x.x.x:32100',
```

commit: c8a67c374f972cf7af26b9f5e012eebde645c93f

**Comment by tommoor** [comment]
Hi @dkkb – that format is _not_ a valid IP – perhaps your reverse proxy is to blame?
