### ISSUE TITLE
Unable to upload images to document

### ISSUE THREAD

**Issue by leetosc** [outline/outline#3062]
When trying to upload an image to a document, the upload fails, saying "Sorry an error occurred uploading the image". 

![image](https://user-images.githubusercontent.com/13279967/152628306-590ad6a1-f2d8-45c8-a8da-577cb4a6afb2.png)

`attachments.create` API returns 400 with this error: 
```json
{
  "ok": false,
  "error": "",
  "message": "Validation isIn on acl failed (acl)"
}
```

```
"BadRequestError: Validation isIn on acl failed (acl)
    at _callee$ (https://outline.nguyen.casa/static/main.21f88946988016b83723.js:2:1404335)
    at u (chrome-extension://hejbmebodbijjdhflfknehhcgaklhano/window/testing-library.js:1:161327)
    at Generator._invoke (chrome-extension://hejbmebodbijjdhflfknehhcgaklhano/window/testing-library.js:1:161080)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://hejbmebodbijjdhflfknehhcgaklhano/window/testing-library.js:1:161684)
    at asyncGeneratorStep (https://outline.nguyen.casa/static/main.21f88946988016b83723.js:2:1401492)
    at _next (https://outline.nguyen.casa/static/main.21f88946988016b83723.js:2:1402174)"
```

---

Self hosted via docker-compose, with minio for storage.  
Interestingly, uploading a logo in Settings -> Details works, and the `attachments.create` call succeeds.
<details>
<summary>Successful response</summary>

```json
{
  "maxUploadSize": "26214400",
  "uploadUrl": "https://data.outline.nguyen.casa/bucket",
  "form": {
    "Cache-Control": "max-age=31557600",
    "Content-Type": "image/jpeg",
    "key": "public/70100b9d-5d77-414a-aab0-7e2446a7637c/20194d1e-ed3f-4e8f-8e19-374352075a01/dogs.jpeg",
    "acl": "public-read",
    "bucket": "bucket",
    "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
    "X-Amz-Credential": "cd0b724c5d18ec33/20220205/xx-xxxx-x/s3/aws4_request",
    "X-Amz-Date": "20220205T042919Z",
    "Policy": "eyJleHBpcmF0aW9uIjoiMjAyMi0wMi0wNVQwNToyOToxOVoiLCJjb25kaXRpb25zIjpbWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwyNjIxNDQwMF0sWyJzdGFydHMtd2l0aCIsIiRDb250ZW50LVR5cGUiLCJpbWFnZS9qcGVnIl0sWyJzdGFydHMtd2l0aCIsIiRDYWNoZS1Db250cm9sIiwiIl0seyJrZXkiOiJwdWJsaWMvNzAxMDBiOWQtNWQ3Ny00MTRhLWFhYjAtN2UyNDQ2YTc2MzdjLzIwMTk0ZDFlLWVkM2YtNGU4Zi04ZTE5LTM3NDM1MjA3NWEwMS9kb2dzLmpwZWcifSx7ImFjbCI6InB1YmxpYy1yZWFkIn0seyJidWNrZXQiOiJidWNrZXQifSx7IlgtQW16LUFsZ29yaXRobSI6IkFXUzQtSE1BQy1TSEEyNTYifSx7IlgtQW16LUNyZWRlbnRpYWwiOiJjZDBiNzI0YzVkMThlYzMzLzIwMjIwMjA1L3h4LXh4eHgteC9zMy9hd3M0X3JlcXVlc3QifSx7IlgtQW16LURhdGUiOiIyMDIyMDIwNVQwNDI5MTlaIn1dfQ==",
    "X-Amz-Signature": "ae4c37c8dba780e535f024d5f00869f5829e0a0bd1a3655ba1d836ea8bd86f64"
  },
  "attachment": {
    "contentType": "image/jpeg",
    "name": "dogs.jpeg",
    "id": "2ae5de85-5151-43ba-bcbe-474ae0ba7703",
    "url": "/api/attachments.redirect?id=2ae5de85-5151-43ba-bcbe-474ae0ba7703",
    "size": 63320
  }
}
```
</details>

---

Looks similar to this issue: https://github.com/outline/outline/issues/2662

---

**To Reproduce**
1. Go to a document
2. Try to insert an image, or paste an image from the clipboard (like a screenshot)
4. Picture is not uploaded, `attachments.create` API returns 400

**Expected behavior**
Image should be uploaded and inserted into document

**Screenshots**
See above

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.61.1
**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.1
 - Browser: All
 - Version 12.1

**Comment by leetosc** [comment]
I figured out the issue, I had the `AWS_S3_ACL` env var wrong.   I had it set to `public`, when it should have been `public-read`. 

It works now, using this config: 
```
AWS_S3_UPLOAD_BUCKET_NAME=bucket
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=public-read
```
