### ISSUE TITLE
Failed to upload images to third-party S3 service like Alibaba Cloud OSS

### ISSUE THREAD

**Issue by KooriMoe** [outline/outline#3155]
I chose to use Alibaba Cloud OSS as S3 storage.
It can normally upload personal avatars and team pictures to Alibaba Cloud OSS but cannot upload files in documents.
In the browser, Outline will automatically merge the URL into the AWS S3 service link with ```amazonaws.com```, for example, ```inotea.s3.oss-cn-beijing.amazonaws.com```, but my S3 is ```inotea.s3.oss-cn-beijing.aliyuncs.com```
Is there a way to fix it?

### .env
```
AWS_ACCESS_KEY_ID=xxxxxxxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxx
AWS_REGION=oss-cn-beijing
AWS_S3_UPLOAD_BUCKET_URL=https://inotea.oss-cn-beijing.aliyuncs.com
AWS_S3_UPLOAD_BUCKET_NAME=inotea
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=false
AWS_S3_ACL=public
```

### Logs from Docker Container
```
yarn run v1.22.15
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"Starting collaboration service"}
{"label":"lifecycle","level":"info","message":"Starting websockets service"}
{"label":"lifecycle","level":"info","message":"Starting worker service"}
{"label":"lifecycle","level":"info","message":"Starting web service"}
{"level":"warn","message":"Enforced https was disabled with FORCE_HTTPS env variable"}
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:3000"}
{"error":"Inaccessible host: `inotea.s3.oss-cn-beijing.amazonaws.com'. This service may not be available in the `oss-cn-beijing' region.","stack":"UnknownEndpoint: Inaccessible host: `inotea.s3.oss-cn-beijing.amazonaws.com'. This service may not be available in the `oss-cn-beijing' region.\n    at Request.ENOTFOUND_ERROR (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:507:46)\n    at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:688:14)\n    at ClientRequest.error (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:339:22)\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/http/node.js:96:19)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","level":"error","message":"Error uploading to S3 from URL"}
{"error":"Inaccessible host: `inotea.s3.oss-cn-beijing.amazonaws.com'. This service may not be available in the `oss-cn-beijing' region.","stack":"UnknownEndpoint: Inaccessible host: `inotea.s3.oss-cn-beijing.amazonaws.com'. This service may not be available in the `oss-cn-beijing' region.\n    at Request.ENOTFOUND_ERROR (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:507:46)\n    at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:688:14)\n    at ClientRequest.error (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:339:22)\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/http/node.js:96:19)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","level":"error","message":"Error uploading to S3 from URL"}
```

**Comment by KooriMoe** [comment]
Already moved to Discussions.
