### ISSUE TITLE
Error: Cannot find module 'koa-webpack-dev-middleware'

### ISSUE THREAD

**Issue by 1itt1eB0y** [outline/outline#3383]
Using docker image `outlinewiki/outline:latest` to create container, pull and run, there will be an `error`
```
(node:40) UnhandledPromiseRejectionWarning: Error: Cannot find module 'koa-webpack-dev-middleware',
Require stack:,
- /opt/outline/build/server/services/web.js,
- /opt/outline/build/server/services/index.js,
- /opt/outline/build/server/index.js,
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15),
    at Function.Module._load (internal/modules/cjs/loader.js:746:27),
    at Module.require (internal/modules/cjs/loader.js:974:19),
    at require (internal/modules/cjs/helpers.js:93:18),
    at init (/opt/outline/build/server/services/web.js:66:27),
    at start (/opt/outline/build/server/index.js:101:11),
    at processTicksAndRejections (internal/process/task_queues.js:95:5),
    at async throng (/opt/outline/node_modules/throng/lib/throng.js:24:12),
(Use `node --trace-warnings ...` to show where the warning was created),
```

**Comment by tommoor** [comment]
Somehow running with NODE_ENV=development?
