### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by EinarArnason** [outline/outline#3480]
Cannot start server on fresh install.

**To Reproduce**
1. git clone
2. yarn install
3. Fill out .env
4. yarn sequelize db:create
5. yarn start

**Expected behavior**
Server starts

**Screenshots**
```bash
/opt/outline/node_modules/toidentifier/index.js:24
    .split(' ')
     ^
Cannot read properties of undefined (reading 'split')
    at toIdentifier (/opt/outline/node_modules/toidentifier/index.js:24:6)
    at forEachCode (/opt/outline/node_modules/raw-body/node_modules/http-errors/index.js:245:16)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (/opt/outline/node_modules/raw-body/node_modules/http-errors/index.js:243:9)
    at Object.<anonymous> (/opt/outline/node_modules/raw-body/node_modules/http-errors/index.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/outline/node_modules/raw-body/index.js:16:19)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.63.0

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by tommoor** [comment]
Cannot reproduce, most likely there is something in `.env` missing… There's nothing actually from Outline's code in that stacktrace, so that's confusing.

**Comment by EinarArnason** [comment]
It's an error in the raw-body package. https://github.com/stream-utils/raw-body/issues/77
I'll open a PR there for a fix.

**Comment by tommoor** [comment]
It sounds like the wrong version of the dependency is installed then, I would encourage you to use the official releases in Docker rather than building `main` which can avoid issues like this. Otherwise ensuring the version that's in the lockfile gets installed should do the trick:

`yarn install --production=true --frozen-lockfile`
