### ISSUE TITLE
API documents.delete doesn't work when bulk delete

### ISSUE THREAD

**Issue by max-mykhailenko** [outline/outline#3505]
I'm trying to send 5+ simultaneously delete requests I have got next logs
```
{"label":"http","level":"info","message":"  --> POST /api/documents.delete 500 30s 78b"}
{"name":"documents.delete","modelId":null,"label":"worker","level":"info","message":"BacklinksProcessor running documents.delete"}

  SequelizeConnectionAcquireTimeoutError: Operation timeout
      at ConnectionManager.getConnection (/opt/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:288:48)
      at async /opt/outline/node_modules/sequelize/lib/sequelize.js:613:26
      at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
      at async Function.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1752:21)
      at async loopChildren (/opt/outline/build/server/models/Collection.js:236:32)
      at async Object.deleteDocument (/opt/outline/build/server/models/Collection.js:247:7)
      at async /opt/outline/build/server/models/Document.js:427:11
      at async /opt/outline/node_modules/sequelize/lib/sequelize.js:1090:24
      at async /opt/outline/build/server/routes/api/documents.js:1225:5
      at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
      at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:15:7)
      at async /opt/outline/node_modules/koa-mount/index.js:58:5
      at async /opt/outline/node_modules/koa-mount/index.js:52:26
      at async logger (/opt/outline/node_modules/koa-logger/index.js:67:7)

ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
    at ConnectionManager.getConnection (/opt/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:288:48)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:613:26
    at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
    at async Function.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1752:21)
    at async loopChildren (/opt/outline/build/server/models/Collection.js:236:32)
    at async Object.deleteDocument (/opt/outline/build/server/models/Collection.js:247:7)
    at async /opt/outline/build/server/models/Document.js:427:11
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:1090:24
    at async /opt/outline/build/server/routes/api/documents.js:1225:5
    at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
    at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:15:7)
    at async /opt/outline/node_modules/koa-mount/index.js:58:5
    at async /opt/outline/node_modules/koa-mount/index.js:52:26
    at async logger (/opt/outline/node_modules/koa-logger/index.js:67:7) {
  parent: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7),
  original: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
}

```

**To Reproduce**
1. Call https://www.getoutline.com/developers#tag/Documents/paths/~1documents.delete/post
2. Check logs

**Expected behavior**
Documents should be deleted

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.63.0

**Comment by tommoor** [comment]
> I'm trying to send 5+ simultaneously delete requests 

Could you say more? What is the behavior that reproduces? Is it find if the delete requests run in serial?

**Comment by max-mykhailenko** [comment]
Pseudo code looks like
```js
function deleteDocument(id) {
  try {
    const response = await fetch(
      "https://.../api/documents.delete",
      {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          Authorization: `Bearer ${OUTLINE_TOKEN}`,
        },
        body: JSON.stringify({ id }),
      }
    );

    const body = await response.json();
    const document = body.data;
    return { id, response: document };
  } catch (e) {
    console.error(e);
    throw e;
  }
}

Promise.all(documentsIds.map((id) => {
  return deleteDocument(id),
}))


```

**Comment by tommoor** [comment]
I suspect you just overloaded your server here, there's nothing in the code that would restrict the number of delete api requests

**Comment by max-mykhailenko** [comment]
Ok, thank you, will recheck memory during this operation
