### ISSUE TITLE
0.64.1 fails to start with JSON parse error when some default value left empty in docker.env 

### ISSUE THREAD

**Issue by bmm-alc** [outline/outline#3581]
**To Reproduce**
1. Have a working version 0.63
2. upgrade to docker image 0.64.1 
3. Launch the Db migration command
4. do a `docker-compose up -d`

Once I removed all the values I don't use in file `docker.env` the error disappeared
here the list of variable I removed
```
AWS_S3_ACCELERATE_URL=
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
AZURE_RESOURCE_APP_ID=
CDN_URL=
COLLABORATION_URL=
DATABASE_CONNECTION_POOL_MAX=
DATABASE_CONNECTION_POOL_MIN=
GOOGLE_ANALYTICS_ID=
OIDC_AUTH_URI=
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_TOKEN_URI=
OIDC_USERINFO_URI=
SENTRY_DSN=
SLACK_APP_ID=
SLACK_KEY=
SLACK_MESSAGE_ACTIONS=
SLACK_SECRET=
SLACK_VERIFICATION_TOKEN=
SMTP_PASSWORD=
SMTP_USERNAME=
```

**Expected behavior**
not to crash

**Screenshots**
```
$ node ./build/server/index.js
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Environment.toBoolean (/opt/outline/build/server/env.js:207:19)
    at Environment.initializer (/opt/outline/build/server/env.js:453:17)
    at _initializerDefineProperty (/opt/outline/build/server/env.js:20:305)
    at new Environment (/opt/outline/build/server/env.js:149:5)
    at Object.<anonymous> (/opt/outline/build/server/env.js:520:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 0.64.1

The redacted version of `docker.env` before I trimmed it.
[docker.env.txt](https://github.com/outline/outline/files/8760042/docker.env.txt)

**Comment by bmm-alc** [comment]
line 149 of /opt/outline/build/server/env.js is 
```
_initializerDefineProperty(this, "SLACK_MESSAGE_ACTIONS", _descriptor35, this);
```
Once I  commented this line, the server fails "nicely" with proper error message
``` 
root@infra-doc:~/docker-outline# docker logs docker-outline_outline_1 -f
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- CDN_URL must be an URL address"}
{"level":"warn","message":"- COLLABORATION_URL must be an URL address"}
{"level":"warn","message":"- SENTRY_DSN must be an URL address"}
{"level":"warn","message":"- GOOGLE_ANALYTICS_ID must contain a UA- string"}
{"level":"warn","message":"- OIDC_AUTH_URI must be an URL address"}
{"level":"warn","message":"- OIDC_TOKEN_URI must be an URL address"}
{"level":"warn","message":"- OIDC_USERINFO_URI must be an URL address"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by bmm-alc** [comment]
Confirming that 0.64.2 fixed the issue
