### ISSUE TITLE
Unknown constraint error 

### ISSUE THREAD

**Issue by bxdavies** [outline/outline#3651]
Unknown constraint error is received in the log file when I try to create a collection. Database migration completed successfully. 

**To Reproduce**
1. Click 'New collection'
2. Enter any name for the collection 
3. Click 'create'
4. See error 500: Internal Server Error in the UI and 

**Expected behavior**
To create a collection. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30366010/172952186-93cd9df4-bc2d-4e5a-8bdd-54f2679355da.png)

**Log**
```
{"label":"http","level":"info","message":"  <-- POST /api/collections.create"}

  SequelizeUnknownConstraintError: Unknown constraint error
      at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:382:17)
      at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
      at async PostgresQueryInterface.insert (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:749:21)
      at async Object.save (/opt/outline/node_modules/sequelize/lib/model.js:3987:35)
      at async Function.create (/opt/outline/node_modules/sequelize/lib/model.js:2217:12)
      at async /opt/outline/build/server/routes/api/collections.js:86:22
      at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
      at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:15:7)
      at async /opt/outline/node_modules/koa-mount/index.js:58:5
      at async /opt/outline/node_modules/koa-mount/index.js:52:26
      at async logger (/opt/outline/node_modules/koa-logger/index.js:67:7)

UnknownConstraintError [SequelizeUnknownConstraintError]: Unknown constraint error
    at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:382:17)
    at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.insert (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:749:21)
    at async Object.save (/opt/outline/node_modules/sequelize/lib/model.js:3987:35)
    at async Function.create (/opt/outline/node_modules/sequelize/lib/model.js:2217:12)
    at async /opt/outline/build/server/routes/api/collections.js:86:22
    at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
    at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:15:7)
    at async /opt/outline/node_modules/koa-mount/index.js:58:5
    at async /opt/outline/node_modules/koa-mount/index.js:52:26
    at async logger (/opt/outline/node_modules/koa-logger/index.js:67:7) {
  parent: error: text search configuration "english" does not exist
      at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 332,
    severity: 'ERROR',
    code: '42704',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: '30',
    internalQuery: "SELECT setweight(to_tsvector('english', coalesce(new.name, '')),'A') ||\n" +
      "    setweight(to_tsvector('english', coalesce(new.description, '')), 'C')",
    where: 'PL/pgSQL function atlases_search_trigger() line 3 at assignment',
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
{"label":"http","level":"info","message":"  --> POST /api/collections.create 500 60ms 78b"}
    constraint: undefined,
    file: 'namespace.c',
    line: '2716',
    routine: 'get_ts_config_oid',
    sql: 'INSERT INTO "collections" ("id","urlId","name","icon","color","index","permission","maintainerApprovalRequired","sharing","sort","createdById","teamId","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING "id","urlId","name","description","icon","color","index","permission","maintainerApprovalRequired","documentStructure","sharing","sort","createdById","teamId","createdAt","updatedAt","deletedAt";',
    parameters: [
      '7c3b13a6-d200-4290-a426-1b6d2702cc9a',
      '0lnvLfqDIn',
      'test',
      'beaker',
      '#4E5C6E',
      'P',
      'read_write',
      false,
      false,
      '{"field":"index","direction":"asc"}',
      '0dca9413-2362-4736-a911-a77581dab764',
      'f5b94487-8f70-4f76-9306-fbf29bde8408',
      '2022-06-09 21:49:42.712 +00:00',
      '2022-06-09 21:49:42.712 +00:00'
    ]
  },
  original: error: text search configuration "english" does not exist
      at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 332,
    severity: 'ERROR',
    code: '42704',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: '30',
    internalQuery: "SELECT setweight(to_tsvector('english', coalesce(new.name, '')),'A') ||\n" +
      "    setweight(to_tsvector('english', coalesce(new.description, '')), 'C')",
    where: 'PL/pgSQL function atlases_search_trigger() line 3 at assignment',
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'namespace.c',
    line: '2716',
    routine: 'get_ts_config_oid',
    sql: 'INSERT INTO "collections" ("id","urlId","name","icon","color","index","permission","maintainerApprovalRequired","sharing","sort","createdById","teamId","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING "id","urlId","name","description","icon","color","index","permission","maintainerApprovalRequired","documentStructure","sharing","sort","createdById","teamId","createdAt","updatedAt","deletedAt";',
    parameters: [
      '7c3b13a6-d200-4290-a426-1b6d2702cc9a',
      '0lnvLfqDIn',
      'test',
      'beaker',
      '#4E5C6E',
      'P',
      'read_write',
      false,
      false,
      '{"field":"index","direction":"asc"}',
      '0dca9413-2362-4736-a911-a77581dab764',
      'f5b94487-8f70-4f76-9306-fbf29bde8408',
      '2022-06-09 21:49:42.712 +00:00',
      '2022-06-09 21:49:42.712 +00:00'
    ]
  },
  sql: 'INSERT INTO "collections" ("id","urlId","name","icon","color","index","permission","maintainerApprovalRequired","sharing","sort","createdById","teamId","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING "id","urlId","name","description","icon","color","index","permission","maintainerApprovalRequired","documentStructure","sharing","sort","createdById","teamId","createdAt","updatedAt","deletedAt";',
  parameters: [
    '7c3b13a6-d200-4290-a426-1b6d2702cc9a',
    '0lnvLfqDIn',
    'test',
    'beaker',
    '#4E5C6E',
    'P',
    'read_write',
    false,
    false,
    '{"field":"index","direction":"asc"}',
    '0dca9413-2362-4736-a911-a77581dab764',
    'f5b94487-8f70-4f76-9306-fbf29bde8408',
    '2022-06-09 21:49:42.712 +00:00',
    '2022-06-09 21:49:42.712 +00:00'
  ],
  constraint: undefined,
  fields: undefined,
  table: undefined
}
```

**Outline:**
- Install: self hosted
- Version: v0.64.3
- 
**Desktop:**
 - OS: Windows 11
 - Browser: Firefox
 - Version 101.0

**Database ENV**
```
DATABASE_URL=postgres://outline:passwordhere@172.17.0.1:5432/outline
PGSSLMODE=disable
```

**Comment by bxdavies** [comment]
Link to dump of outline database schema: [https://pastebin.com/dMmkJjnD](https://pastebin.com/dMmkJjnD).

**Comment by tommoor** [comment]
The error is this:

`text search configuration "english" does not exist`

Not sure why this would be the case, it should be there on a default postgres install – where is your Postgres instance coming from? Moving to discussions as this is not a bug in the Outline codebase.
