### ISSUE TITLE
Authentication failed on fresh Outline Instance

### ISSUE THREAD

**Issue by pinarruiz** [outline/outline#3874]
Cannot login on fresh install of outline using the google authentication provider.

**To Reproduce**
1. Create fresh PostgreSQL database (AWS).
2. Create fresh Redis (AWS).
3. Create a new instance with Google oauth.
4. Try to login.

**Expected behavior**
The login goes well.

**Error Logs**
```
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"Starting collaboration service"}
{"label":"lifecycle","level":"info","message":"Starting websockets service"}
{"label":"lifecycle","level":"info","message":"Starting worker service"}
{"label":"lifecycle","level":"info","message":"Starting web service"}
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:8080"}
{"name":"teams.create","modelId":null,"attempt":0,"label":"worker","level":"info","message":"Processing teams.create"}
{"name":"teams.create","modelId":null,"label":"worker","level":"info","message":"AvatarProcessor running teams.create"}
{"error":"Invalid key length","stack":"RangeError: Invalid key length\n    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)\n    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)\n    at new Cipheriv (node:internal/crypto/cipher:243:3)\n
  at Object.createCipheriv (node:crypto:138:10)\n    at Object.set (/opt/outline/node_modules/sequelize-encrypted/index.js:48:33)\n    at setEncryptedColumn (/opt/outline/build/server/models/decorators/Encrypted.js:59:55)\n    at Object.set accessToken (/opt/outline/build/
server/models/UserAuthentication.js:73:39)\n    at Object.set (/opt/outline/node_modules/sequelize/lib/model.js:2204:32)\n    at Object.set (/opt/outline/node_modules/sequelize/lib/model.js:2189:18)\n    at Object._initValues (/opt/outline/node_modules/sequelize/lib/model.
js:156:10)\n    at new Model (/opt/outline/node_modules/sequelize/lib/model.js:116:10)\n    at new Model (/opt/outline/node_modules/sequelize-typescript/dist/model/model/model.js:14:9)\n    at new BaseModel (/opt/outline/build/server/models/base/BaseModel.js:10:1)\n    at
new IdModel (/opt/outline/build/server/models/base/IdModel.js:26:5)\n    at new UserAuthentication (/opt/outline/build/server/models/UserAuthentication.js:49:5)\n    at new user_authentication (/opt/outline/build/server/models/decorators/Fix.js:21:7)\n    at Function.build
 (/opt/outline/node_modules/sequelize/lib/model.js:1326:12)\n    at Function.Model.<computed> (/opt/outline/node_modules/sequelize-typescript/dist/model/model/model.js:128:28)\n    at Function.Model.<computed> [as build] (/opt/outline/node_modules/sequelize-typescript/dist
/model/model/model.js:138:28)\n    at /opt/outline/node_modules/sequelize/lib/model.js:1340:43\n    at Array.map (<anonymous>)\n    at Function.bulkBuild (/opt/outline/node_modules/sequelize/lib/model.js:1340:22)","level":"error","message":"Error during authentication"}
{"teamId":"aa3ff2c9-db79-4bae-b2b4-1f3b63110a95","avatarUrl":"https://logo.clearbit.com/domain.es","label":"worker","level":"info","message":"UploadTeamAvatarTask running"}
{"name":"teams.create","modelId":null,"label":"worker","level":"info","message":"WebhookProcessor running teams.create"}
```

**Screenshots**
![Error on login](https://gcdnb.pbrd.co/images/wZdczrOlEXpi.png)

**Outline (please complete the following information):**
- Install: Self Hosted (Kubernetes)
- Version: 0.65.2

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 103.0.5060.134

**Comment by pinarruiz** [comment]
Adding more information to the issue:

**Google configuration**

- [x] Google + API
- [x] OAuth consent screen

- Authorized JavaScript origins
  - https://domain.es
- Authorized redirect URIs
  - https://domain.es/auth/google.callback
