### ISSUE TITLE
OIDC with Authelia failing to renew token

### ISSUE THREAD

**Issue by szinn** [outline/outline#4020]
Outline failing to renew expiring tokens with Authelia. Not supplying a refresh token

**To Reproduce**
1. Configure integration between outline and authelia as described in https://www.authelia.com/integration/openid-connect/outline/
2. Log into authelia and then log into outline.
3. After a while:
2022-08-26T18:02:49-04:00 {"userId":"27255a7d-4f68-4261-a589-97db3028acb0","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
2022-08-26T18:02:49-04:00 {"id":"f92af7d8-8792-47cc-a8f2-106a68afc636","userId":"27255a7d-4f68-4261-a589-97db3028acb0","label":"utils","level":"info","message":"Refreshing expiring access token"}
2022-08-26T18:02:49-04:00 {"error":"Invalid authentication","stack":"UnauthorizedError: Invalid authentication\n    at AuthenticationError (/opt/outline/build/server/errors.js:35:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:75:47)\n

will show up in the logs. Authelia is also logging an error saying the refresh token isn't found.

**Expected behavior**
No errors showing in the file and refresh tokens / updated user_authorization table entries managed correctly.

**Outline (please complete the following information):**
- Install: self-hosted
- Version:
      repository: docker.io/outlinewiki/outline
      tag: 0.65.2

**Desktop (please complete the following information):**
- N/A

**Mobile (please complete the following information):**
- N/A

**Comment by tommoor** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/380914/187027195-116c0f4c-df4f-45a5-a993-84cd7d2c0a1e.png">
