### ISSUE TITLE
new outline installation, db migration keeps failing

### ISSUE THREAD

**Issue by leonsteinhaeuser** [outline/outline#4139]
Currently, when I try to deploy outline, I encounter the error below during the database migration.

**To Reproduce**
1. use the configuration from below
2. `yarn sequelize db:migrate`
3. See error

**Expected behavior**
I expect the migration to complete.

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.66.0

Config (env):
```bash
DATABASE_URL=postgres://xxx@pgha1.postgres.svc:5432/outline?sslmode=disable&password=xxx
NODE_VERSION=16.14.2
HOSTNAME=outline-l8bkzvfaip-76464d86b-vr79j
YARN_VERSION=1.22.18
SHLVL=1
HOME=/home/nodejs
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
PWD=/opt/outline
DATABASE_CONNECTION_POOL_MIN=2
DATABASE_CONNECTION_POOL_MAX=10
NODE_ENV=production-ssl-disabled
````

Error:
```bash
/opt/outline $ yarn sequelize db:migrate --env production-ssl-disabled
yarn run v1.22.18
$ /opt/outline/node_modules/.bin/sequelize db:migrate --env production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.4.1, ORM: 6.20.1]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
node:internal/crypto/keys:570
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received null
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at new Hmac (node:internal/crypto/hash:132:9)
    at Object.createHmac (node:crypto:162:10)
    at createHMAC (/opt/outline/node_modules/pg/lib/sasl.js:133:17)
    at Hi (/opt/outline/node_modules/pg/lib/sasl.js:137:13)
    at Object.continueSession (/opt/outline/node_modules/pg/lib/sasl.js:32:24)
    at Client._handleAuthSASLContinue (/opt/outline/node_modules/pg/lib/client.js:257:10)
    at Connection.emit (node:events:526:28)
    at /opt/outline/node_modules/pg/lib/connection.js:115:12
    at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vgwidt** [comment]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received null
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
```

You need to make sure necessary environment variables for Outline are set such as SECRET_KEY

**Comment by leonsteinhaeuser** [comment]
@vgwidt thanks for your reply. I filtered the output a bit to remove the K8s specific environment variables. It seems that I also removed a few outline specific variables. In the "original" environment secret_key and utils_secret are set.
I have updated the list above.

The definition for the variables can be found here:
- https://github.com/programmfabrik/outline-helm/blob/main/charts/outline/templates/secret.yaml
- https://github.com/programmfabrik/outline-helm/blob/main/charts/outline/templates/configmap.yaml
