### ISSUE TITLE
Azure SSO - Error processing task in ValidateSSOAccessTask

### ISSUE THREAD

**Issue by begemotik** [outline/outline#4152]
While working with Outline we constantly see the following error messages in logs.  It doesn't seem that it affects somehow user experience (at least so far). We have SSO configured with Azure AD in accordance with [the doc](https://app.getoutline.com/s/770a97da-13e5-401e-9f8a-37949c19f97e/doc/microsoft-azure-UVz6jsIOcv)

```
{"userId":"c8418a7e-ae79-47d5-8630-15cde49ba492","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"d0c7f1f2-831b-4cca-9b0e-f073e0c34327","userId":"c8418a7e-ae79-47d5-8630-15cde49ba492","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Authentication required","stack":"UnauthorizedError: Authentication required\n    at AuthenticationError (/opt/outline/build/server/errors.js:41:34)\n    at AzureClient.rotateToken (/opt/outline/build/server/utils/oauth.js:75:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:157:24)\n    at async Object.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:110:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:40:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:503:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:26:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"userId":"c8418a7e-ae79-47d5-8630-15cde49ba492","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"d0c7f1f2-831b-4cca-9b0e-f073e0c34327","userId":"c8418a7e-ae79-47d5-8630-15cde49ba492","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Authentication required","stack":"UnauthorizedError: Authentication required\n    at AuthenticationError (/opt/outline/build/server/errors.js:41:34)\n    at AzureClient.rotateToken (/opt/outline/build/server/utils/oauth.js:75:47)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:157:24)\n    at async Object.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:110:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:40:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:503:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:26:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:132:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
```

1. Read the logs of outline container.

**Expected behavior**
Ideally those error messages shouldn't be there

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self-hosted, kubernetes
- Version: 0.66.0, 0.66.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 105.0.5195.102

**Comment by tommoor** [comment]
Please add the `offline` access permission, docs are now updated to reflect this.

**Comment by chr4** [comment]
This still seems to be the case, even with the `offline_access` permission? I'm getting the exact same error regularily.

Is there anything I'm missing?
