### ISSUE TITLE
Error: rollback has been called on this transaction

### ISSUE THREAD

**Issue by AlessandroSpallina** [outline/outline#4155]
I have a self-hosted instance of Outline v0.65.2 and during the last two days I see errors like the following
```
{"id":"1cd05b84-0a79-4feb-9c55-30ef1b0e1770","userId":"2d110ecb-4cb3-43fa-b2c3-47e1d62e61a2","label":"utils","level":"info","message":"Successfully refreshed expired access token"}
/opt/outline/node_modules/sequelize/lib/sequelize.js:290
        const error = new Error(`${options.transaction.finished} has been called on this transaction(${options.transaction.id}), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)`);
                      ^

Error: rollback has been called on this transaction(8405cfa8-96f0-485e-a80f-ae7c26c88d07), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (/opt/outline/node_modules/sequelize/lib/sequelize.js:290:23)
    at /opt/outline/node_modules/sequelize/lib/sequelize.js:300:7
    at /opt/outline/node_modules/retry-as-promised/index.js:69:21
    at new Promise (<anonymous>)
    at retryAsPromised (/opt/outline/node_modules/retry-as-promised/index.js:59:10)
    at Sequelize.query (/opt/outline/node_modules/sequelize/lib/sequelize.js:296:12)
    at PostgresQueryInterface.update (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:355:33)
    at Object.save (/opt/outline/node_modules/sequelize/lib/model.js:2432:79)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  sql: 'UPDATE "user_authentications" SET "refreshToken"=$1,"accessToken"=$2,"expiresAt"=$3,"updatedAt"=$4 WHERE "id" = $5'
}
```
After the login with Keycloak I have the following error message
![image](https://user-images.githubusercontent.com/10786872/191697527-0e8c25b1-bb75-40af-b6fb-3542f4a5c9a5.png)

Any hint about what happened? 

**To Reproduce**
1. self host keycloak and outline

**Outline:**
- Install: self hosted v0.65.2
- Version: docker image `outlinewiki/outline:0.65.2`

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 105

**Comment by tommoor** [comment]
Please fill out the bug template, there is not enough information here to go off – eg what version of the software?

**Comment by AlessandroSpallina** [comment]
@tommoor I updated the first message

**Comment by tommoor** [comment]
First step is upgrade to latest, `v0.66.1` – fixes were made in the latest release that may affect this.
