### ISSUE TITLE
Replace error when starting outline in Docker

### ISSUE THREAD

**Issue by Stitch10925** [outline/outline#4177]
I get the following error when I try to start outline in docker:

yarn run v1.22.18
$ node ./build/server/index.js
/opt/outline/node_modules/sequelize/lib/sequelize.js:58
      options.dialect = urlParts.protocol.replace(/:$/, "");
                                          ^

TypeError: Cannot read properties of null (reading 'replace')
    at new Sequelize (/opt/outline/node_modules/sequelize/lib/sequelize.js:58:43)
    at new Sequelize (/opt/outline/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js:16:9)
    at Object.<anonymous> (/opt/outline/build/server/database/sequelize.js:26:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/outline/build/server/collaboration/PersistenceExtension.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
error Command failed with exit code 1.

**Comment by tommoor** [comment]
Your `DATABASE_URL` env must not be valid.
