### ISSUE TITLE
Google auth new user problem

### ISSUE THREAD

**Issue by matthieuzbo** [outline/outline#4471]
I reproduce error with versions: `0.66.1`, `0.66.2` and `0.66.3`.
I have not tried with `v0.67.0-pre.1`.

We are using authentication with google - gsuite account.

For current members, no issue, everything is working well (I can disconnect and reconnect without any problem, even if private session).

But for new member we have an issue that I don't understand (try with two people, same error): `SequelizeValidationError: Validation error: avatarUrl must be less than 1000 characters`.

Full received error:

```json
{
  "error": "Validation error: avatarUrl must be less than 1000 characters",
  "stack": "SequelizeValidationError: Validation error: avatarUrl must be less than 1000 characters\n    at InstanceValidator._validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:50:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/opt/outline/node_modules/sequelize/lib/instance-validator.js:60:7)\n    at async InstanceValidator.validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:54:12)\n    at async Object.save (/opt/outline/node_modules/sequelize/lib/model.js:2368:7)\n    at async Function.create (/opt/outline/node_modules/sequelize/lib/model.js:1344:12)\n    at async userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:184:18)\n    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:85:20)\n    at async Strategy._verify (/opt/outline/build/server/routes/auth/providers/google.js:84:22)",
  "level": "error",
  "message": "Error during authentication"
}
```

Stack error:

```
SequelizeValidationError: Validation error: avatarUrl must be less than 1000 characters
    at InstanceValidator._validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:50:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InstanceValidator._validateAndRunHooks (/opt/outline/node_modules/sequelize/lib/instance-validator.js:60:7)
    at async InstanceValidator.validate (/opt/outline/node_modules/sequelize/lib/instance-validator.js:54:12)
    at async Object.save (/opt/outline/node_modules/sequelize/lib/model.js:2368:7)
    at async Function.create (/opt/outline/node_modules/sequelize/lib/model.js:1344:12)
    at async userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:184:18)
    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:85:20)
    at async Strategy._verify (/opt/outline/build/server/routes/auth/providers/google.js:84:22)
```

Does somebody have an idea ?

**Comment by tommoor** [comment]
This issue is fixed in the pre-release `v0.67.0-pre.1`
