### ISSUE TITLE
SequelizeDatabaseError: column team.slackId does not exist

### ISSUE THREAD

**Issue by mingwiki** [outline/outline#4627]
It occurs in version 0.66.3, 0.66.2 is fine.

And maybe its a bug from #3493 ?

The log is as following:

```
yarn run v1.22.15
$ sequelize db:migrate --env production-ssl-disabled

Sequelize CLI [Node: 14.18.1, CLI: 6.3.0, ORM: 6.9.0]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
No migrations were executed, database schema was already up to date.
Done in 1.38s.
yarn run v1.22.15
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"label":"lifecycle","level":"info","message":"Starting collaboration service"}
{"label":"lifecycle","level":"info","message":"Starting websockets service"}
{"label":"lifecycle","level":"info","message":"Starting worker service"}
{"label":"lifecycle","level":"info","message":"Starting web service"}
{"level":"warn","message":"Enforced https was disabled with FORCE_HTTPS env variable"}
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:3000"}

  SequelizeDatabaseError: column team.slackId does not exist
      at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:392:16)
      at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
      at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
      at async Function.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1752:21)
      at async /opt/outline/build/server/routes/api/auth.js:52:19
      at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
      at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:17:7)
      at async /opt/outline/node_modules/koa-mount/index.js:58:5
      at async /opt/outline/node_modules/koa-mount/index.js:52:26

DatabaseError [SequelizeDatabaseError]: column team.slackId does not exist
    at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:392:16)
    at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
    at async Function.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1752:21)
    at async /opt/outline/build/server/routes/api/auth.js:52:19
    at async apiWrapperMiddleware (/opt/outline/build/server/routes/api/middlewares/apiWrapper.js:14:5)
    at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:17:7)
    at async /opt/outline/node_modules/koa-mount/index.js:58:5
    at async /opt/outline/node_modules/koa-mount/index.js:52:26 {
  parent: error: column team.slackId does not exist
      at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 110,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '73',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3589',
    routine: 'errorMissingColumn',
    sql: 'SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."signupQueryParams", "team"."guestSignin", "team"."documentEmbeds", "team"."collaborativeEditing", "team"."defaultUserRole", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL);',
    parameters: undefined
  },
  original: error: column team.slackId does not exist
      at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 110,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '73',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3589',
    routine: 'errorMissingColumn',
    sql: 'SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."signupQueryParams", "team"."guestSignin", "team"."documentEmbeds", "team"."collaborativeEditing", "team"."defaultUserRole", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL);',
    parameters: undefined
  },
  sql: 'SELECT "team"."id", "team"."name", "team"."subdomain", "team"."domain", "team"."slackId", "team"."googleId", "team"."avatarUrl", "team"."sharing", "team"."signupQueryParams", "team"."guestSignin", "team"."documentEmbeds", "team"."collaborativeEditing", "team"."defaultUserRole", "team"."createdAt", "team"."updatedAt", "team"."deletedAt", "authenticationProviders"."id" AS "authenticationProviders.id", "authenticationProviders"."name" AS "authenticationProviders.name", "authenticationProviders"."enabled" AS "authenticationProviders.enabled", "authenticationProviders"."providerId" AS "authenticationProviders.providerId", "authenticationProviders"."createdAt" AS "authenticationProviders.createdAt", "authenticationProviders"."teamId" AS "authenticationProviders.teamId" FROM "teams" AS "team" LEFT OUTER JOIN "authentication_providers" AS "authenticationProviders" ON "team"."id" = "authenticationProviders"."teamId" WHERE ("team"."deletedAt" IS NULL);',
  parameters: undefined
}
```

**Comment by mingwiki** [comment]
I use Gitea built-in OAuth2 authorization only, I don't know why slack app was imported and called.

**Comment by tommoor** [comment]
`slackId` doesn't exist in the codebase and hasn't since the PR you linked nearly 6 months ago. It looks like you're not running in docker so you'll need to rebuild the code with `yarn build:server`

**Comment by mingwiki** [comment]
> `slackId` doesn't exist in the codebase and hasn't since the PR you linked nearly 6 months ago. It looks like you're not running in docker so you'll need to rebuild the code with `yarn build:server`

No, I exactly use docker, I tried restart or 'compose down and compose up -d', it does't work.

the compose file is :

```
    image: outlinewiki/outline
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
```

OS is debian11:
![image](https://user-images.githubusercontent.com/7548568/210175189-455f7350-fcd3-4f8f-8234-dde7332e0c8a.png)

**Comment by tommoor** [comment]
Weird, there are thousands of orgs running these docker images. I'd suggest jumping to the [v0.67.0-pre.1](https://github.com/outline/outline/releases/tag/v0.67.0-pre.1) tag.

**Comment by mingwiki** [comment]
the error log does't show when it starts successfully. 
if reflesh the outline page in browser. it will occurs.
