### ISSUE TITLE
InternalOAuthError: Failed to obtain access token with Authelia

### ISSUE THREAD

**Issue by Zoranner** [outline/outline#5245]
### Deploy environment

| Service | Type | Domain |
| ---- | ---- | ---- |
| Ouline | Docker Compose | wiki.master.kim |
| Authelia | Docker Compose | auth.master.kim |
| Nginx Proxy Manger | Docker Compose | - |

**FIRST, i have no problems with DNS.**

#### docker-compose.yml

```yml
---
version: "3"
services:
  outline:
    container_name: outline
    image: outlinewiki/outline
    restart: unless-stopped
    expose: 
      - 3003
    domainname: wiki.master.kim
    networks:
      default:
        aliases:
          - wiki.master.kim
    env_file: ./.env
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  default:
    external: true
    name: nginx
```

#### Configuration

```env
# –––––––––––––––– REQUIRED ––––––––––––––––
URL=https://wiki.master.kim
PORT=3003
# –––––––––––––– AUTHENTICATION ––––––––––––––
OIDC_CLIENT_ID=outline
OIDC_CLIENT_SECRET=SECRET
OIDC_AUTH_URI=https://auth.master.kim/api/oidc/authorization
OIDC_TOKEN_URI=https://auth.master.kim/api/oidc/token
OIDC_USERINFO_URI=https://auth.master.kim/api/oidc/userinfo
OIDC_USERNAME_CLAIM=preferred_username
OIDC_DISPLAY_NAME=Authelia
OIDC_SCOPES=openid profile email groups offline_access
# –––––––––––––––– OPTIONAL ––––––––––––––––
FORCE_HTTPS=true
LOG_LEVEL=debug
```

#### Log

```log
2023-04-23 17:02:56 yarn run v1.22.18
2023-04-23 17:02:56 $ node ./build/server/index.js
2023-04-23 17:03:06 {"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
2023-04-23 17:03:22 {"label":"lifecycle","level":"info","message":"Starting collaboration service"}
2023-04-23 17:03:22 {"label":"lifecycle","level":"info","message":"Starting websockets service"}
2023-04-23 17:03:22 {"label":"lifecycle","level":"info","message":"Starting worker service"}
2023-04-23 17:03:22 {"label":"lifecycle","level":"info","message":"Starting web service"}
2023-04-23 17:03:22 {"label":"lifecycle","level":"info","message":"Listening on http://localhost:3003"}
2023-04-23 17:06:16 {"label":"http","level":"info","message":"  <-- GET /"}
2023-04-23 17:06:18 {"label":"http","level":"info","message":"  --> GET / 200 1,889ms 805b"}
2023-04-23 17:06:19 {"label":"http","level":"info","message":"  <-- POST /api/auth.config"}
2023-04-23 17:06:19 {"label":"http","level":"info","message":"  --> POST /api/auth.config 200 86ms 102b"}
2023-04-23 17:06:20 {"label":"http","level":"info","message":"  <-- GET /static/service-worker.js"}
2023-04-23 17:06:20 {"label":"http","level":"info","message":"  --> GET /static/service-worker.js 200 14ms 11.27kb"}
2023-04-23 17:06:20 {"label":"http","level":"info","message":"  <-- GET /auth/oidc"}
2023-04-23 17:06:21 {"label":"http","level":"info","message":"  --> GET /auth/oidc 302 20ms 0b"}
2023-04-23 17:06:23 {"label":"http","level":"info","message":"  <-- GET /auth/oidc.callback?code=authelia_ac_VP7PHCu4D1PZ0ijLdR7UZ5czXcjbVMXlSP8WgpkN6pQ.43XZL_s7xkIHBczWlSrNCfFZFae3ED__Nqri2GVBJJs&scope=openid+profile+email+groups+offline_access&state=42c2b94a6b12eebe"}
2023-04-23 17:06:23 {"error":"Failed to obtain access token","stack":"InternalOAuthError: Failed to obtain access token\n    at OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)\n    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45\n    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (node:events:526:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at TLSSocket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","level":"error","message":"Error during authentication"}
2023-04-23 17:06:23 {"label":"http","level":"info","message":"  --> GET /auth/oidc.callback?code=authelia_ac_VP7PHCu4D1PZ0ijLdR7UZ5czXcjbVMXlSP8WgpkN6pQ.43XZL_s7xkIHBczWlSrNCfFZFae3ED__Nqri2GVBJJs&scope=openid+profile+email+groups+offline_access&state=42c2b94a6b12eebe 302 112ms 69b"}
2023-04-23 17:06:23 {"label":"http","level":"info","message":"  <-- GET /?notice=auth-error"}
2023-04-23 17:06:23 {"label":"http","level":"info","message":"  --> GET /?notice=auth-error 200 51ms 805b"}
2023-04-23 17:06:24 {"label":"http","level":"info","message":"  <-- POST /api/auth.config"}
2023-04-23 17:06:24 {"label":"http","level":"info","message":"  --> POST /api/auth.config 200 30ms 102b"}
2023-04-23 17:06:25 {"label":"http","level":"info","message":"  <-- GET /static/service-worker.js"}
2023-04-23 17:06:25 {"label":"http","level":"info","message":"  --> GET /static/service-worker.js 200 16ms 11.27kb"}
```

#### docker-compose.yml

```yml
---
version: "3.8"
services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    expose:
      - 9091
    domainname: auth.master.kim
    networks:
      default:
        aliases:
          - auth.master.kim
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /secrets/OIDC_HMAC_SECRET
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /secrets/OIDC/ISSUER_PRIVATE_KEY
    volumes:
      - ./config:/config
      - ./secrets:/secrets
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  default:
    external: true
    name: nginx
```

#### Configuration

```yml
identity_providers:
  oidc:
    ## Cross-Origin Resource Sharing (CORS) settings.
    cors:
      ## List of endpoints in addition to the metadata endpoints to permit cross-origin requests on.
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo

      ## Automatically adds the origin portion of all redirect URI's on all clients to the list of allowed_origins,
      ## provided they have the scheme http or https and do not have the hostname of localhost.
      allowed_origins_from_client_redirect_uris: true

    ## Clients is a list of known clients and their configuration.
    clients:
      - id: outline
        description: Outline
        secret: SECRET
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://wiki.master.kim/auth/oidc.callback
        scopes:
          - openid
          - groups
          - email
          - profile
          - offline_access
        userinfo_signing_algorithm: none
...
```

#### docker-compose.yml

```yml
version: '3'
services:
  manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./data/nginx/snippets:/snippets:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  default:
    external: true
    name: nginx
  nginx:
    driver: bridge
```

**I have searched through all the discussions related to my issue, but none of the solutions seem to work for me. Could you please help me identify where the problem might be? Thank you very much.**

**Comment by tommoor** [comment]
Lets keep this in the original discussion
