### ISSUE TITLE
Export for  stuck processing after upgrade to 0.69.0

### ISSUE THREAD

**Issue by brianvess** [outline/outline#5256]
**To Reproduce**
1. Go to export under settings and click export as any type
2. Export hangs and never completes.
3. Cant export individual collections
4. See the error logs below
5. I can downgrade to 0.6.7 and export works.

**Expected behavior**
Should see exports ready for download. 

**HOSTING**
Docker
nginx proxy manager

**Outline (please complete the following information):**
- Install: self-hosted
- Version: https://github.com/outline/outline/commit/d4da028527f056e196d172c6ff6f023c747b592d

**Desktop (please complete the following information):**
 - OS: e.g. macos Ventura
 - Browser safari, chrome

**Logs**
I have upgraded to the latest version 0.69. I am still not able to export any collection. I have attached logs

```
{"label":"http","level":"info","message":"  --> GET /static/images/whimsical.png 200 3ms 10.54kb"}
{"label":"http","level":"info","message":"  <-- GET /static/images/youtube.png"}
{"label":"http","level":"info","message":"  --> GET /static/images/youtube.png 200 3ms 1.38kb"}
{"label":"http","level":"info","message":"  <-- GET /static/images/zapier.png"}
{"label":"http","level":"info","message":"  --> GET /static/images/zapier.png 200 3ms 2.34kb"}
{"label":"http","level":"info","message":"  <-- GET /static/manifest.webmanifest"}
{"label":"http","level":"info","message":"  --> GET /static/manifest.webmanifest 200 2ms 412b"}
{"userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"69ae17f1-dcd2-4044-8c04-4263ff8c510b","userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Authentication required","stack":"UnauthorizedError: Authentication required\n    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:65:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserAuthentication.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:122:24)\n    at async UserAuthentication.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:79:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:31:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:18:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:109:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"worker","level":"info","message":"ValidateSSOAccessTask running"}
{"id":"69ae17f1-dcd2-4044-8c04-4263ff8c510b","userId":"936214a6-40bc-4c5e-b77f-558e2fc04335","label":"utils","level":"info","message":"Refreshing expiring access token"}
{"error":"Authentication required","stack":"UnauthorizedError: Authentication required\n    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)\n    at OIDCClient.rotateToken (/opt/outline/build/server/utils/oauth.js:65:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserAuthentication.refreshAccessTokenIfNeeded (/opt/outline/build/server/models/UserAuthentication.js:122:24)\n    at async UserAuthentication.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:79:7)\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:31:21\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:18:5)\n    at async Queue.<anonymous> (/opt/outline/build/server/services/worker.js:109:7)","level":"error","message":"Error processing task in ValidateSSOAccessTask"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 153ms 885b"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.export_all"}
{"label":"http","level":"info","message":"  --> POST /api/collections.export_all 200 120ms 824b"}
{"event":{"id":"dc858288-27a4-4a32-804a-19e626e7cb7d","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","collectionId":null,"ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T16:57:49.988Z","userId":null,"documentId":null},"attempt":0,"label":"worker","level":"info","message":"Processing fileOperations.create"}
{"event":{"id":"dc858288-27a4-4a32-804a-19e626e7cb7d","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","collectionId":null,"ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T16:57:49.988Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"FileOperationsProcessor running fileOperations.create"}
{"fileOperationId":"058e1554-f3a3-4a40-acd9-f482891afaae","label":"worker","level":"info","message":"ExportMarkdownZipTask running"}
{"label":"task","level":"info","message":"ExportTask fetching data for 058e1554-f3a3-4a40-acd9-f482891afaae"}
{"event":{"id":"dc858288-27a4-4a32-804a-19e626e7cb7d","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","collectionId":null,"ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T16:57:49.988Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"WebhookProcessor running fileOperations.create"}
{"label":"task","level":"info","message":"ExportTask processing data for 058e1554-f3a3-4a40-acd9-f482891afaae"}
{"event":{"id":"e07a84b5-74b1-439c-b0dc-fdcf9baf52ba","createdAt":"2023-04-24T16:57:50.243Z","name":"fileOperations.update","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","data":{"id":"058e1554-f3a3-4a40-acd9-f482891afaae","type":"export","format":"outline-markdown","name":"WebsoftPC-export.zip","state":"creating","error":null,"size":"0","collectionId":null,"user":{"id":"936214a6-40bc-4c5e-b77f-558e2fc04335","name":"Brian Vess","avatarUrl":"https://minio.websoftpc.com/outline/public/936214a6-40bc-4c5e-b77f-558e2fc04335/4d1b4295-7872-4002-ab7d-f61f3a96242a/kisspng-yoda-luke-skywalker-jedi-computer-icons-children-chair-5addf50a871355.1139938815244956265533.png","color":"#9E5CF7","isAdmin":true,"isSuspended":false,"isViewer":false,"createdAt":"2022-09-30T22:19:05.219Z","updatedAt":"2023-04-24T16:57:20.798Z","lastActiveAt":"2023-04-24T16:57:20.796Z"},"createdAt":"2023-04-24T16:57:49.974Z","updatedAt":"2023-04-24T16:57:49.974Z"}},"attempt":0,"label":"worker","level":"info","message":"Processing fileOperations.update"}
{"event":{"id":"e07a84b5-74b1-439c-b0dc-fdcf9baf52ba","createdAt":"2023-04-24T16:57:50.243Z","name":"fileOperations.update","modelId":"058e1554-f3a3-4a40-acd9-f482891afaae","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","data":{"id":"058e1554-f3a3-4a40-acd9-f482891afaae","type":"export","format":"outline-markdown","name":"WebsoftPC-export.zip","state":"creating","error":null,"size":"0","collectionId":null,"user":{"id":"936214a6-40bc-4c5e-b77f-558e2fc04335","name":"Brian Vess","avatarUrl":"https://minio.websoftpc.com/outline/public/936214a6-40bc-4c5e-b77f-558e2fc04335/4d1b4295-7872-4002-ab7d-f61f3a96242a/kisspng-yoda-luke-skywalker-jedi-computer-icons-children-chair-5addf50a871355.1139938815244956265533.png","color":"#9E5CF7","isAdmin":true,"isSuspended":false,"isViewer":false,"createdAt":"2022-09-30T22:19:05.219Z","updatedAt":"2023-04-24T16:57:20.798Z","lastActiveAt":"2023-04-24T16:57:20.796Z"},"createdAt":"2023-04-24T16:57:49.974Z","updatedAt":"2023-04-24T16:57:49.974Z"}},"label":"worker","level":"info","message":"WebhookProcessor running fileOperations.update"}
{"label":"http","level":"info","message":"  <-- GET /settings/export"}
{"label":"http","level":"info","message":"  --> GET /settings/export 200 41ms 1.2kb"}
{"label":"http","level":"info","message":"  <-- GET /static/manifest.webmanifest"}
{"label":"http","level":"info","message":"  --> GET /static/manifest.webmanifest 200 3ms 412b"}
{"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
{"label":"http","level":"info","message":"  <-- GET /locales/en_US.json"}
{"label":"http","level":"info","message":"  --> POST /api/auth.info 200 19ms 2.35kb"}
{"label":"http","level":"info","message":"  --> GET /locales/en_US.json 200 164ms 10.95kb"}
{"label":"http","level":"info","message":"  <-- GET /opensearch.xml"}
{"label":"http","level":"info","message":"  --> GET /opensearch.xml 200 3ms 567b"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 31ms 1.61kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 85ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 125ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 238ms 7.04kb"}
{"label":"multiplayer","level":"info","message":"New connection to \"document.cd952795-9231-4d32-ba63-00d361bb73ba\""}
{"label":"database","level":"info","message":"Document cd952795-9231-4d32-ba63-00d361bb73ba is in database state"}
{"userId":"d513857d-2f1d-4bd9-a89f-01761b1b7da5","label":"multiplayer","level":"info","message":"Loaded document \"document.cd952795-9231-4d32-ba63-00d361bb73ba\""}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 75ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /settings/export"}
{"label":"http","level":"info","message":"  --> GET /settings/export 200 69ms 1.2kb"}
{"label":"http","level":"info","message":"  <-- GET /static/manifest.webmanifest"}
{"label":"http","level":"info","message":"  --> GET /static/manifest.webmanifest 200 5ms 412b"}
{"label":"http","level":"info","message":"  <-- GET /locales/en_US.json"}
{"label":"http","level":"info","message":"  <-- POST /api/auth.info"}
{"label":"http","level":"info","message":"  --> GET /locales/en_US.json 200 260ms 10.95kb"}
{"label":"http","level":"info","message":"  --> POST /api/auth.info 200 313ms 2.35kb"}
{"label":"http","level":"info","message":"  <-- GET /opensearch.xml"}
{"label":"http","level":"info","message":"  --> GET /opensearch.xml 200 2ms 567b"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 69ms 1.61kb"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.drafts"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.list"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.list"}
{"label":"http","level":"info","message":"  <-- POST /api/stars.list"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.viewed"}
--
{"label":"http","level":"info","message":"  --> GET / 200 104ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 100ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.drafts"}
{"label":"http","level":"info","message":"  <-- POST /api/pins.list"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.viewed"}
{"label":"http","level":"info","message":"  <-- POST /api/documents.list"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.list"}
{"label":"http","level":"info","message":"  <-- POST /api/stars.list"}
{"label":"http","level":"info","message":"  --> POST /api/pins.list 200 551ms 156b"}
{"label":"http","level":"info","message":"  --> POST /api/stars.list 200 287ms 158b"}
{"label":"http","level":"info","message":"  --> POST /api/documents.list 200 678ms 5.04kb"}
{"label":"http","level":"info","message":"  --> POST /api/documents.drafts 200 741ms 30.16kb"}
{"label":"http","level":"info","message":"  --> POST /api/collections.list 200 404ms 78.52kb"}
{"label":"http","level":"info","message":"  --> POST /api/documents.viewed 200 807ms 138.67kb"}
{"label":"http","level":"info","message":"  <-- POST /api/collections.export"}
{"label":"http","level":"info","message":"  --> POST /api/collections.export 200 167ms 841b"}
{"event":{"id":"365f74bb-cee4-4723-9fcf-1bcb97585950","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"f018c6a9-ebf9-4bd1-9dda-e5be0799b3fb","collectionId":"827975cf-901c-4b1e-b94d-8a30b933f141","ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T17:19:35.531Z","userId":null,"documentId":null},"attempt":0,"label":"worker","level":"info","message":"Processing fileOperations.create"}
{"event":{"id":"365f74bb-cee4-4723-9fcf-1bcb97585950","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"f018c6a9-ebf9-4bd1-9dda-e5be0799b3fb","collectionId":"827975cf-901c-4b1e-b94d-8a30b933f141","ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T17:19:35.531Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"FileOperationsProcessor running fileOperations.create"}
{"event":{"id":"365f74bb-cee4-4723-9fcf-1bcb97585950","name":"fileOperations.create","teamId":"1ebe5319-0bb9-4fcc-801b-d22bdfca125b","actorId":"936214a6-40bc-4c5e-b77f-558e2fc04335","modelId":"f018c6a9-ebf9-4bd1-9dda-e5be0799b3fb","collectionId":"827975cf-901c-4b1e-b94d-8a30b933f141","ip":"199.87.14.15","data":{"type":"export","format":"outline-markdown"},"createdAt":"2023-04-24T17:19:35.531Z","userId":null,"documentId":null},"label":"worker","level":"info","message":"WebhookProcessor running fileOperations.create"}
{"label":"http","level":"info","message":"  <-- POST /api/fileOperations.list"}
{"label":"http","level":"info","message":"  --> POST /api/fileOperations.list 200 59ms 2.37kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 109ms 7.04kb"}
{"label":"http","level":"info","message":"  <-- GET /"}
{"label":"http","level":"info","message":"  --> GET / 200 70ms 7.04kb"}
```

**Comment by brianvess** [comment]
![Screen Shot 2023-04-25 at 2 43 45 PM](https://user-images.githubusercontent.com/53948675/234411166-c9b7fa8d-df90-4555-bb78-3dc3c48ca771.png)

**Comment by tommoor** [comment]
Your issue says this is after upgrade to `v0.69.0` but your screenshot includes a failed export from 2 months ago?

**Comment by Gaurhoth** [comment]
This happened to me as well, after upgrading from 0.67.x (I can't remember if it was .0, .1, or .2) to 0.68.1. I could never export anything after that. Nothing ever showed up in the logs as an error and none of the processing exports ever finished. 

I eventually gave up and assumed I borked something during one of the deployments or upgrades (I did go through a lot of trial and error to get S3 integration working), and deployed a new/clean instance of 0.68.1 and manually copy/pasted my already entered documents into the new instance. Since then, exports have worked fine even after upgrading to 0.69.0.

Going forward, I do a nightly exports to json format in the hopes that if something like this happens again - I can just import the last successfully exported json bundle into a new instance.

**Comment by tommoor** [comment]
There's just not enough to go off here, we'll probably need to add a bunch of debug logs and get a build out to see where it's getting stuck in this circumstance…

**Comment by brianvess** [comment]
There is about 200 mb of data total for export. Even the smallest collection individually will not export. If you give me some commands or tell me how to enable more debugging I will provide the information. Is there a way to kill the existing exports?

**Comment by brianvess** [comment]
> Your issue says this is after upgrade to `v0.69.0` but your screenshot includes a failed export from 2 months ago?

I had opened this issue back a couple of months ago but it kept getting closed.

**Comment by Gaurhoth** [comment]
In my case, my last successful export was around 13mb. So very small. I still have the broken instance, so if you have something you'd like me to try in order to help others, I can spin that back up as well.

**Comment by tommoor** [comment]
If one of you can add the following in environment `LOG_LEVEL=debug`, then do another export, that will output all the sql queries that happen among other things, hopefully that'll be enough information to figure out where it gets locked up.

**Comment by brianvess** [comment]
[logs.txt](https://github.com/outline/outline/files/11345702/logs.txt)

**Comment by tommoor** [comment]
Those seem like Minio logs or something else entirely, we need Outline's logs…

**Comment by Gwemox** [comment]
I can do it, the logs contain sensitive information?

**Comment by tommoor** [comment]
Potentially, although we attempt to scrub sensitive info from being printed in logs. You can also email them to tom@linear.app

**Comment by brianvess** [comment]
> These logs are no different to what you posted before, did you change the `LOG_LEVEL` configuration?

I did put the debug in the .env file are restarted the pod

**Comment by Gwemox** [comment]
> Potentially, although we attempt to scrub sensitive info from being printed in logs. You can also email them to [tom@getoutline.com](mailto:tom@getoutline.com)

I sent the logs by email.

**Comment by brianvess** [comment]
I created a new default deployment and tried to complete an export, and the export failed. Please see the below screenshot. 


<img width="826" alt="Screenshot 2023-04-29 at 7 42 33 PM" src="https://user-images.githubusercontent.com/53948675/235333088-03b4bb02-bed7-48b4-868e-b37034b71355.png">

**Comment by brianvess** [comment]
I found an exported backup from two months ago. I was able to create a new instance and import the backup. I was able to export from the new instance. I downloaded the mark down of each file created within the last two months an will work on recreating them in the new instance.

**Comment by tommoor** [comment]
`v0.69.1` was pushed yesterday, it includes _lots_ of additional debug logging to try and narrow this down. It doesn't reproduce on the cloud hosted instance at all

**Comment by Gwemox** [comment]
@brianvess What is your provider for the S3?

**Comment by tommoor** [comment]
Yea, I came to the same conclusion too, see the PR if anyone that can reproduce wants to test that branch. I've never been able to reproduce the issue unfortunately

**Comment by Gwemox** [comment]
This branch comes with new irreversible features compared to 0.69.1

**Comment by tommoor** [comment]
I'm not sure what you mean, you can cherry pick the changes from that branch if you prefer.

**Comment by Gwemox** [comment]
If I switch my production to your branch, can I go back? It seems to me that database migrations will block.

I will cherry-pick to test

**Comment by tommoor** [comment]
Easiest is to switch the branch and delete that migration – it's just cleaning up an old database table so it won't cause issues to not run it.

**Comment by brianvess** [comment]
> @brianvess What is your provider for the S3?
> 
> Edit : I think the source of the problem is [767850d](https://github.com/outline/outline/commit/767850dbcdadff6c991474a313bf0860707bdf49) #4796
> 
> Edit 2: @tommoor I confirm I reverted the commit and it works.

I am using minio in docker.

**Comment by brianvess** [comment]
I found an exported backup from two months ago. I was able to create a new instance and import the backup. I was able to export from the new instance. I downloaded the markdown of each file created within the last two months and will work on recreating them in the new instance.
