### ISSUE TITLE
Uncaught RangeError when copying and pasting within app

### ISSUE THREAD

**Issue by vgwidt** [outline/outline#5502]
When cutting and pasting certain* content from within the app, the data would appear briefly then disappear, and the following exception was thrown in the console:
```
Uncaught RangeError: No value supplied for attribute id
    at computeAttrs (index.es.js:1864:20)
    at MarkType2.create2 [as create] (index.es.js:2106:25)
    at ParseContext2.addElementByRule (index.es.js:2964:21)
    at ParseContext2.addElement (index.es.js:2912:10)
    at ParseContext2.addDOM (index.es.js:2850:10)
    at ParseContext2.addAll (index.es.js:2998:10)
    at ParseContext2.addElementByRule (index.es.js:2982:10)
    at ParseContext2.addElement (index.es.js:2912:10)
    at ParseContext2.addDOM (index.es.js:2850:10)
    at ParseContext2.addAll (index.es.js:2998:10)
computeAttrs @ index.es.js:1864
create2 @ index.es.js:2106
addElementByRule @ index.es.js:2964
addElement @ index.es.js:2912
addDOM @ index.es.js:2850
addAll @ index.es.js:2998
addElementByRule @ index.es.js:2982
addElement @ index.es.js:2912
addDOM @ index.es.js:2850
addAll @ index.es.js:2998
parse2 @ index.es.js:2616
parseBetween @ index.js:4440
readDOMChange @ index.js:4501
(匿名) @ index.js:4835
flush @ index.js:4339
DOMObserver.observer @ index.js:4216
```

* I cannot say what content it was that caused it.  I was cutting and pasting, so I unfortunately lost the exact data and could only retain the plain text version by pasting with shift.  When looking at a revision from about 15 minutes prior, I can see that the :: notice was not at all where it was supposed to be.  I had noticed before that when refreshing the page, the warning would often encompass data that it shouldn't.  Here is what it looks like in the revision (it is supposed to just display over "This is the point at which ...".  So I'm suspicious that this might be causing the problem.

![image](https://github.com/outline/outline/assets/49006240/ab2e6ece-cbb9-46a5-908a-151e53f11e94)

Sorry I know this may not be enough to go off of, but it felt a bit too strange to leave as is.  Let me know if I can provide any more information.  I'm going to try to find a way to recreate the behavior.

**Expected behavior**
Data copied from Outline should be pastable while retaining all formatting

**Outline (please complete the following information):**
- Install: self-hosted
- Version: 69.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge

**Comment by vgwidt** [comment]
I was able to recreate it once by adding comments in various places (in info blocks, headings, and text) then deleting the comments after I remembered I had comments but deleted for the page that original spawned this issue.  But I can't reproduce it reliably yet.  I'll build from source when I have a bit more time and try to see if I can find a solid way to reproduce it.

**Comment by vgwidt** [comment]
I can confirm this happens when pasting comments.  To reproduce just copy text that contains a link to a comment.  I have not built from source yet.
