### ISSUE TITLE
500 TokenError when I try to login with OIDC

### ISSUE THREAD

**Issue by kirill-dev-pro** [outline/outline#5648]
Hello. I'm getting this error when my browser navigates back to callback URL from OAuth provider with code, this is example of URL
```
http://localhost:3010/auth/oidc.callback?code=uH2S1CWitgpr0LuErV1us8EidBO4IKqwTa1DA32X6tC0GZJd&state=8bacec9eb0e6a745
```
This is error from the console
```
[backend] [api] Error during authentication
[backend] [api] TokenError
[backend] [api]     at OAuth2Strategy.parseErrorResponse (/Users/kirill/Temp/outline/node_modules/passport-oauth2/lib/strategy.js:374:12)
[backend] [api]     at OAuth2Strategy._createOAuthError (/Users/kirill/Temp/outline/node_modules/passport-oauth2/lib/strategy.js:421:16)
[backend] [api]     at /Users/kirill/Temp/outline/node_modules/passport-oauth2/lib/strategy.js:177:45
[backend] [api]     at /Users/kirill/Temp/outline/node_modules/oauth/lib/oauth2.js:191:18
[backend] [api]     at passBackControl (/Users/kirill/Temp/outline/node_modules/oauth/lib/oauth2.js:132:9)
[backend] [api]     at IncomingMessage.<anonymous> (/Users/kirill/Temp/outline/node_modules/oauth/lib/oauth2.js:157:7)
[backend] [api]     at IncomingMessage.emit (node:events:539:35)
[backend] [api]     at IncomingMessage.emit (node:domain:475:12)
[backend] [api]     at endReadableNT (node:internal/streams/readable:1345:12)
[backend] [api]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[backend] [api]   message: undefined,
[backend] [api]   code: 'invalid_client',
[backend] [api]   uri: undefined,
[backend] [api]   status: 500
[backend] [api] }
```

**To Reproduce**
1. Setup variables for custom oidc provider
2. start a development server
3. open web page
4. click to login with your provider
5. accept login on the side of oidc provider
6. get error when browser navigates back to outline

**Expected behavior**
Login to own outline instance

**Screenshots**
<img width="1040" alt="image" src="https://github.com/outline/outline/assets/8945959/d8b465da-5914-4128-8f38-cb24cb8ad978">

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.70.2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Arc
 - Version Version 1.1.1 (40415) Chromium Engine Version 115.0.5790.114

**Comment by tommoor** [comment]
I'm not sure which OIDC provider you're using as it wasn't detailed – but you can see in the error response from your OIDC server that the error is `invalid_client`.
