### ISSUE TITLE
Errors and re-logins after upgrading to v0.71.0

### ISSUE THREAD

**Issue by marcociarrocca** [outline/outline#5813]
Upgrading to v0.71.0 from v0.69.2, we started noticing an increased number of errors in Sentry (reported below), and an increased frequency in Outline's requests to log in again. When the login bug happens, the publicly-shared pages also return a 404.

Examples of the errors in Sentry:

TypeError: Right side of assignment cannot be destructured
  at ? (../../../app/models/Collection.ts:137:37)

TypeError: Cannot destructure property 'data' of '(intermediate value)' as it is undefined.
  at Collection.fetchDocuments(../../../app/models/Collection.ts:137:15)

Invariant Violation: Comment list not available
  at invariant$1(../../../node_modules/invariant/browser.js:38:15)
  at CommentsStore.fetchDocumentComments(../../../app/stores/CommentsStore.ts:85:17)

Invariant Violation: Data not available
  at invariant$1(../../../node_modules/invariant/browser.js:38:15)
  at BaseStore.fetchPage(../../../app/stores/BaseStore.ts:233:17)
  at async fetchViews(../../../app/scenes/Document/components/DataLoader.tsx:137:13)

Invariant Violation: Data not available
  at invariant$1(../../../node_modules/invariant/browser.js:38:15)
  at BaseStore.fetchPage(../../../app/stores/BaseStore.ts:233:17)
  at async fetchEmbedIntegrations(../../../app/hooks/useEmbeds.ts:21:11)

Invariant Violation: Document list not available
  at ? (../../../app/stores/DocumentsStore.ts:296:17)

Error: Invalid login: 535 Authentication Failed
  File "/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js", line 790, col 19, in SMTPConnection._formatError
    err = new Error(message);
  File "/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js", line 1564, col 34, in SMTPConnection._actionAUTHComplete
    return callback(this._formatError('Invalid login', 'EAUTH', str, 'AUTH ' + this._authMethod));
  File "/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js", line 546, col 26, in SMTPConnection.<anonymous>
    this._actionAUTHComplete(str, callback);
  File "/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js", line 969, col 20, in SMTPConnection._processResponse
    action.call(this, str);
  File "/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js", line 755, col 14, in SMTPConnection._onData
    this._processResponse();
  File "/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js", line 193, col 44, in SMTPConnection._onSocketData
    this._onSocketData = chunk => this._onData(chunk);
  File "node:events", line 514, col 28, in TLSSocket.emit
  File "node:domain", line 489, col 12, in TLSSocket.emit
  File "node:internal/streams/readable", line 324, col 12, in addChunk
  File "node:internal/streams/readable", line 297, col 9, in readableAddChunk
  File "node:internal/streams/readable", line 234, col 10, in Readable.push
  File "node:internal/stream_base_commons", line 190, col 23, in TLSWrap.onStreamRead

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.71.0 (Docker)

**Desktop:**
 - OS: macOS 13.5.2
 - Browser: Safari 16.6, Chrome 116.0.0

**Comment by tommoor** [comment]
As of `0.71.0` the expiry time of the token issued from your authentication provider is respected, if you need to stay logged in longer ensure that the auth provider issues a refresh token as well so that Outline can refresh the auth.

https://github.com/outline/outline/discussions/5760#discussioncomment-6890656
