### ISSUE TITLE
[onAuthenticate] Operation timeout

### ISSUE THREAD

**Issue by Mag1cByt3s** [outline/outline#5964]
I suddenly got a 502 from outline and saw this error stacktrace in the docker logs.

I am not quite sure what happened and i don't know how to reproduce this error.

```
[onAuthenticate] Operation timeout
ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
    at ConnectionManager.getConnection (/opt/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:305:26
    at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async team.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1140:21)
    at async team.findOne (/opt/outline/node_modules/sequelize/lib/model.js:1240:12)
    at async getTeamFromContext (/opt/outline/build/server/utils/passport.js:113:14)
    at async /opt/outline/build/server/routes/index.js:119:16
    at async compressMiddleware (/opt/outline/node_modules/koa-compress/lib/index.js:56:5)
    at async /opt/outline/build/server/routes/index.js:146:3
    at async userAgent (/opt/outline/node_modules/koa-useragent/dist/index.js:12:5)
    at async /opt/outline/node_modules/koa-mount/index.js:52:26
    at async /opt/outline/node_modules/koa-mount/index.js:52:26 {
  parent: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7),
  original: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)
}
ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
    at ConnectionManager.getConnection (/opt/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:305:26
    at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async team.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1140:21)
    at async team.findOne (/opt/outline/node_modules/sequelize/lib/model.js:1240:12)
    at async getTeamFromContext (/opt/outline/build/server/utils/passport.js:113:14)
    at async /opt/outline/build/server/routes/index.js:119:16
    at async compressMiddleware (/opt/outline/node_modules/koa-compress/lib/index.js:56:5)
    at async /opt/outline/build/server/routes/index.js:146:3
    at async userAgent (/opt/outline/node_modules/koa-useragent/dist/index.js:12:5)
    at async /opt/outline/node_modules/koa-mount/index.js:52:26
    at async /opt/outline/node_modules/koa-mount/index.js:52:26 {
  parent: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7),
  original: TimeoutError: Operation timeout
      at Timeout.<anonymous> (/opt/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)
}
```

**Comment by tommoor** [comment]
Impossible to say I’m afraid, your server could not connect to the database temporarily. You can check the database logs for clues
