### ISSUE TITLE
Uploading multiple attachments at once fails with local file storage

### ISSUE THREAD

**Issue by jannschu** [outline/outline#6042]
If I try to upload many attachments the API `/api/attachments.create` blocks and runs into a timeout.

**To Reproduce**
1. Configure local file storage.
2. Start local version by running `make`.
3. Try to upload 10 files at once with drag an drop into a document. The files can be emtpy.
4. The API requests run into a time out, no attachments are uploaded.

The problem also shows up in a release build that uses local file storage.

**Expected behavior**
The attachments should be uploaded.

**Error log**

Here is a log excerpt that may be relevant:

```
[backend] [api] info: [http]   xxx POST /api/attachments.create 500 30s -
[backend] [api] ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
[backend] [api]     at ConnectionManager.getConnection (/Users/username/Documents/outline/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:206:15)
[backend] [api]     at runNextTicks (node:internal/process/task_queues:60:5)
[backend] [api]     at listOnTimeout (node:internal/timers:538:9)
[backend] [api]     at process.processTimers (node:internal/timers:512:7)
[backend] [api]     at async /Users/username/Documents/outline/node_modules/sequelize/lib/sequelize.js:305:26
[backend] [api]     at async PostgresQueryInterface.select (/Users/username/Documents/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
[backend] [api]     at async document.findAll (/Users/username/Documents/outline/node_modules/sequelize/lib/model.js:1140:21)
[backend] [api]     at async document.findOne (/Users/username/Documents/outline/node_modules/sequelize/lib/model.js:1240:12)
[backend] [api]     at async /Users/username/Documents/outline/build/server/routes/api/attachments/attachments.js:50:22
[backend] [api]     at async /Users/username/Documents/outline/node_modules/sequelize/lib/sequelize.js:507:18
[backend] [api]     at async transactionMiddleware (/Users/username/Documents/outline/build/server/middlewares/transaction.js:17:5)
[backend] [api]     at async apiWrapperMiddleware (/Users/username/Documents/outline/build/server/routes/api/middlewares/apiWrapper.js:12:5)
[backend] [api]     at async userAgent (/Users/username/Documents/outline/node_modules/koa-useragent/dist/index.js:12:5)
[backend] [api]     at async /Users/username/Documents/outline/node_modules/koa-mount/index.js:58:5
[backend] [api]     at async /Users/username/Documents/outline/node_modules/koa-mount/index.js:52:26
[backend] [api]     at async /Users/username/Documents/outline/node_modules/@bull-board/koa/node_modules/koa-mount/index.js:52:26
[backend] [api]     at async logger (/Users/username/Documents/outline/node_modules/koa-logger/index.js:67:7) {
[backend] [api]   parent: TimeoutError: Operation timeout
[backend] [api]       at Timeout.<anonymous> (/Users/username/Documents/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
[backend] [api]       at listOnTimeout (node:internal/timers:569:17)
[backend] [api]       at process.processTimers (node:internal/timers:512:7),
[backend] [api]   original: TimeoutError: Operation timeout
[backend] [api]       at Timeout.<anonymous> (/Users/username/Documents/outline/node_modules/sequelize-pool/lib/Deferred.js:17:25)
[backend] [api]       at listOnTimeout (node:internal/timers:569:17)
[backend] [api]       at process.processTimers (node:internal/timers:512:7)
[backend] [api] }
```

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.72.2

**Desktop (please complete the following information):**
 - OS: macOS 13.6
 - Browser Chrome
 - Version Version 118.0.5993.88 
 
Also reproduced this with Firefox 118.0.1.

**Comment by jannschu** [comment]
This is not restricted to the local file storage, I could also reproduce it with `FILE_STORAGE=s3` locally.

**Comment by tommoor** [comment]
I can't reproduce, try increasing `DATABASE_CONNECTION_POOL_MAX` to `10` or higher, I suspect you're overwhelming the connections to the db.

**Comment by tommoor** [comment]
@jannschu good find, if you want to make the PR and get credit let me know otherwise will address in the next few days. More thorough use of transactions is being added gradually, the codebase used to have none several years ago – this is certainly a gotcha that we need to ensure all db requests within a route handler are using the same transaction once any are.
