### ISSUE TITLE
Uploading a video file exceeding 200M will result in an error that the file size exceeds the setting, and the FILE_STORAGE_UPLOAD_MAX_SIZE configured in docker.env does not take effect.

### ISSUE THREAD

**Issue by Https443** [outline/outline#6085]
Uploading a video file exceeding 200M will result in an error that the file size exceeds the setting, and the FILE_STORAGE_UPLOAD_MAX_SIZE configured in docker.env does not take effect.

**To Reproduce**
1. Upload a video file (274MB)
2. Received log error

```
FormidableError: options.maxFileSize (209715200 bytes) exceeded, received 209776884 bytes of file data
    at Stream.<anonymous> (/opt/outline/node_modules/formidable/src/Formidable.js:358:11)
    at Stream.emit (node:events:517:28)
    at Stream.emit (node:domain:489:12)
    at MultipartParser.dataPropagation (/opt/outline/node_modules/formidable/src/plugins/multipart.js:104:22)
    at MultipartParser.emit (node:events:529:35)
    at MultipartParser.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Readable.push (node:internal/streams/readable:245:10)
    at MultipartParser._handleCallback (/opt/outline/node_modules/formidable/src/parsers/Multipart.js:100:10)
    at dataCallback (/opt/outline/node_modules/formidable/src/parsers/Multipart.js:130:14)
    at MultipartParser._transform (/opt/outline/node_modules/formidable/src/parsers/Multipart.js:323:5)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at IncomingForm.write (/opt/outline/node_modules/formidable/src/Formidable.js:254:18)
    at IncomingMessage.<anonymous> (/opt/outline/node_modules/formidable/src/Formidable.js:201:16)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at Readable.read (node:internal/streams/readable:550:10)
    at flow (node:internal/streams/readable:1032:34) {
  code: 1009,
  httpCode: 413
}
```

Outline (please complete the following information):
- Install: docker
- Version: v0.72.2 [Latest] (https://github.com/outline/outline/commit/6f234bef1156910e0f2964702835f900d3e115af)

**Comment by tommoor** [comment]
Fixed in b53c595e1bcdeab84c0dab85ca24a48e8749686b
