### ISSUE TITLE
Migration error with new installs of 0.73.0

### ISSUE THREAD

**Issue by gramakri** [outline/outline#6153]
**To Reproduce**
* Install 0.73.0
* Run `yarn db:migrate`
* Migration error. `error: column "sourceMetadata" does not exist`

```
root@9a99776a-5b6a-4fa3-8a83-252284784ec8:/app/code# gosu cloudron:cloudron yarn db:migrate --env=production-ssl-disabled
yarn run v1.22.19
$ sequelize db:migrate --env=production-ssl-disabled

Sequelize CLI [Node: 18.18.0, CLI: 6.6.1, ORM: 6.33.0]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
== 20160619080644-initial: migrating =======
== 20160619080644-initial: migrated (0.044s)

== 20160622043741-add-parent-document: migrating =======
== 20160622043741-add-parent-document: migrated (0.006s)

== 20160626063409-add-indexes: migrating =======
== 20160626063409-add-indexes: migrated (0.028s)

== 20160626175224-add-revisions: migrating =======
== 20160626175224-add-revisions: migrated (0.026s)

== 20160711071958-search-index: migrating =======
== 20160711071958-search-index: migrated (0.026s)

== 20160726061511-atlas-creator: migrating =======
== 20160726061511-atlas-creator: migrated (0.015s)

== 20160812145029-document-atlas-soft-delete: migrating =======
== 20160812145029-document-atlas-soft-delete: migrated (0.022s)

== 20160814083127-paranoia-indeces: migrating =======
== 20160814083127-paranoia-indeces: migrated (0.052s)

== 20160814095336-add-document-createdById: migrating =======
== 20160814095336-add-document-createdById: migrated (0.010s)

== 20160814111419-add-document-collaboratorIds: migrating =======
== 20160814111419-add-document-collaboratorIds: migrated (0.006s)

== 20160815142720-app-collection-urlId: migrating =======
== 20160815142720-app-collection-urlId: migrated (0.010s)

== 20160816082738-add-revision-index: migrating =======
== 20160816082738-add-revision-index: migrated (0.011s)

== 20160824061730-add-apikeys: migrating =======
== 20160824061730-add-apikeys: migrated (0.017s)

== 20160824062457-add-apikey-indeces: migrating =======
== 20160824062457-add-apikey-indeces: migrated (0.015s)

== 20160911230444-user-optional-slack-id: migrating =======
== 20160911230444-user-optional-slack-id: migrated (0.041s)

== 20160911232911-user-unique-fields: migrating =======
== 20160911232911-user-unique-fields: migrated (0.036s)

== 20160911234928-user-password: migrating =======
== 20160911234928-user-password: migrated (0.012s)

== 20170603185012-add-collection-documentStructure-migration: migrating =======
== 20170603185012-add-collection-documentStructure-migration: migrated (0.015s)

== 20170604052346-add-views: migrating =======
== 20170604052346-add-views: migrated (0.022s)

== 20170604052347-add-stars: migrating =======
== 20170604052347-add-stars: migrated (0.020s)

== 20170712055148-non-unique-email: migrating =======
== 20170712055148-non-unique-email: migrated (0.015s)

== 20170712072234-uniq-slack-id: migrating =======
== 20170712072234-uniq-slack-id: migrated (0.013s)

== 20170729215619-emoji: migrating =======
== 20170729215619-emoji: migrated (0.012s)

== 20170827182423-improve-references: migrating =======
== 20170827182423-improve-references: migrated (0.027s)

== 20170904202454-allow-null-username: migrating =======
== 20170904202454-allow-null-username: migrated (0.009s)

== 20171010042938-add-event: migrating =======
== 20171010042938-add-event: migrated (0.018s)

== 20171016012353-remove-collection-navigationtree: migrating =======
== 20171016012353-remove-collection-navigationtree: migrated (0.012s)

== 20171017055026-remove-document-html: migrating =======
== 20171017055026-remove-document-html: migrated (0.015s)

== 20171019071915-user-avatar-url: migrating =======
== 20171019071915-user-avatar-url: migrated (0.013s)

== 20171023064220-collection-color: migrating =======
== 20171023064220-collection-color: migrated (0.008s)

== 20171218043717-add-authentications: migrating =======
== 20171218043717-add-authentications: migrated (0.013s)

== 20171225143838-set-admins: migrating =======
== 20171225143838-set-admins: migrated (0.007s)

== 20180115021837-add-drafts: migrating =======
== 20180115021837-add-drafts: migrated (0.020s)

== 20180212033504-add-integrations: migrating =======
== 20180212033504-add-integrations: migrated (0.015s)

== 20180225203847-document-pinning: migrating =======
== 20180225203847-document-pinning: migrated (0.008s)

== 20180303193036-suspended-users: migrating =======
== 20180303193036-suspended-users: migrated (0.008s)

== 20180324214403-serializer-upgrade: migrating =======
== 20180324214403-serializer-upgrade: migrated (0.006s)

== 20180513041057-add-share-links: migrating =======
== 20180513041057-add-share-links: migrated (0.011s)

== 20180528233909-google-auth: migrating =======
== 20180528233909-google-auth: migrated (0.044s)

== 20180528233910-rename-serviceid: migrating =======
== 20180528233910-rename-serviceid: migrated (0.048s)

== 20180604182823-user-tracking: migrating =======
== 20180604182823-user-tracking: migrated (0.017s)

== 20180604191743-revoke-share-links: migrating =======
== 20180604191743-revoke-share-links: migrated (0.013s)

== 20180707220121-more-soft-delete: migrating =======
== 20180707220121-more-soft-delete: migrated (0.014s)

== 20180707231201-remove-passwords: migrating =======
== 20180707231201-remove-passwords: migrated (0.016s)

== 20180708231200-serviceid-null: migrating =======
== 20180708231200-serviceid-null: migrated (0.010s)

== 20180808061353-cleanup: migrating =======
== 20180808061353-cleanup: migrated (0.025s)

== 20180819054252-disable-sharing: migrating =======
== 20180819054252-disable-sharing: migrated (0.010s)

== 20181031015046-add-subdomain-to-team: migrating =======
== 20181031015046-add-subdomain-to-team: migrated (0.018s)

== 20181124000438-add-notifications: migrating =======
== 20181124000438-add-notifications: migrated (0.023s)

== 20181215192422-document-embeds: migrating =======
== 20181215192422-document-embeds: migrated (0.010s)

== 20181227001547-collection-permissions: migrating =======
== 20181227001547-collection-permissions: migrated (0.012s)

== 20190404035736-add-archive: migrating =======
== 20190404035736-add-archive: migrated (0.009s)

== 20190423051708-add-search-indexes: migrating =======
== 20190423051708-add-search-indexes: migrated (0.020s)

== 20190606035733-events: migrating =======
== 20190606035733-events: migrated (0.029s)

== 20190704070630-welcome-docs: migrating =======
== 20190704070630-welcome-docs: migrated (0.019s)

== 20190706213213-backlinks: migrating =======
== 20190706213213-backlinks: migrated (0.025s)

== 20190811231511-maintainers: migrating =======
== 20190811231511-maintainers: migrated (0.011s)

== 20191118023010-cascade-delete: migrating =======
== 20191118023010-cascade-delete: migrated (0.009s)

== 20191119023010-cascade-backlinks: migrating =======
== 20191119023010-cascade-backlinks: migrated (0.015s)

== 20191119023011-cascade-parent-documents: migrating =======
== 20191119023011-cascade-parent-documents: migrated (0.011s)

== 20191119023012-cascade-shares: migrating =======
== 20191119023012-cascade-shares: migrated (0.014s)

== 20191119023013-cascade-backlinks2: migrating =======
== 20191119023013-cascade-backlinks2: migrated (0.012s)

== 20191121035144-guest-invite: migrating =======
== 20191121035144-guest-invite: migrated (0.016s)

== 20191211044318-create-groups: migrating =======
== 20191211044318-create-groups: migrated (0.026s)

== 20191211044319-create-group-users: migrating =======
== 20191211044319-create-group-users: migrated (0.030s)

== 20191228031525-edit-presence: migrating =======
== 20191228031525-edit-presence: migrated (0.010s)

== 20200104233831-attachments: migrating =======
== 20200104233831-attachments: migrated (0.019s)

== 20200122083721-create-collection-groups: migrating =======
== 20200122083721-create-collection-groups: migrated (0.028s)

== 20200316040755-document-editor-version: migrating =======
== 20200316040755-document-editor-version: migrated (0.011s)

== 20200328175012-cascade-delete: migrating =======
== 20200328175012-cascade-delete: migrated (0.009s)

== 20200330053639-document-version: migrating =======
== 20200330053639-document-version: migrated (0.014s)

== 20200519032353-text-backup: migrating =======
== 20200519032353-text-backup: migrated (0.008s)

== 20200522054958-collection-icon: migrating =======
== 20200522054958-collection-icon: migrated (0.006s)

== 20200723055414-add-published-to-shares: migrating =======
== 20200723055414-add-published-to-shares: migrated (0.007s)

== 20200727051157-add-templates: migrating =======
== 20200727051157-add-templates: migrated (0.009s)

== 20200812170227-remove-collection-type: migrating =======
== 20200812170227-remove-collection-type: migrated (0.007s)

== 20200915010511-create-search-queries: migrating =======
== 20200915010511-create-search-queries: migrated (0.018s)

== 20200926204620-add-missing-indexes: migrating =======
== 20200926204620-add-missing-indexes: migrated (0.013s)

== 20201028043021-reverse-document-id-index: migrating =======
== 20201028043021-reverse-document-id-index: migrated (0.012s)

== 20201103050534-custom-domains: migrating =======
== 20201103050534-custom-domains: migrated (0.011s)

== 20201106122752-i18n: migrating =======
== 20201106122752-i18n: migrated (0.012s)

== 20201206210619-update-attachment-cols: migrating =======
== 20201206210619-update-attachment-cols: migrated (0.008s)

== 20201211080408-attachment-no-cascade: migrating =======
== 20201211080408-attachment-no-cascade: migrated (0.007s)

== 20201230031607-collection-sort: migrating =======
== 20201230031607-collection-sort: migrated (0.007s)

== 20210110143902-collection-rename-creator-id: migrating =======
== 20210110143902-collection-rename-creator-id: migrated (0.020s)

== 20210208062816-disable-collection-sharing: migrating =======
== 20210208062816-disable-collection-sharing: migrated (0.014s)

== 20210218111237-add-collection-index: migrating =======
== 20210218111237-add-collection-index: migrated (0.014s)

== 20210226232041-authentication-providers: migrating =======
== 20210226232041-authentication-providers: migrated (0.033s)

== 20210310051804-passport: migrating =======
== 20210310051804-passport: migrated (0.012s)

== 20210314173941-isViewer: migrating =======
== 20210314173941-isViewer: migrated (0.016s)

== 20210327005406-read-only-collections: migrating =======
== 20210327005406-read-only-collections: migrated (0.015s)

== 20210418053152-share-last-viewed: migrating =======
== 20210418053152-share-last-viewed: migrated (0.015s)

== 20210426055334-nested-document-sharing: migrating =======
== 20210426055334-nested-document-sharing: migrated (0.008s)

== 20210430024222-marketing-tracking: migrating =======
== 20210430024222-marketing-tracking: migrated (0.007s)

== 20210716064654-introduce-previousTitles: migrating =======
== 20210716064654-introduce-previousTitles: migrated (0.008s)

== 20210716071454-search-index-previousTitles: migrating =======
== 20210716071454-search-index-previousTitles: migrated (0.007s)

== 20210716162923-events-indexes: migrating =======
== 20210716162923-events-indexes: migrated (0.009s)

== 20210730042450-remove-unused-indexes: migrating =======
== 20210730042450-remove-unused-indexes: migrated (0.021s)

== 20210730044247-remove-backup-column: migrating =======
== 20210730044247-remove-backup-column: migrated (0.015s)

== 20210730044248-create-realtime: migrating =======
== 20210730044248-create-realtime: migrated (0.012s)

== 20210730210120-add-fileOperations: migrating =======
== 20210730210120-add-fileOperations: migrated (0.044s)

== 20210915051740-collaborative-collections: migrating =======
== 20210915051740-collaborative-collections: migrated (0.008s)

== 20210921031555-missing-cascades: migrating =======
== 20210921031555-missing-cascades: migrated (0.033s)

== 20210923031555-missing-cascades: migrating =======
== 20210923031555-missing-cascades: migrated (0.024s)

== 20211003021903-missing-cascades: migrating =======
== 20211003021903-missing-cascades: migrated (0.013s)

== 20211015170955-add-defaultUserRole: migrating =======
== 20211015170955-add-defaultUserRole: migrated (0.008s)

== 20211107021900-missing-cascades: migrating =======
== 20211107021900-missing-cascades: migrated (0.017s)

== 20211217054419-integration-events: migrating =======
== 20211217054419-integration-events: migrated (0.008s)

== 20211218185045-remove-unused-indexes: migrating =======
== 20211218185045-remove-unused-indexes: migrated (0.011s)

== 20211218193004-documents-full-width: migrating =======
== 20211218193004-documents-full-width: migrated (0.012s)

== 20211221031430-create-pins: migrating =======
== 20211221031430-create-pins: migrated (0.018s)

== 20220117012250-add-starred-sorting: migrating =======
== 20220117012250-add-starred-sorting: migrated (0.008s)

== 20220127000000-index-fixes: migrating =======
== 20220127000000-index-fixes: migrated (0.031s)

== 20220129092607-add-defaultCollectionId: migrating =======
== 20220129092607-add-defaultCollectionId: migrated (0.008s)

== 20220206225006-add-error-to-file-operation: migrating =======
== 20220206225006-add-error-to-file-operation: migrated (0.018s)

== 20220305195830-create-comments: migrating =======
== 20220305195830-create-comments: migrated (0.047s)

== 20220311020825-views-indexes: migrating =======
== 20220311020825-views-indexes: migrated (0.015s)

== 20220319022812-events-indexes: migrating =======
== 20220319022812-events-indexes: migrated (0.007s)

== 20220319060408-collection-create-permission: migrating =======
== 20220319060408-collection-create-permission: migrated (0.009s)

== 20220328215615-add-shareId-to-search-queries: migrating =======
== 20220328215615-add-shareId-to-search-queries: migrated (0.011s)

== 20220402032204-starred-collections: migrating =======
== 20220402032204-starred-collections: migrated (0.026s)

== 20220409222213-user-flags: migrating =======
== 20220409222213-user-flags: migrated (0.009s)

== 20220409225935-user-invited-by: migrating =======
== 20220409225935-user-invited-by: migrated (0.009s)

== 20220413213537-add-inviteRequired-to-teams: migrating =======
== 20220413213537-add-inviteRequired-to-teams: migrated (0.009s)

== 20220419052832-create-team-domains: migrating =======
== 20220419052832-create-team-domains: migrated (0.029s)

== 20220421052253-create-file-operation-format: migrating =======
== 20220421052253-create-file-operation-format: migrated (0.007s)

== 20220430043135-collection-sort-backfill: migrating =======
Backfilling collection sort…
== 20220430043135-collection-sort-backfill: migrated (0.011s)

== 20220521164111-create-webhook-subscription: migrating =======
== 20220521164111-create-webhook-subscription: migrated (0.020s)

== 20220525054603-user-authentication-expires-at: migrating =======
== 20220525054603-user-authentication-expires-at: migrated (0.014s)

== 20220606031139-create-webhook-delivieries: migrating =======
== 20220606031139-create-webhook-delivieries: migrated (0.022s)

== 20220702132722-add-webhooks-deleted-at: migrating =======
== 20220702132722-add-webhooks-deleted-at: migrated (0.021s)

== 20220719121200-create-subscriptions: migrating =======
== 20220719121200-create-subscriptions: migrated (0.016s)

== 20220720221531-remove-deprecated-columns: migrating =======
== 20220720221531-remove-deprecated-columns: migrated (0.015s)

== 20220722184916-remove-event-updatedat: migrating =======
== 20220722184916-remove-event-updatedat: migrated (0.008s)

== 20220810185000-scope-provider-id-uniqueness-to-team: migrating =======
== 20220810185000-scope-provider-id-uniqueness-to-team: migrated (0.014s)

== 20220812115059-scope-user-auth-provider-id-uniqueness-to-user: migrating =======
== 20220812115059-scope-user-auth-provider-id-uniqueness-to-user: migrated (0.010s)

== 20220816070527-change-column-authentication-id-nullable: migrating =======
== 20220816070527-change-column-authentication-id-nullable: migrated (0.008s)

== 20220816175234-user-email-index: migrating =======
== 20220816175234-user-email-index: migrated (0.009s)

== 20220828144837-add-columns-to-notifications-for-tracking: migrating =======
== 20220828144837-add-columns-to-notifications-for-tracking: migrated (0.017s)

== 20220830215146-add-shares-views: migrating =======
== 20220830215146-add-shares-views: migrated (0.008s)

== 20220907132304-user-preferences: migrating =======
== 20220907132304-user-preferences: migrated (0.010s)

== 20220907140227-team-preferences: migrating =======
== 20220907140227-team-preferences: migrated (0.010s)

== 20220909203454-fix-notification-constraints: migrating =======
== 20220909203454-fix-notification-constraints: migrated (0.043s)

== 20220922073737-webhook-signing-secret: migrating =======
== 20220922073737-webhook-signing-secret: migrated (0.008s)

== 20220928030442-fix-avatar-urls: migrating =======
== 20220928030442-fix-avatar-urls: migrated (0.026s)

== 20221111171828-fix-user-constraints: migrating =======
== 20221111171828-fix-user-constraints: migrated (0.014s)

== 20221112152649-import-document-relationship: migrating =======
== 20221112152649-import-document-relationship: migrated (0.036s)

== 20221112162341-attachment-tracking: migrating =======
== 20221112162341-attachment-tracking: migrated (0.013s)

== 20221120151710-attachment-expiry: migrating =======
== 20221120151710-attachment-expiry: migrated (0.022s)

== 20221206163421-add-share-url-slug: migrating =======
== 20221206163421-add-share-url-slug: migrated (0.018s)

== 20221218013627-fix-webhook-subscription-constraints: migrating =======
== 20221218013627-fix-webhook-subscription-constraints: migrated (0.016s)

== 20221219013835-fix-integration-constraints: migrating =======
== 20221219013835-fix-integration-constraints: migrated (0.022s)

== 20221230234256-add-stars-cascade: migrating =======
== 20221230234256-add-stars-cascade: migrated (0.014s)

== 20230101144349-integration-indexes: migrating =======
== 20230101144349-integration-indexes: migrated (0.010s)

== 20230204191035-update-tsvector-trigger: migrating =======
== 20230204191035-update-tsvector-trigger: migrated (0.009s)

== 20230314013103-move-notification-settings: migrating =======
== 20230314013103-move-notification-settings: migrated (0.010s)

== 20230317144617-remove-user-username: migrating =======
== 20230317144617-remove-user-username: migrated (0.008s)

== 20230330181038-remove-column-userId-from-documents: migrating =======
== 20230330181038-remove-column-userId-from-documents: migrated (0.010s)

== 20230403120315-add-comment-to-notifications: migrating =======
== 20230403120315-add-comment-to-notifications: migrated (0.014s)

== 20230419124305-add-archivedat-col-to-notifications: migrating =======
== 20230419124305-add-archivedat-col-to-notifications: migrated (0.018s)

== 20230419132159-add-indexes-to-notifications: migrating =======
== 20230419132159-add-indexes-to-notifications: migrated (0.023s)

== 20230429005039-collection-admins: migrating =======
== 20230429005039-collection-admins: migrated (0.013s)

== 20230430213332-remove-notification-settings: migrating =======
== 20230430213332-remove-notification-settings: migrated (0.014s)

== 20230621004649-add-include-attachments-file-operation: migrating =======
== 20230621004649-add-include-attachments-file-operation: migrated (0.011s)

== 20230720002422-add-insights-control: migrating =======
== 20230720002422-add-insights-control: migrated (0.010s)

== 20230723231806-fix-file-operation-constraints: migrating =======
== 20230723231806-fix-file-operation-constraints: migrated (0.019s)

== 20230815063830-add-emoji-to-revisions: migrating =======
== 20230815063830-add-emoji-to-revisions: migrated (0.011s)

== 20230815063834-migrate-emoji-in-document-title: migrating =======
Backfill document emoji from title… page 0
(node:62) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (/app/code/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/code/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.select (/app/code/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async document.findAll (/app/code/node_modules/sequelize/lib/model.js:1140:21)
    at async /app/code/build/server/scripts/20230815063834-migrate-emoji-in-document-title.js:20:19
    at async /app/code/node_modules/sequelize/lib/sequelize.js:507:18
    at async work (/app/code/build/server/scripts/20230815063834-migrate-emoji-in-document-title.js:19:5)
    at async main (/app/code/build/server/scripts/20230815063834-migrate-emoji-in-document-title.js:61:3) {
  name: 'SequelizeDatabaseError',
  parent: error: column "sourceMetadata" does not exist
      at Parser.parseErrorMessage (/app/code/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/code/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/code/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/code/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:517:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:335:12)
      at readableAddChunk (node:internal/streams/readable:308:9)
      at Readable.push (node:internal/streams/readable:245:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 115,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '229',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3638',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "urlId", "title", "previousTitles", "version", "template", "fullWidth", "insightsEnabled", "editorVersion", "emoji", "text", "isWelcome", "revisionCount", "archivedAt", "publishedAt", "collaboratorIds", "importId", "sourceMetadata", "parentDocumentId", "lastModifiedById", "createdById", "templateId", "teamId", "collectionId", "createdAt", "updatedAt", "deletedAt" FROM "documents" AS "document" WHERE "document"."version" IS NOT NULL ORDER BY "document"."createdAt" ASC LIMIT 1000 OFFSET 0 FOR UPDATE;',
    parameters: undefined
  },
  original: error: column "sourceMetadata" does not exist
      at Parser.parseErrorMessage (/app/code/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/code/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/code/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/code/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:517:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:335:12)
      at readableAddChunk (node:internal/streams/readable:308:9)
      at Readable.push (node:internal/streams/readable:245:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 115,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '229',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3638',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "urlId", "title", "previousTitles", "version", "template", "fullWidth", "insightsEnabled", "editorVersion", "emoji", "text", "isWelcome", "revisionCount", "archivedAt", "publishedAt", "collaboratorIds", "importId", "sourceMetadata", "parentDocumentId", "lastModifiedById", "createdById", "templateId", "teamId", "collectionId", "createdAt", "updatedAt", "deletedAt" FROM "documents" AS "document" WHERE "document"."version" IS NOT NULL ORDER BY "document"."createdAt" ASC LIMIT 1000 OFFSET 0 FOR UPDATE;',
    parameters: undefined
  },
  sql: 'SELECT "id", "urlId", "title", "previousTitles", "version", "template", "fullWidth", "insightsEnabled", "editorVersion", "emoji", "text", "isWelcome", "revisionCount", "archivedAt", "publishedAt", "collaboratorIds", "importId", "sourceMetadata", "parentDocumentId", "lastModifiedById", "createdById", "templateId", "teamId", "collectionId", "createdAt", "updatedAt", "deletedAt" FROM "documents" AS "document" WHERE "document"."version" IS NOT NULL ORDER BY "document"."createdAt" ASC LIMIT 1000 OFFSET 0 FOR UPDATE;',
  parameters: {}
}

Node.js v18.18.0

ERROR: Command failed: node /app/code/build/server/scripts/20230815063834-migrate-emoji-in-document-title.js

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Initial migration should work

**Outline (please complete the following information):**
- Install: This is Outline on Cloudron . I am the maintainer of the package.
- Version: 0.73.0 release

**Comment by gramakri** [comment]
The error here is because the latest release 0.73.0 added the new column `sourceMetadata` in the documents table - `20231111023920-add-source-metadata.js` . However, an earlier migration script `20230815063834-migrate-emoji-in-document-title` sources the `20230815063834-migrate-emoji-in-document-title.ts` script which in turn has `import { Document } from "@server/models";` that already has the `sourceMetadata` field in the code. As a result, the SQL generated is incorrect since the `20231111023920-add-source-metadata.js` is not yet run.

**Comment by wangweitung** [comment]
https://github.com/outline/outline/discussions/6151#discussion-5848923
Is this the same error?

**Comment by gramakri** [comment]
@wangweitung it's not , no.

**Comment by tommoor** [comment]
In the meantime, you can install `0.72.2` and then immediately install `0.73.0` as a workaround

**Comment by pingiun** [comment]
I manually added the failing migrations in the SequelizeMeta table for my new install. Is this a sound fix?

**Comment by QYG2297248353** [comment]
```
outline-ms  | yarn run v1.22.22
outline-ms  | $ node ./build/server/index.js
outline-ms  | {"label":"database","level":"info","message":"Running migrations…"}
outline-ms  | {"label":"database","level":"info","message":"Migrating 20160619080644-initial.js…"}
outline-ms  | {"label":"database","level":"info","message":"Migrated 20160619080644-initial.js in 0.02s"}
outline-ms  | {"label":"database","level":"info","message":"Migrating 20160622043741-add-parent-document.js…"}
outline-ms  | {"label":"database","level":"info","message":"Migrated 20160622043741-add-parent-document.js in 0.003s"}
outline-ms  | {"label":"database","level":"info","message":"Migrating 20160626063409-add-indexes.js…"}
outline-ms  | {"label":"database","level":"info","message":"Migrated 20160626063409-add-indexes.js in 0.017s"}
outline-ms  | {"label":"database","level":"info","message":"Migrating 20160626175224-add-revisions.js…"}
outline-ms  | {"label":"database","level":"info","message":"Migrated 20160626175224-add-revisions.js in 0.006s"}
outline-ms  | {"label":"database","level":"info","message":"Migrating 20160711071958-search-index.js…"}
outline-ms  | {"level":"warn","message":"Migration 20160711071958-search-index.js (up) failed: Original error: function \"documents_search_trigger\" already exists with same argument types"}
outline-ms  | error Command failed with exit code 1.
outline-ms  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline-ms exited with code 0
```

I think I'm experiencing a similar error
