### ISSUE TITLE
Outline is broken after migrate from 0.72.1 to 0.73.1

### ISSUE THREAD

**Issue by arnolem** [outline/outline#6171]
Bug after migrate from 0.72.1 to 0.73.1. All page display this error : 
`TypeError: Cannot read properties of null (reading 'href')` on Edge
`TypeError: e is null` on Firefox

**Expected behavior**

![image](https://github.com/outline/outline/assets/2263103/897ae9ca-eb9d-4f80-8d96-943b43ec6a33)

![image](https://github.com/outline/outline/assets/2263103/f4d1e00f-337c-4e66-b174-fc9935bc1760)

**Outline (please complete the following information):**
- Install: self hosted
- Version: https://github.com/outline/outline/commit/2c870f0dbbad072b70f0fa9941f0f227e47c33f1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge 120 / Firefox 119

**Comment by arnolem** [comment]
Firefox Console logs : 
```
Content-Security-Policy : Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). content-script.js:106:46
SyntaxError: export declarations may only appear at top level of a module common.js:2:1
GET
https://minio.docs.wixiweb.net/outline-data/avatars/f79c875b-0c54-41d1-b7c6-f77d9df1b249/635f9058-9e43-461d-b96b-c674821860cb

GET
https://minio.docs.wixiweb.net/outline-data/avatars/d2c0ad7e-5279-407d-b89a-bb5a5f3dd358/d4227dd6-839b-403a-9bfe-c9a04e17912a

TypeError: e is null
    HoverPreview HoverPreview.tsx:131
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    MobX 6
    fetchPage Store.ts:258
    MobX 2
    fetchEmbedIntegrations useEmbeds.ts:22
    f useEmbeds.ts:32
    fk React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    MobX 7
    fetchResults PaginatedList.tsx:119
    MobX 2
    componentDidMount PaginatedList.tsx:73
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    V2 scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    EventHandlerNonNull* scheduler.production.min.js:12
    <anonymous> scheduler.production.min.js:20
react-dom.production.min.js:216:199
ErrorBoundary 
Object { error: TypeError, extra: undefined }
Logger.ts:80:12
Uncaught TypeError: this.docView is null
    updateStateInner index.js:5197
    updateState index.js:5170
    dispatchTransaction index.tsx:465
    dispatch index.js:5506
    _forceRerender sync-plugin.js:301
    mux mutex.js:35
    _forceRerender sync-plugin.js:297
    r sync-plugin.js:142
    setTimeout handler*timeout eventloop.js:59
    view sync-plugin.js:141
    updatePluginViews index.js:5283
    EditorView index.js:5115
    createView index.tsx:448
    init index.tsx:299
    componentDidMount index.tsx:211
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    MobX 6
    fetchPage Store.ts:258
    MobX 2
    fetchEmbedIntegrations useEmbeds.ts:22
    f useEmbeds.ts:32
    fk React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    MobX 7
    fetchResults PaginatedList.tsx:119
    MobX 2
    componentDidMount PaginatedList.tsx:73
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    V2 scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    EventHandlerNonNull* scheduler.production.min.js:12
    <anonymous> scheduler.production.min.js:20
index.js:5197:35

```

Edge Console logs : 

```
react-dom.production.min.js:216  TypeError: Cannot read properties of null (reading 'href')
    at HoverPreview (HoverPreview.tsx:131:29)
    at Ch (react-dom.production.min.js:157:137)
    at Bo (react-dom.production.min.js:267:460)
    at bk (react-dom.production.min.js:250:347)
    at ak (react-dom.production.min.js:250:278)
    at Tj (react-dom.production.min.js:250:128)
    at Lj (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at gg (react-dom.production.min.js:122:325)
Ni @ react-dom.production.min.js:216
Si.a.componentDidCatch.n.callback @ react-dom.production.min.js:217
Eg @ react-dom.production.min.js:131
Yi @ react-dom.production.min.js:220
dk @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Uj @ react-dom.production.min.js:252
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
lt @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
Show 19 more frames
Show less
Logger.ts:80  ErrorBoundary {error: TypeError: Cannot read properties of null (reading 'href')
    at HoverPreview (https://docs.wixiwe…, extra: undefined}
error @ Logger.ts:80
componentDidCatch @ ErrorBoundary.tsx:48
Si.a.componentDidCatch.n.callback @ react-dom.production.min.js:217
Eg @ react-dom.production.min.js:131
Yi @ react-dom.production.min.js:220
dk @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Uj @ react-dom.production.min.js:252
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
lt @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
Show 18 more frames
Show less
react-dom.production.min.js:216  TypeError: Cannot read properties of null (reading 'href')
    at HoverPreview (HoverPreview.tsx:131:29)
    at Ch (react-dom.production.min.js:157:137)
    at Bo (react-dom.production.min.js:267:460)
    at bk (react-dom.production.min.js:250:347)
    at ak (react-dom.production.min.js:250:278)
    at Tj (react-dom.production.min.js:250:128)
    at Lj (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at gg (react-dom.production.min.js:122:325)
Ni @ react-dom.production.min.js:216
Si.a.componentDidCatch.n.callback @ react-dom.production.min.js:217
Eg @ react-dom.production.min.js:131
Yi @ react-dom.production.min.js:220
dk @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Uj @ react-dom.production.min.js:252
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
lt @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
Show 19 more frames
Show less
Logger.ts:80  ErrorBoundary {error: TypeError: Cannot read properties of null (reading 'href')
    at HoverPreview (https://docs.wixiwe…, extra: undefined}
error @ Logger.ts:80
componentDidCatch @ ErrorBoundary.tsx:48
Si.a.componentDidCatch.n.callback @ react-dom.production.min.js:217
Eg @ react-dom.production.min.js:131
Yi @ react-dom.production.min.js:220
dk @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Uj @ react-dom.production.min.js:252
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
lt @ react-dom.production.min.js:292
Nb @ react-dom.production.min.js:50
jd @ react-dom.production.min.js:105
yc @ react-dom.production.min.js:75
hd @ react-dom.production.min.js:74
Show 18 more frames
Show less

```

**Comment by tommoor** [comment]
Are you able to pause on the error and see what exactly it's trying to read? The error says `href` of `null`, but there is no code that tries to read a property called `href` in `HoverPreview` so that's very odd.

**Comment by clementthenard** [comment]
Hi,

I fixed it. In `HoverPreview` file (line 131) I added check if `element` is `null` like this :

```
// previews only work for internal doc links for now
if (element === null || isExternalUrl(element.href)) {
    return null;
}
```

**Comment by tommoor** [comment]
This somewhat confirms my hypothesis as the code you're referring to doesn't exist:

https://github.com/outline/outline/blob/v0.73.1/app/components/HoverPreview/HoverPreview.tsx#L131

In fact `isExternalUrl` doesn't appear in that entire file, so you have some sort of caching issue, or the code you're running is a different version to what you think.
