### ISSUE TITLE
Print does not include image

### ISSUE THREAD

**Issue by PovilasID** [outline/outline#6538]
If you include an image in your document and select a print option the document is blank on chrome
**To Reproduce**

1. Go to 'New document'
2. Click on 'plus and upload an image'
3. Click 'on drop down in top right and select 'Print' '

**Expected behavior**
For the print preview to not be empty

**Outline (please complete the following information):**

* Install: self hosted
* Version: v0.75.0

**Desktop (please complete the following information):**

* OS: Windows 11
* Browser Chrome
* Version 121.0.6167.161

Console log:

```
manifest.webmanifest:1 Manifest: property 'scope' ignored. Start url should be within scope of scope URL.
index.js:221 TextSelection endpoint not pointing into a node with inline content (doc)
checkTextSelection @ index.js:221
Show 1 more frame
Show less
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
index.js:5197 Uncaught TypeError: Cannot read properties of null (reading 'matchesNode')
    at EditorView.updateStateInner (index.js:5197:49)
    at EditorView.updateState (index.js:5170:14)
    at EditorView.dispatchTransaction (index.tsx:465:14)
    at EditorView.dispatch (index.js:5506:33)
    at sync-plugin.js:301:28
    at ProsemirrorBinding.mux (mutex.js:35:12)
    at ProsemirrorBinding._forceRerender (sync-plugin.js:297:10)
    at sync-plugin.js:142:17
index.js:5197 Uncaught TypeError: Cannot read properties of null (reading 'matchesNode')
    at EditorView.updateStateInner (index.js:5197:49)
    at EditorView.updateState (index.js:5170:14)
    at EditorView.dispatchTransaction (index.tsx:465:14)
    at EditorView.dispatch (index.js:5506:33)
    at sync-plugin.js:301:28
    at ProsemirrorBinding.mux (mutex.js:35:12)
    at ProsemirrorBinding._forceRerender (sync-plugin.js:297:10)
    at sync-plugin.js:142:17
index.js:5197 Uncaught TypeError: Cannot read properties of null (reading 'matchesNode')
    at EditorView.updateStateInner (index.js:5197:49)
    at EditorView.updateState (index.js:5170:14)
    at EditorView.dispatchTransaction (index.tsx:465:14)
    at EditorView.dispatch (index.js:5506:33)
    at sync-plugin.js:301:28
    at ProsemirrorBinding.mux (mutex.js:35:12)
    at ProsemirrorBinding._forceRerender (sync-plugin.js:297:10)
    at sync-plugin.js:142:17
index.js:5197 Uncaught TypeError: Cannot read properties of null (reading 'matchesNode')
    at EditorView.updateStateInner (index.js:5197:49)
    at EditorView.updateState (index.js:5170:14)
    at EditorView.dispatchTransaction (index.tsx:465:14)
    at EditorView.dispatch (index.js:5506:33)
    at sync-plugin.js:301:28
    at ProsemirrorBinding.mux (mutex.js:35:12)
    at ProsemirrorBinding._forceRerender (sync-plugin.js:297:10)
    at sync-plugin.js:142:17
updateStateInner @ index.js:5197
updateState @ index.js:5170
dispatchTransaction @ index.tsx:465
dispatch @ index.js:5506
(anonymous) @ sync-plugin.js:301
(anonymous) @ mutex.js:35
_forceRerender @ sync-plugin.js:297
(anonymous) @ sync-plugin.js:142
setTimeout (async)
timeout @ eventloop.js:59
view @ sync-plugin.js:141
updatePluginViews @ index.js:5283
EditorView @ index.js:5115
createView @ index.tsx:448
init @ index.tsx:299
componentDidMount @ index.tsx:211
Yi @ react-dom.production.min.js:219
dk @ react-dom.production.min.js:259
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
Uj @ react-dom.production.min.js:252
Lj @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:18
gg @ react-dom.production.min.js:122
jg @ react-dom.production.min.js:123
ig @ react-dom.production.min.js:122
Jg @ react-dom.production.min.js:237
Oh @ react-dom.production.min.js:170
listener @ useMediaQuery.ts:13
Show 24 more frames
Show less
```

**Comment by tommoor** [comment]
I am not able to reproduce this issue, are you sure the image is uploaded and not stuck in the uploading state? You have a lot of errors there…

**Comment by tommoor** [comment]
This seems like a Chrome bug of some sort in that case, I tested in all three browsers without issue

**Comment by whuwangyong** [comment]
When I use Chrome version 126 save as PDF does not contain Images, but when I use Chromium version 94, it works.
