### ISSUE TITLE
Video uploads are not displaying in Safari 17.5 on Mac OS Sonoma 14.5.

### ISSUE THREAD

**Issue by bizfreak22** [outline/outline#6949]
As stated in the title, video uploads are not displaying in Safari yet no issues in Chrome. After uploading, the video appears with the crossed out play button. See screenshot below:

![CleanShot 2024-05-26 at 19 31 16@2x](https://github.com/outline/outline/assets/33889841/4086f2aa-0b82-41b5-9010-074c3bd9d877)

/api/files.get seems to error out in safari but not in chrome

![CleanShot 2024-05-26 at 19 31 47@2x](https://github.com/outline/outline/assets/33889841/f6279103-8622-47ef-b376-fd6b7885dcba)

**Comment by tommoor** [comment]
Seems Safari requests part of the file whereas chrome doesn't. Relatively easy fix to pass this through to the underlying file reader

**Comment by bizfreak22** [comment]
Hey it seems like its broken again. Updated to [v0.77.2] - Video upload on Safari just hangs, nothing happens.. Tried uploading the same video on Chrome, worked instantly. Safari is also not displaying any videos - when I hit play, developer tools shows this:

![CleanShot 2024-07-03 at 16 11 13@2x](https://github.com/outline/outline/assets/33889841/55150652-bb98-4c8a-9df7-7c952dac22fd)

**Comment by tommoor** [comment]
Everything seems okay here, please provide as much information as possible on the failed requests. Also are there server-side errors?

**Comment by bizfreak22** [comment]
> Everything seems okay here, please provide as much information as possible on the failed requests. Also are there server-side errors?

The only error I see when running docker-compose logs outline is this:

TypeError: a non-empty url is required
    at parseDomain (/opt/outline/build/shared/utils/domains.js:46:11)
    at shareDomainsMiddleware (/opt/outline/build/server/middlewares/shareDomains.js:14:53)
    at /opt/outline/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57
    at shareDomainsMiddleware (/opt/outline/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21)
    at dispatch (/opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /opt/outline/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at compressMiddleware (/opt/outline/node_modules/koa-compress/lib/index.js:56:11)
    at /opt/outline/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57
    at compressMiddleware (/opt/outline/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21)
    at dispatch (/opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /opt/outline/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /opt/outline/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/opt/outline/node_modules/koa-router/lib/router.js:351:31)
    at /opt/outline/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57
    at dispatch (/opt/outline/node_modules/koa-compose/index.js:42:32)
    at apexRedirectMiddleware (/opt/outline/build/server/middlewares/apexRedirect.js:12:14)
    at /opt/outline/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57

-- 

Checked logs in the docker directory - only see this:

![CleanShot 2024-07-03 at 16 36 11@2x](https://github.com/outline/outline/assets/33889841/f746f5c8-b590-4e66-a48c-1e41cbb9f2bf)

Also checked redis/postgres logs - nothing out of the ordinary there..

**Comment by tommoor** [comment]
`TypeError: a non-empty url is required`

Can you tell which request this error is associated with?

**Comment by bizfreak22** [comment]
> `TypeError: a non-empty url is required`
> 
> Can you tell which request this error is associated with?

Ah, sorry, fairly certain this error is not associated with uploading the video or pressing play button.. it looks to have popped up when I updated to the new version and it was rebuilding:

![CleanShot 2024-07-03 at 16 56 55@2x](https://github.com/outline/outline/assets/33889841/73a80ade-46b4-4434-b671-b6595c9eec1a)

**Comment by tommoor** [comment]
Ah, then I don't know I would double check you actually have the new code from the PR and it's deployed correctly as that's the most likely issue rn
