### ISSUE TITLE
Error: Cannot find module './../../../app/components/EventBoundary' on 0.77.0 & 0.77.1-2

### ISSUE THREAD

**Issue by beastarman74** [outline/outline#7041]
When attempting to update to v0.77.0, Outline fails to start throwing an error regarding EventBoundary module.  Outline does not recover and the container is stops.  

**To Reproduce**
1. Update Docker Compose to pull image 0.77.0. Also tried 0.77.1-2 as thought it might be associated with the ARM architecture issues
2. Bring up the Outline containers (outline, redis, postgres etc)
3. Check the logs, the error appears after a few seconds, then gets into a container restarting loop where the same error reoccurs. Outline fails to start successfully and is inaccessible.
4. This has been tried on a Raspberry Pi 8 (the usual host Outline runs on) and an AMD64 based host (moved it over to see if it was related to the current issues with 0.77.0 and ARM based architectures. The same issue occurred on both.
5. Also tried this with a fresh database in case it was an issue with my database for some reason.  Deleted the current database. Created a stub Postgres database and recreated the container and the same issue remained.
6. See error below

```
Gyarn run v1.22.22
G$ node ./build/server/index.js --env=production-ssl-disabled
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module './../../../app/components/EventBoundary'
Require stack:
- /opt/outline/build/shared/editor/components/ImageZoom.js
- /opt/outline/build/shared/editor/embeds/InVision.js
- /opt/outline/build/shared/editor/embeds/index.js
- /opt/outline/build/shared/editor/nodes/Embed.js
- /opt/outline/build/shared/editor/nodes/index.js
- /opt/outline/build/server/editor/index.js
- /opt/outline/build/server/models/helpers/DocumentHelper.js
- /opt/outline/build/server/models/Collection.js
- /opt/outline/build/server/models/Document.js
- /opt/outline/build/server/models/Attachment.js
- /opt/outline/build/server/models/User.js
- /opt/outline/build/server/models/ApiKey.js
- /opt/outline/build/server/models/index.js
- /opt/outline/build/server/collaboration/ViewsExtension.js
- /opt/outline/build/server/services/collaboration.js
- /opt/outline/build/server/services/index.js
- /opt/outline/build/server/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:54:29)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/outline/build/shared/editor/components/ImageZoom.js:10:45)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/outline/build/shared/editor/embeds/InVision.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/outline/build/shared/editor/components/ImageZoom.js',
    '/opt/outline/build/shared/editor/embeds/InVision.js',
    '/opt/outline/build/shared/editor/embeds/index.js',
    '/opt/outline/build/shared/editor/nodes/Embed.js',
    '/opt/outline/build/shared/editor/nodes/index.js',
    '/opt/outline/build/server/editor/index.js',
    '/opt/outline/build/server/models/helpers/DocumentHelper.js',
    '/opt/outline/build/server/models/Collection.js',
    '/opt/outline/build/server/models/Document.js',
    '/opt/outline/build/server/models/Attachment.js',
    '/opt/outline/build/server/models/User.js',
    '/opt/outline/build/server/models/ApiKey.js',
    '/opt/outline/build/server/models/index.js',
    '/opt/outline/build/server/collaboration/ViewsExtension.js',
    '/opt/outline/build/server/services/collaboration.js',
    '/opt/outline/build/server/services/index.js',
    '/opt/outline/build/server/index.js'
  ]
}

Node.js v20.14.0
Gerror Command failed with exit code 1.
Ginfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Container stopped
```

**Expected behavior**
Outline starts correctly as is accessible running on a ARM based Raspberry Pi or AMD64 based host.

**Screenshots**
Screenshot the error can be provided of the error if the code capture above is not sufficient.  Omitted due to the size of the image to capture the length of the log.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.77.0 & 0.77.1-2

**Comment by tommoor** [comment]
This is not an issue in `0.77.0` for sure, the code in question was merged to `main` after that release was cut.

Follow along existing discussion in https://github.com/outline/outline/issues/7033 – `v0.77.0` or `v0.77.1-3` will work fine (if on ARM)

**Comment by beastarman74** [comment]
Thanks Tom,

Sorry if I have wasted your time with this one. Trying 0.77.1-3 now.
Thanks.
