### ISSUE TITLE
Import Failure After Exporting Data with Media Files (jpg, png, mp4) in Getoutline System

### ISSUE THREAD

**Issue by drsaluml** [outline/outline#7755]
When creating and working with data that contains media files such as jpg, png, and mp4, the system functions properly. However, after exporting the data and attempting to import it back into the getoutline system, the import process fails, even though the data was originally generated within the same getoutline environment.

**Comment by tommoor** [comment]
Please follow the bug template and provide error logs otherwise the issue will be closed due to lack of information – thanks

**Comment by drsaluml** [comment]
Some logs cannot be disclosed to the public.

file: 740fa881-fd69-4c58-b289-75829daa0ab2 It is very small.

`{"error":"The document \"740fa881-fd69-4c58-b289-75829daa0ab2\" is too large to import, please reduce the length and try again","level":"error","message":"Error processing task in ImportMarkdownZipTask","stack":"BadRequestError: The document \"740fa881-fd69-4c58-b289-75829daa0ab2\" is too large to import, please reduce the length and try again\n    at InvalidRequestError (/opt/outline/build/server/errors.js:99:34)\n    at documentImporter (/opt/outline/build/server/commands/documentImporter.js:56:43)"}`

My computer cannot upload files due to security restrictions within the organization.

**Comment by drsaluml** [comment]
You can test it yourself by uploading a PNG or MP4 file, then export and import it afterward.

**Comment by tommoor** [comment]
Please provide the information in the bug template, and let me know which import/export methods you're using
