### ISSUE TITLE
Cannot login via Slack or Google

### ISSUE THREAD

**Issue by lmquang** [outline/outline#874]
Hi,

I've followed the document which guides how to build and run locally (by `yarn dev` and `docker-compose` also) and seft hosted as well, but after I run the app on, I tried to login and i always received `Internal server error` like these messages from terminal:

```
outline_1   |   xxx GET /auth/slack.callback?code=261592188464.528556808820.35b9adb5cdcb420f086c8e60a708f4d5a4fb9523ebb9ce4117c2f742c890cba6&state=r26bjc 500 1,961ms -
outline_1   |
outline_1   |   AccessDenied: Access Denied
outline_1   |       at Request.extractError (/opt/outline/node_modules/aws-sdk/lib/services/s3.js:577:35)
outline_1   |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:683:14)
outline_1   |       at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
outline_1   |       at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
outline_1   |       at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:685:12)
outline_1   |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:683:14)
outline_1   |       at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
outline_1   |       at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
outline_1   |       at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:685:12)
outline_1   |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
outline_1   |       at callNextListener (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
outline_1   |       at IncomingMessage.onEnd (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:269:13)
outline_1   |       at emitNone (events.js:111:20)
outline_1   |       at IncomingMessage.emit (events.js:208:7)
outline_1   |       at endReadableNT (_stream_readable.js:1064:12)
outline_1   |       at _combinedTickCallback (internal/process/next_tick.js:138:11)
outline_1   |       at process._tickDomainCallback (internal/process/next_tick.js:218:9)
outline_1   |   From previous event:
outline_1   |       at Promise.each.hook (/opt/outline/node_modules/sequelize/lib/hooks.js:130:22)
outline_1   |   From previous event:
outline_1   |       at Function.runHooks (/opt/outline/node_modules/sequelize/lib/hooks.js:124:20)
outline_1   |       at Promise.try.then (/opt/outline/node_modules/sequelize/lib/model.js:3531:33)
```

Does anyone can help me to overcome this issue?

Thanks.

**Comment by tommoor** [comment]
Looks like you’re missing the AWS credentials

**Comment by lmquang** [comment]
hi @tommoor , thanks for your suggestion, I've solved
