### ISSUE TITLE
Error when logging with slack

### ISSUE THREAD

**Issue by diegogarrido** [outline/outline#876]
When I try to log in with any slack account throws this error and returns Internal Server Error
```
outline_1   |   XMLParserError: Unexpected close tag
outline_1   |   Line: 11
outline_1   |   Column: 9
outline_1   |   Char: >
outline_1   |       at error (/opt/outline/node_modules/sax/lib/sax.js:651:10)
outline_1   |       at strictFail (/opt/outline/node_modules/sax/lib/sax.js:677:7)
outline_1   |       at closeTag (/opt/outline/node_modules/sax/lib/sax.js:871:9)
outline_1   |       at SAXParser.write (/opt/outline/node_modules/sax/lib/sax.js:1436:13)
outline_1   |       at Parser.exports.Parser.Parser.parseString (/opt/outline/node_modules/xml2js/lib/xml2js.js:508:31)
outline_1   |       at Parser.parseString (/opt/outline/node_modules/xml2js/lib/xml2js.js:7:59)
outline_1   |       at NodeXmlParser.parse (/opt/outline/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
outline_1   |       at Request.extractError (/opt/outline/node_modules/aws-sdk/lib/services/s3.js:563:39)
outline_1   |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:683:14)
outline_1   |       at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
outline_1   |       at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
outline_1   |       at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:685:12)
outline_1   |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
outline_1   |       at Request.emit (/opt/outline/node_modules/aws-sdk/lib/request.js:683:14)
outline_1   |       at Request.transition (/opt/outline/node_modules/aws-sdk/lib/request.js:22:10)
outline_1   |       at AcceptorStateMachine.runTo (/opt/outline/node_modules/aws-sdk/lib/state_machine.js:14:12)
outline_1   |       at /opt/outline/node_modules/aws-sdk/lib/state_machine.js:26:10
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:38:9)
outline_1   |       at Request.<anonymous> (/opt/outline/node_modules/aws-sdk/lib/request.js:685:12)
outline_1   |       at Request.callListeners (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
outline_1   |       at callNextListener (/opt/outline/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
outline_1   |       at IncomingMessage.onEnd (/opt/outline/node_modules/aws-sdk/lib/event_listeners.js:269:13)
outline_1   |       at emitNone (events.js:111:20)
outline_1   |       at IncomingMessage.emit (events.js:208:7)
outline_1   |       at endReadableNT (_stream_readable.js:1064:12)
outline_1   |       at _combinedTickCallback (internal/process/next_tick.js:138:11)
outline_1   |       at process._tickDomainCallback (internal/process/next_tick.js:218:9)
outline_1   |   From previous event:
outline_1   |       at Promise.each.hook (/opt/outline/node_modules/sequelize/lib/hooks.js:130:22)
outline_1   |   From previous event:
outline_1   |       at Function.runHooks (/opt/outline/node_modules/sequelize/lib/hooks.js:124:20)
outline_1   |       at Promise.try.then (/opt/outline/node_modules/sequelize/lib/model.js:3531:33)
outline_1   |   From previous event:
outline_1   |       at model.save (/opt/outline/node_modules/sequelize/lib/model.js:3519:8)
outline_1   |       at Function.create (/opt/outline/node_modules/sequelize/lib/model.js:1998:8)
outline_1   |       at sequelize.transaction.then.then.instance (/opt/outline/node_modules/sequelize/lib/model.js:2096:19)
outline_1   |       at runCallback (timers.js:810:20)
outline_1   |       at tryOnImmediate (timers.js:768:5)
outline_1   |       at processImmediate [as _immediateCallback] (timers.js:745:5)
outline_1   |   From previous event:
outline_1   |       at Function.findOrCreate (/opt/outline/node_modules/sequelize/lib/model.js:2084:8)
outline_1   |       at _callee2$ (/opt/outline/server/auth/slack.js:49:44)
outline_1   |       at tryCatch (/opt/outline/node_modules/regenerator-runtime/runtime.js:65:40)
outline_1   |       at Generator.invoke [as _invoke] (/opt/outline/node_modules/regenerator-runtime/runtime.js:303:22)
outline_1   |       at Generator.prototype.(anonymous function) [as next] (/opt/outline/node_modules/regenerator-runtime/runtime.js:117:21)
outline_1   |       at step (/opt/outline/server/auth/slack.js:35:191)
outline_1   |       at /opt/outline/server/auth/slack.js:35:361
outline_1   |       at <anonymous>
```

**Comment by tommoor** [comment]
It looks like there's probably something wrong with your AWS credentials. Please refer to the Spectrum community for self hosted support –https://spectrum.chat/outline
