### ISSUE TITLE
Allow login with a personal gmail account

### ISSUE THREAD

**Issue by brpaz** [outline/outline#883]
Hello. 
First of all, congrats for the amazing work with outline ;)

I would like to experiment outline for my personal knowledge base but when I try to login using my Google account, it gives an error saying I must login with a company account.

**Comment by pfista** [comment]
Hey @brpaz, if you're running Outline yourself it's easy to change the code to allow this.

Here's an example below of what you could change to allow Gmail accounts:

```
--- a/server/auth/google.js
+++ b/server/auth/google.js
@@ -39,10 +39,12 @@ router.get('google.callback', auth({ required: false }), async ctx => {
     url: 'https://www.googleapis.com/oauth2/v1/userinfo',
   });

-  if (!profile.data.hd) {
-    ctx.redirect('/?notice=google-hd');
+  // Hack to allow Gmail (non GSuite) accounts
+  if (!profile.data.hd) {
+    // ctx.redirect('/?notice=outsider');
      // return;
   }
+  profile.data.hd = "teamname.com"
```

**Comment by andermurias** [comment]
I've done a small modification with similar goals, in order to achieve two things, first one, to be able to login with an gmail email, but only with a list of allowed emails and second one, to allow all the users be in the same team.

This is not a perfect solution, but worked for me and may be usefull for more people

In `.env`:
```
TEAM_ID=TEAMID
GOOGLE_ALLOWED_EMAILS=allowed.email@gmail.com,allowed.email2@gmail.com
```

in `server/auth/google.js`:
```javascript

  const profile = await client.request({
    url: 'https://www.googleapis.com/oauth2/v1/userinfo',
  });

  // EDIT START (ARROUND LINE 42)
  const allowedEmails = allowedEmailsEnv && allowedEmailsEnv.split(',');

  if (!profile.data.hd) {
  	  if (allowedEmails && !allowedEmails.includes(profile.data.email)) {
    	ctx.redirect('/?notice=google-hd');
    	return;
  	  }
  }

  // allow all domains by default if the env is not set
  const allowedDomains = allowedDomainsEnv && allowedDomainsEnv.split(',');
  if (allowedDomains && !allowedDomains.includes(profile.data.hd) && allowedEmails && !allowedEmails.includes(profile.data.email)) {
    ctx.redirect('/?notice=hd-not-allowed');
    return;
  }

  let googleId = process.env.TEAM_ID;
  if(!googleId) {
    const googleId = profile.data.hd;
  }

  const hostname = googleId.split('.')[0];
  const teamName = capitalize(hostname);

  // EDIT END
```

**Comment by tommoor** [comment]
Thanks @andermurias – I hope this can be useful for folks 😄 

I'm currently working on separating out some of the code that's more specific for the hosted version which should allow us to folks the open source project on a single-team experience in the long run

**Comment by typkrft** [comment]
Could you explain a little about how you allowed just specific @gmail.com addresses?

You have GOOGLE_ALLOWED_EMAILS=allowed.email@gmail.com,allowed.email2@gmail.com in the .env file, but I dont see where you referenced the env variable in the google.js. Is there anything else you changed?

**Comment by andermurias** [comment]
> Could you explain a little about how you allowed just specific @gmail.com addresses?
> 
> You have GOOGLE_ALLOWED_EMAILS=[allowed.email@gmail.com](mailto:allowed.email@gmail.com),[allowed.email2@gmail.com](mailto:allowed.email2@gmail.com) in the .env file, but I dont see where you referenced the env variable in the google.js. Is there anything else you changed?

My bad, i've updated the code in the comment above, the var is assigned from the process.env, if I have some time later I'll try to check everything is fine.

```javascript
// Around line 14-15
const allowedDomainsEnv = process.env.GOOGLE_ALLOWED_DOMAINS;
const allowedEmailsEnv = process.env.GOOGLE_ALLOWED_EMAILS;
```

**Comment by flaviuse** [comment]
I installed Outline previously for the documentation of a startup, I wanted to run my own self hosted version for taking notes but the trick showed by @pfista does not work for me, I run into a timeout when trying a loging with my gmail account, it seems to be a problem with the oauth tokens but I could not find the issue. Any idea : `2020-05-03T20:13:57.283623+00:00 heroku[router]: at=info method=GET path="/auth/google.callback?code=4%2FzQEWd7dCOXkNtIvqCze6W0HBUiEafPOdYgAH6Yh-Z4TQO3WzlHG37tS4_mqnLrePX9s_DkyNgA-UwE0YnD-B8-A&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=consent" host=mydocumentation.herokuapp.com request_id=7f338704-547c-4e02-b3ce-befa3b99f6dc fwd="81.185.174.203" dyno=web.1 connect=8ms service=119ms status=500 bytes=737 protocol=https

2020-05-03T20:14:40+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.285 sample#load-avg-5m=0.225 sample#load-avg-15m=0.175 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11709784kB sample#memory-cached=818268kB sample#memory-redis=447136bytes sample#hit-rate=0.0099302 sample#evicted-keys=0

2020-05-03T20:14:40+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.11 sample#load-avg-5m=0.19 sample#load-avg-15m=0.17 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705396kB sample#memory-cached=818272kB sample#memory-redis=488088bytes sample#hit-rate=0.0097529 sample#evicted-keys=0

2020-05-03T20:18:05+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.065 sample#load-avg-5m=0.12 sample#load-avg-15m=0.145 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705128kB sample#memory-cached=818288kB sample#memory-redis=447136bytes sample#hit-rate=0.010077 sample#evicted-keys=0

2020-05-03T20:21:18+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.13 sample#load-avg-5m=0.14 sample#load-avg-15m=0.15 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705600kB sample#memory-cached=818288kB sample#memory-redis=446936bytes sample#hit-rate=0.010031 sample#evicted-keys=0

2020-05-03T20:24:43+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.115 sample#load-avg-5m=0.14 sample#load-avg-15m=0.145 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11705028kB sample#memory-cached=818296kB sample#memory-redis=447136bytes sample#hit-rate=0.010086 sample#evicted-keys=0

2020-05-03T20:27:21.948842+00:00 heroku[router]: at=info method=GET path="/" host=mydocumentation.herokuapp.com request_id=0284563f-b459-47bf-9832-331a150de232 fwd="81.185.174.203" dyno=web.1 connect=6ms service=46ms status=200 bytes=4679 protocol=https

2020-05-03T20:27:23.483545+00:00 heroku[router]: at=info method=GET path="/auth/google" host=mydocumentation.herokuapp.com request_id=321bb799-a52a-478b-8f02-14ad85f62d3b fwd="81.185.174.203" dyno=web.1 connect=1ms service=4ms status=302 bytes=1403 protocol=https

2020-05-03T20:24:43+00:00 app[heroku-redis]: source=REDIS addon=redis-pointy-74609 sample#active-connections=7 sample#load-avg-1m=0.13 sample#load-avg-5m=0.135 sample#load-avg-15m=0.14 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=11704432kB sample#memory-cached=818300kB sample#memory-redis=488088bytes sample#hit-rate=0.0099278 sample#evicted-keys=0

2020-05-03T20:27:56.474645+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/auth/google.callback?code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=consent" host=mydocumentation.herokuapp.com request_id=3a23f0a1-fe57-4fb0-9231-d3bebd3bf92e fwd="81.185.174.203" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https

2020-05-03T20:27:56.810447+00:00 heroku[router]: at=info method=GET path="/auth/google.callback?code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid&authuser=0&prompt=consent" host=mydocumentation.herokuapp.com request_id=eabb92d7-479f-4c6b-9141-c761b3f3f709 fwd="81.185.174.203" dyno=web.1 connect=1ms service=80ms status=500 bytes=737 protocol=https

2020-05-03T20:27:56.811296+00:00 app[web.1]: GaxiosError: invalid_grant

2020-05-03T20:27:56.811337+00:00 app[web.1]:     at Gaxios._request (/app/node_modules/gaxios/src/gaxios.ts:109:15)

2020-05-03T20:27:56.811339+00:00 app[web.1]:     at runMicrotasks (<anonymous>)

2020-05-03T20:27:56.811339+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

2020-05-03T20:27:56.811340+00:00 app[web.1]:     at OAuth2Client.getTokenAsync (/app/node_modules/google-auth-library/build/src/auth/oauth2client.js:122:21) {

2020-05-03T20:27:56.811341+00:00 app[web.1]:   response: {

2020-05-03T20:27:56.811342+00:00 app[web.1]:     config: {

2020-05-03T20:27:56.811342+00:00 app[web.1]:       method: 'POST',

2020-05-03T20:27:56.811343+00:00 app[web.1]:       url: 'https://oauth2.googleapis.com/token',

2020-05-03T20:27:56.811344+00:00 app[web.1]:       data: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-ldah0htukrb4nrkoge0rqmh71m5lkadg.apps.googleusercontent.com&client_secret=t5zmCfx6Dm6CFh2gNw-i3FfD&redirect_uri=http%3A%2F%2Fmydocumentation.herokuapp.com%2Fauth%2Fgoogle.callback&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811345+00:00 app[web.1]:       headers: [Object],

2020-05-03T20:27:56.811345+00:00 app[web.1]:       params: [Object: null prototype] {},

2020-05-03T20:27:56.811345+00:00 app[web.1]:       paramsSerializer: [Function: paramsSerializer],

2020-05-03T20:27:56.811346+00:00 app[web.1]:       body: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-ldah0htukrb4nrkoge0rqmh71m5lkadg.apps.googleusercontent.com&client_secret=t5zmCfx6Dm6CFh2gNw-i3FfD&redirect_uri=http%3A%2F%2Fmydocumentation.herokuapp.com%2Fauth%2Fgoogle.callback&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811346+00:00 app[web.1]:       validateStatus: [Function: validateStatus],

2020-05-03T20:27:56.811347+00:00 app[web.1]:       responseType: 'json'

2020-05-03T20:27:56.811347+00:00 app[web.1]:     },

2020-05-03T20:27:56.811347+00:00 app[web.1]:     data: { error: 'invalid_grant', error_description: 'Bad Request' },

2020-05-03T20:27:56.811348+00:00 app[web.1]:     headers: {

2020-05-03T20:27:56.811348+00:00 app[web.1]:       'alt-svc': 'h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',

2020-05-03T20:27:56.811349+00:00 app[web.1]:       'cache-control': 'private',

2020-05-03T20:27:56.811349+00:00 app[web.1]:       connection: 'close',

2020-05-03T20:27:56.811349+00:00 app[web.1]:       'content-encoding': 'gzip',

2020-05-03T20:27:56.811350+00:00 app[web.1]:       'content-type': 'application/json; charset=utf-8',

2020-05-03T20:27:56.811350+00:00 app[web.1]:       date: 'Sun, 03 May 2020 20:27:56 GMT',

2020-05-03T20:27:56.811350+00:00 app[web.1]:       server: 'scaffolding on HTTPServer2',

2020-05-03T20:27:56.811351+00:00 app[web.1]:       'transfer-encoding': 'chunked',

2020-05-03T20:27:56.811351+00:00 app[web.1]:       vary: 'Origin, X-Origin, Referer',

2020-05-03T20:27:56.811351+00:00 app[web.1]:       'x-content-type-options': 'nosniff',

2020-05-03T20:27:56.811352+00:00 app[web.1]:       'x-frame-options': 'SAMEORIGIN',

2020-05-03T20:27:56.811352+00:00 app[web.1]:       'x-xss-protection': '0'

2020-05-03T20:27:56.811352+00:00 app[web.1]:     },

2020-05-03T20:27:56.811352+00:00 app[web.1]:     status: 400,

2020-05-03T20:27:56.811353+00:00 app[web.1]:     statusText: 'Bad Request',

2020-05-03T20:27:56.811353+00:00 app[web.1]:     request: { responseURL: 'https://oauth2.googleapis.com/token' }

2020-05-03T20:27:56.811354+00:00 app[web.1]:   },

2020-05-03T20:27:56.811354+00:00 app[web.1]:   config: {

2020-05-03T20:27:56.811354+00:00 app[web.1]:     method: 'POST',

2020-05-03T20:27:56.811354+00:00 app[web.1]:     url: 'https://oauth2.googleapis.com/token',

2020-05-03T20:27:56.811355+00:00 app[web.1]:     data: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-ldah0htukrb4nrkoge0rqmh71m5lkadg.apps.googleusercontent.com&client_secret=t5zmCfx6Dm6CFh2gNw-i3FfD&redirect_uri=http%3A%2F%2Fmydocumentation.herokuapp.com%2Fauth%2Fgoogle.callback&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811355+00:00 app[web.1]:     headers: {

2020-05-03T20:27:56.811355+00:00 app[web.1]:       'Content-Type': 'application/x-www-form-urlencoded',

2020-05-03T20:27:56.811356+00:00 app[web.1]:       'User-Agent': 'google-api-nodejs-client/5.10.1',

2020-05-03T20:27:56.811356+00:00 app[web.1]:       'x-goog-api-client': 'gl-node/14.1.0 auth/5.10.1',

2020-05-03T20:27:56.811356+00:00 app[web.1]:       Accept: 'application/json'

2020-05-03T20:27:56.811356+00:00 app[web.1]:     },

2020-05-03T20:27:56.811357+00:00 app[web.1]:     params: [Object: null prototype] {},

2020-05-03T20:27:56.811357+00:00 app[web.1]:     paramsSerializer: [Function: paramsSerializer],

2020-05-03T20:27:56.811357+00:00 app[web.1]:     body: 'code=4%2FzQG8e-B2UiyP1J56oX4m--fSQYc3YepEXIMuCkVKP3bdQwYQ3cxCxmSQ0lEPgW_JPDlIGV8CRIZGGuSCXCAUZ_g&client_id=383471037841-ldah0htukrb4nrkoge0rqmh71m5lkadg.apps.googleusercontent.com&client_secret=t5zmCfx6Dm6CFh2gNw-i3FfD&redirect_uri=http%3A%2F%2Fmydocumentation.herokuapp.com%2Fauth%2Fgoogle.callback&grant_type=authorization_code&code_verifier=',

2020-05-03T20:27:56.811358+00:00 app[web.1]:     validateStatus: [Function: validateStatus],

2020-05-03T20:27:56.811358+00:00 app[web.1]:     responseType: 'json'

2020-05-03T20:27:56.811358+00:00 app[web.1]:   },

2020-05-03T20:27:56.811358+00:00 app[web.1]:   code: '400'

2020-05-03T20:27:56.811359+00:00 app[web.1]: }

`

**Comment by ahvahsky2008** [comment]
> --- a/server/auth/google.js
> +++ b/server/auth/google.js
> @@ -39,10 +39,12 @@ router.get('google.callback', auth({ required: false }), async ctx => {
>      url: 'https://www.googleapis.com/oauth2/v1/userinfo',
>    });
> 
> -  if (!profile.data.hd) {
> -    ctx.redirect('/?notice=google-hd');
> -    return;
> +  // Hack to allow Gmail (non GSuite) accounts
> +  if (!profile.data.hd) {
> +          profile.data.hd = "teamname.com"
> 
>    }

sorry, but its not works.

**Comment by ahvahsky2008** [comment]
How simple allow login with gmail

**Comment by ahvahsky2008** [comment]
> Hey @brpaz, if you're running Outline yourself it's easy to change the code to allow this.
> 
> Here's an example below of what you could change to allow Gmail accounts:
> 
> ```
> --- a/server/auth/google.js
> +++ b/server/auth/google.js
> @@ -39,10 +39,12 @@ router.get('google.callback', auth({ required: false }), async ctx => {
>      url: 'https://www.googleapis.com/oauth2/v1/userinfo',
>    });
> 
> -  if (!profile.data.hd) {
> -    ctx.redirect('/?notice=google-hd');
> -    return;
> +  // Hack to allow Gmail (non GSuite) accounts
> +  if (!profile.data.hd) {
> +          profile.data.hd = "teamname.com"
> 
>    }
> ```

can you share new version?

**Comment by mesuutt** [comment]
I made a change for allowing only given gmail accounts(for personal use). [commit](https://github.com/mesuutt/outline/commit/7936a5d73298c1d1e9d6d8e442f8d39c9cc8e757)

**Comment by ahvahsky2008** [comment]
> I made a change for allowing only given gmail accounts(for personal use). [commit](https://github.com/mesuutt/outline/commit/7936a5d73298c1d1e9d6d8e442f8d39c9cc8e757)

What meaning TEAMID?

**Comment by ahvahsky2008** [comment]
How use it simply as notion.so?

**Comment by almereyda** [comment]
> can you share new version?

After the recent merge of #1934, the approaches described here can be adapted more easily into a separate authentication provider. #1953 in respect shows an example about which movable parts would have to be touched for that.

**Comment by victorhooi** [comment]
Is it possible to add this feature into Outline itself?

Or is there some technical reason it can't be done?

**Comment by antonzapevalov** [comment]
@tommoor Is it planned to support authorization through personal Google accounts for self-hosted?

**Comment by dreyinger** [comment]
I would appreciate that feature too. Would be great for testing and personal use.

**Comment by bbloomberg** [comment]
We would appreciate this feature as well

**Comment by ivorsmorenburg** [comment]
Open Source... yes right..

**Comment by skelewir** [comment]
If anyone still wondering how to solve this - just use google as openid provider:
OIDC_CLIENT_ID=your client id from google app
OIDC_CLIENT_SECRET=your client secret from google app
OIDC_AUTH_URI=https://accounts.google.com/o/oauth2/v2/auth
OIDC_TOKEN_URI=https://oauth2.googleapis.com/token
OIDC_USERINFO_URI=https://openidconnect.googleapis.com/v1/userinfo

**Comment by Plorenzo** [comment]
Thanks @skelewir !

This should be clearly documented in the installation guide.. It's a super common use case and it's clear that many people had to google around for a while until they discovered this answer.

**Comment by technowhizz** [comment]
@vidjg If you are still seeing errors then you need to update your callback URI in Google Oauth to:

```
https://<URL>/auth/oidc.callback
```
Then save the OAuth consent screen and wait a couple of minutes as it could take a few minutes to update

**Comment by memphisraynz** [comment]
> > If anyone still wondering how to solve this - just use google as openid provider: OIDC_CLIENT_ID=your client id from google app OIDC_CLIENT_SECRET=your client secret from google app OIDC_AUTH_URI=https://accounts.google.com/o/oauth2/v2/auth OIDC_TOKEN_URI=https://oauth2.googleapis.com/token OIDC_USERINFO_URI=https://openidconnect.googleapis.com/v1/userinfo
> 
> Thank you [@skelewir](https://github.com/skelewir) ! Your instruction works like a charm! However, in this way, it seems like anyone with a gmail account is able to login my Outline, and even when in testing mode for the google project, setting the "Test User" in the Google OAuth consent screen is not working.
> 
> Looking forward to your help, thanks!

Were you ever able to do anything about anyone being able to auth to your instace using OIDC when set to Google?

**Comment by smaciver** [comment]
> Were you ever able to do anything about anyone being able to auth to your instace using OIDC when set to Google?

Ditto. I don't understand what I'm missing allowing anyone with a gmail account to access.

**Comment by memphisraynz** [comment]
I'm sure it can be done. The generic OIDC setup works, but then anyone can create and account which is very poor security, and the feature to prevent those is locked behind a paywall.

**Comment by almereyda** [comment]
You are still free to use an Outline instance that has SMTP configured only with email accounts. After seeding an initial admin user, as described in https://github.com/outline/outline/issues/1881#issuecomment-2008582557, you would be able to invite other users with their email address. Considering SMTP is configured correctly, those could be any email recipients, including those using the Google service.

This would give you an option to login with a personal GMail account.

**Comment by smaciver** [comment]
yeah I got it all working with the OIDC setup but that's good info regarding the paywall. That pretty much wraps it up for me.

**Comment by dvkolesnikov** [comment]
> The generic OIDC setup works, but then anyone can create and account which is very poor security

As a workaround, you can set an impossible domain in the `Allowed Domains` in your teamspace Security settings, so that nobody can create a new account. Existing accounts still will be able to login.

**Comment by smaciver** [comment]
> > The generic OIDC setup works, but then anyone can create and account which is very poor security
> 
> As a workaround, you can set an impossible domain in the `Allowed Domains` in your teamspace Security settings, so that nobody can create a new account. Existing accounts still will be able to login.

Where is this "Allowed Domains" setting?

**Comment by dvkolesnikov** [comment]
@smaciver Click on your workspace -> Settings -> Security. It will be the 5th item in the list.

**Comment by smaciver** [comment]
> [@smaciver](https://github.com/smaciver) Click on your workspace -> Settings -> Security. It will be the 5th item in the list.

I'm an idiot. I wasn't logging in with my admin email. I see it now. Thanks
