### ISSUE TITLE
"Internal Server Error" for Slack and Google login

### ISSUE THREAD

**Issue by Paradiddley** [outline/outline#923]
I'm self hosting and I can't get the OAuth to work as both Slack and Google return the same error;

```
Error: unable to verify the first certificate
      at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
      at emitNone (events.js:106:13)
      at TLSSocket.emit (events.js:208:7)
      at TLSSocket._finishInit (_tls_wrap.js:639:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
``` 

It's hosted on a VPS that's configured to only be accessible to internal staff using a whitelist of IPs. For this reason I only created Let's Encrypt certificates and visiting the home page it's showing as a valid. 

<img width="277" alt="Screenshot 2019-03-28 at 11 19 07" src="https://user-images.githubusercontent.com/2915723/55153949-9a9eb480-514b-11e9-8920-4d2be7b9f6c3.png">

How I've set this up (which I hope is valid, I'm not savvy with node.js apps) is by having a reverse proxy setup on Nginx and serving the app locally using PM2 on port 3000. I'm not using Docker. Here's my Nginx config;

```
server {
  listen 443 ssl; # managed by Certbot
  server_name wiki.[redacted];
  root /home/forge/wiki.[redacted]/dist;
  index index.html;

  ssl_certificate /etc/letsencrypt/live/wiki.[redacted]/cert.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/wiki.[redacted]/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

  access_log /var/log/nginx/wiki.[redacted].access.log;
  error_log /var/log/nginx/wiki.[redacted].error.log;

  location / {
    proxy_pass http://localhost:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_bypass $http_upgrade;
  }
}

server {
  if ($host = wiki.[redacted]) {
    return 301 https://$host$request_uri;
  } # managed by Certbot

  listen 80;
  server_name wiki.[redacted];
  return 404; # managed by Certbot
}
```

And here's the nginx.conf that it's extended from.

```
user forge;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	multi_accept on;
}

http {
	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	server_names_hash_bucket_size 128;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/server.whitelist;
	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```

I've got a feeling I'm missing some trivial step here, or doing something silly.

**Comment by tommoor** [comment]
I'm sorry, I'm unable to provide support for the configuration of self hosted installations. The production version of Outline does not use nginx.
