### ISSUE TITLE
S3  AccessDenied: Access Denied

### ISSUE THREAD

**Issue by kevalkothari** [outline/outline#947]
Hello Outline Team,

Thanks for the great product, I am trying to set it up and got stuck with below errors 

`  AccessDenied: Access Denied
      at Request.extractError (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/services/s3.js:585:35)
      at Request.callListeners (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/www/www/smart_webtech-app-wiki3/node_modules/aws-sdk/lib/event_listeners.js:299:13)
      at emitNone (events.js:111:20)
      at IncomingMessage.emit (events.js:208:7)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickDomainCallback (internal/process/next_tick.js:219:9)`

I have assigned **AmazonS3FullAccess** to an  IAM user and I have .env setup correctly with all below details.

`
# AWS credentials (optional in dev)
AWS_ACCESS_KEY_ID=AKNOYTHLV3YPAPQ
AWS_SECRET_ACCESS_KEY=d3kIwyF1NPAVLouK7sLL536SooKxQZhD
AWS_S3_UPLOAD_BUCKET_URL=https://s3.amazonaws.com
AWS_S3_UPLOAD_BUCKET_NAME=wikibucket
AWS_S3_UPLOAD_MAX_SIZE=26214400`

But every time getting above Access Denied error. am I missing something?  

Any help would be appreciated.

Thanks,
Keval

**Comment by kevalkothari** [comment]
I was able to resolve it. issue was with S3 permission. However I still not able to run it due to another issue which I will post as issue.

**Comment by tommoor** [comment]
Hi @kevalkothari – GitHub issues is not private, you posted your AWS access information on the public internet, you should immediately revoke those credentials or you are likely to see abuse of your account.

**Comment by kevalkothari** [comment]
I had revoked it. thanks

**Comment by JohnKimDev** [comment]
> I was able to resolve it. issue was with S3 permission. However I still not able to run it due to another issue which I will post as issue.

@kevalkothari I am having the same issue. what is the S3 permission setting you have to make it work if you don't mind sharing?

**Comment by deatherving** [comment]
Same issue. Any ideas?
