### ISSUE TITLE
Image uploads broken on 0.33.0

### ISSUE THREAD

**Issue by captn3m0** [outline/outline#993]
Getting the following error while trying to upload an image.

Last tested version was 0.29.0

```
  TypeError: Data must be a string or a buffer
      at Hmac.update (crypto.js:99:16)
      at hmac (/opt/outline/server/utils/s3.js:18:6)
      at getSignature (/opt/outline/server/utils/s3.js:58:19)
      at _callee4$ (/opt/outline/server/api/users.js:104:28)
      at tryCatch (/opt/outline/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (/opt/outline/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (/opt/outline/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (/opt/outline/server/api/users.js:45:191)
      at /opt/outline/server/api/users.js:45:361
      at <anonymous>
```

**Comment by captn3m0** [comment]
Shows up till I downgrade to `0.30.0`. Might be a configuration issue at our end, verifying

**Comment by tommoor** [comment]
You must set the `AWS_REGION` environment variable to something like `us-east-1` as of `v0.31.0`

**Comment by captn3m0** [comment]
Thanks a lot :+1:
